### ISSUE TITLE
phyluce_snp_bwa_multiple_align error - unable to locate gatk tools

### ISSUE THREAD

**Issue by bryansmclean** [faircloth-lab/phyluce#104]
I am putting a multispecies dataset through the SNP extraction workflow now formally incorporated into phyluce. Hitting a snag when calling phyluce_snp_bwa_multiple_align that I hope someone can help me with.

Specifically the script runs but I get errors thrown in log files as follows:

in xxx.pe.picard-clean-out.log:
Unable to access jarfile /apps/gatk/4.0.1.1/CleanSam.jar

in xxx.pe.picard-RG-out.log 
Unable to access jarfile /apps/gatk/4.0.1.1/AddOrReplaceReadGroups.jar

resulting in the phyluce error:

OSError: [Errno 2] No such file or directory: "...Uarmatus_NK216605-CL.bam"

I realize this isnt a phyluce bug but still hoping someone has some insight. Seems like these gatk tools are no longer packaged as standalone jar files, but Im not sure what other program (or possibly what part of the phyluce pipeline) is trying to call them. Ive tried both older and newer versions of gatk/picard but this didnt resolve it. Currently running these modules:

samtools/0.1.19
bedtools/2.19.1
bwa/0.7.7
gatk/4.0.1.1
picard/2.18.3

thanks!
Bryan

**Comment by bryansmclean** [comment]
Update: could not resolve this issue on our computing cluster but am running it locally and drew important info from a previous [post](https://github.com/faircloth-lab/phyluce/issues/101).

**Comment by brantfaircloth** [comment]
This **should** be fixed in v1.6.2 and the package that will shortly be uploaded to bioconda.  That said, I have not extensively tested those fixes.  Also, the GATK used above will not work (in any form).  You may need to install GATK 3.x - but, as of right now, `phyluce_snp_bwa_multiple_align` does not require this.

**Comment by bryansmclean** [comment]
thanks Brant!
