### ISSUE TITLE
An error in running 'phyluce_probe_get_tiled_probes'

### ISSUE THREAD

**Issue by ClearloveMiao** [faircloth-lab/phyluce#106]
Hi,Brant!

When I was running the `phyluce_probe_get_tiled_probes` to design the temporary baits sets, it has reported such error:

![image](https://user-images.githubusercontent.com/37678675/39855302-fb389dec-545d-11e8-9472-d23f7e5ef573.png)

And the script is just like the below:

`phyluce_probe_get_tiled_probes \`
    `--input CuCh_PB+6.fasta \`
    `--probe-prefix "exon-" \`
    `--design Cu-v1 \`
    `--designer Miao \`
    `--tiling-density 3 \`
    `--two-probes \`
    `--probe-length 180 \`
    `--overlap middle \`
    `--masking 0.25 \`
    `--remove-gc \`
    `--output CuCh_PB+6.temp.probes`

It seems that there is something wrong with the header of sequence of the base genome, but I don't know how to deal with it. So, can you give me some help for fixing it? And can I send the input fasta file to your e-mail? 

Thanks for any help and suggestion!

**Comment by ClearloveMiao** [comment]
Another question, can you give me your e-mail? It seems like `brant@faircloth-­lab.org` is not your e-mail, because I failed to send mail to `brant@faircloth-­lab.org`.
Many thanks!

**Comment by mmaggia** [comment]
Hi Jibin!

I went through the same error and I would like to know if you have found how to deal with it?

Thank you for your help!
Best,
Marie-Eugenie

**Comment by ClearloveMiao** [comment]
@mmaggia 
Hi Eugenie!
So sorry about that. I haven't deal with this error, so I haven't use pyhluce next.
Do you know another methods?
Thanks a lot!

**Comment by mmaggia** [comment]
@ClearloveMiao 
Hi Jibin!
In my case the problem was from the headers. In fact, one of my genomes was not from NCBI and in the headers there was an additional bar-signe "|" that was causing the problem. I simplified the headers and then it works!
Best,
Marie-Eugenie

**Comment by ClearloveMiao** [comment]
@mmaggia 
Thank you very much!
