### ISSUE TITLE
phasing uce snps

### ISSUE THREAD

**Issue by mcfaddenlab** [faircloth-lab/phyluce#107]
hi brant,

i have successfully run through the snp phasing tutorial ii. In the phyluce_snp_phase_uces.log I have 19/96 species in which only 1 locus was written per file. example:
018-05-15 02:34:48,287 - phyluce_snp_phase_uces - INFO - Wrote 1 loci for Coral94
2018-05-15 02:34:48,288 - phyluce_snp_phase_uces - INFO - Wrote 1 loci for Coral100
2018-05-15 02:34:48,458 - phyluce_snp_phase_uces - INFO - Wrote 756 loci for Coral66

So it appears that loci for these 19 species were not phased.

In the phased_reads/fastas/*unphased.clean.balanced.fasta files, the header info says
 ">uce-113031_Coral94 |uce-113031_hom" 

I assume then these 19 species are predicted as homozygotes across all loci? ( a little surprised by this-but then selfing in corals is common)

And if the sequences were not phased, then they do not get included in the joined_allele_sequences_all_samples.fasta ?? (Np. I just need to combine them all into the file somehow...)

Also, if there are homozygous loci, are they deleted from the *.0.clean.balanced.fasta and *1.clean.balanced.fasta files? 

Andrea

**Comment by brantfaircloth** [comment]
I'm not sure - we've not run data through where this could ever be a possibility...

I probably need to take a look at this with some of your data, but unfortunately, I don't have time to do that right now (and won't for a while).  You might make some progress by doing a quick and dirty SNP calling against a few of the suspect BAM files using samtools (see the help page) - the VCF files from that procedure will potentially give you a clearer idea of what type of data you have at different sites.

**Comment by mcfaddenlab** [comment]
Hey~ thanks! I will see if i can pull anything out of the other files. no real rush on any of this. maybe its something we can visit again in the future.

**Comment by Ptero64** [comment]
Hello,
I am interested to use the new part of your pipeline to phase reads. I will use the python script phyluce_snp_phase_uces but I would like to ask you which options of samtools phase are used in it (-q 3 -AF ?). I am not good with Biopython and I didn't found the info in the script.
Thanks
Nicolas

**Comment by brantfaircloth** [comment]
Hi.  Here are the options:

```
cmd = [
        get_user_path("samtools", "samtools"),
        "phase",
        "-A",
        "-F",
        "-Q",
        "20",
        "-b",
        sample_dir,
        bam
]
```

**Comment by Ptero64** [comment]
Thanks a lot.

**Comment by brantfaircloth** [comment]
👍

**Comment by brantfaircloth** [comment]
**May** have fixed this in newest version (`v.1.6.6`), which will probably be up on bioconda in the next few days (it's been posted, just needs to be approved).  I ran the updated code against the test data from tutorial 1 and everything works, as expected, again.  Still not sure how that will work against your specific data, but it's working against the test data, at least (and producing the expected number of loci).
