### ISSUE TITLE
Porting phyluce to bioconda

### ISSUE THREAD

**Issue by brantfaircloth** [faircloth-lab/phyluce#110]
Current phyluce, when installed using conda, pulls packages from a repository that I maintained that was similar to bioconda in spirit (and existed before bioconda).  Since I set things up that way, bioconda has come along and is an excellent source of conda packages.  Additionally, I'm a contributor to bioconda, and it's stupid to keep packages in two places. So, the current plan is to port phyluce to bioconda so that `conda install` pulls builds from bioconda.

## Benefits
* Less overall maintenance of the phyluce package
* Faster turnaround of phyluce versions
* Overall better experience

## Potential Problems

This is likely going to break a couple of things, namely:

* Trinity (current newish builds in bioconda don't work on macos
* GATK - their license sucks and makes things difficult
* phyluce assemblo_trinity
* phyluce coverage computations (which currently use GATK) along with many other packages to compute coverage

**Comment by brantfaircloth** [comment]
1.6.2 pushed to bioconda.  Awaiting merge of pull request in to main.

**Comment by drwhitehouse** [comment]
@brantfaircloth - good work, thanks. I took your advice and used illumiprocessor from bioconda and somehow got a free java 1.8 too (from conda) which should make putting this in a container easier.

**Comment by brantfaircloth** [comment]
haha - yeah, bioconda makes things easier (we even get containers for each app: https://quay.io/repository/biocontainers/illumiprocessor, not sure if those are helpful for your purposes, however).

**Comment by brantfaircloth** [comment]
phyluce is now available from @bioconda.
