### ISSUE TITLE
Phasing UCE data - phasing mapped reads wrote 1 allele

### ISSUE THREAD

**Issue by nnbuainain** [faircloth-lab/phyluce#113]
Hi,

I ran the whole tutorial II with apparently no errors in the terminal during the process. However, when I finish the Phasing mapped reads I have only one loci written for all my samples. At first I ran with only 6 samples and then with the whole taxa-set and still got the same results.
When I check the logs on the previous step (mapping-results), none show explicit error messages except "taxa.pe.picard-clean-out.log" and taxa.se.picard-clean-out.log. Those show several lines as follows:

Ignoring SAM validation error: ERROR: Record 818, Read name J00160:100:HLY23BBXX:5:1101:32065:6484, MAPQ should be 0 for unmapped read.
Ignoring SAM validation error: ERROR: Record 1594, Read name J00160:100:HLY23BBXX:5:1101:18578:11390, MAPQ should be 0 for unmapped read.
Ignoring SAM validation error: ERROR: Record 1601, Read name J00160:100:HLY23BBXX:5:1101:31507:11425, MAPQ should be 0 for unmapped read.

Apparently, this might be error with picard. Looking at other forums several people suggest changing the parameter: VALIDATION_STRINGENCY=SILENT to VALIDATION_STRINGENCY=LENIENT in the code. I did that to picard.py in phyluce/lib/python2.7/site-packages/phyluce/ but i still got the same result.

I'm not sure if this is the same issue as #107 as I got the same results for 6 and 74 taxa I also got the same with a different taxa set of a colleague in two different PC's (both with the same system though).

Does anyone have clue of what's going on? I appreciate any help regarding the issue.

thank you very much.
Best,

**Comment by brantfaircloth** [comment]
What types of data are these (organism, marker)?  How did you collect these data and what is the read depth?  If you run tutorial 2 with data from tutorial 1, what results do you get?

**Comment by nnbuainain** [comment]
I'm using passerine bird species with a UCE sequencing done by rapidgenomics. Most DNA were obtained from tissue and blood samples, but some were toepads. In the first ran (with 6 samples) I chose only samples obtained from tissue.
I did the entire data processing with the phyluce pipeline (following tutorial I and II) so the results I got were the ones I mentioned. Was that the question?
I don't think I did any procedure to check read depths. Should that be any output from the standard pipeline? I would guess the read depths are usually high, or at least should be good enough for some samples.

**Comment by brantfaircloth** [comment]
Yes - thank you - that helps.  Can you run 1-2 of the species (gator, chicken, etc) from tutorial 1 through the pipeline to see if those work as expected for you?  Probably also best to make sure you have the latest phyluce (v1.6.3 is available; v1.6.4 will be up in a day or so).

**Comment by nnbuainain** [comment]
Dear Brant,

Sorry for the long delay. I finally got to the end of the pipeline using the tutorial data (Alligator, Chicken and mouse). I got the exact same error that I had before using my own data.

**Comment by brantfaircloth** [comment]
I'm working on this now - not sure how long fix will take.

**Comment by brantfaircloth** [comment]
Should have fixed this in newest version (`v.1.6.6`), which will probably be up on bioconda in the next few days (it's been posted, just needs to be approved).  I ran the updated code against the test data from tutorial 1 and everything works, as expected, again.

**Comment by nnbuainain** [comment]
Thank you!!!
