### ISSUE TITLE
error report in phyluce_align_explode_alignments 

### ISSUE THREAD

**Issue by nnbuainain** [faircloth-lab/phyluce#114]
Hello,

Just would like to report a couple of errors I got during the phyluce_align_explode_alignments when I was running Tutorial II.

The command line suggested in the tutorial is:

phyluce_align_explode_alignments --input mafft-nexus-edge-trimmed --output-dir exploded-fastas --by-taxon

1)The correct argument for the input file apparently is --alignments and not --input. 

Even so,

2)I kept getting the following error:
Traceback (most recent call last):
  File "/home/croizat/anaconda2/envs/phyluce/bin/phyluce_align_explode_alignments", line 169, in <module>
    main()
  File "/home/croizat/anaconda2/envs/phyluce/bin/phyluce_align_explode_alignments", line 124, in main
    d[shortname] = open(os.path.join(args.output, new_file), 'w')
AttributeError: 'Namespace' object has no attribute 'output'

The only way I could get that to run was changing line 42 in phyluce_align_explode_alignments from --output-dir to --output .

Then, my final command line was:

phyluce_align_explode_alignments --alignments mafft-nexus-edge-trimmed/ --output exploded-fastas-reference/ --by-taxon --input-format nexus 

I'm not sure this is true issue or if that was the proper way to fix it but maybe someone will have the same problem. 

Best,

**Comment by brantfaircloth** [comment]
Thank you for reporting these - I updated the code to fix.  The new package (phyluce 1.6.4) with the updated code will be available on bioconda in a day or so, or you can work from repository.

**Comment by zhangpizhu** [comment]
Hello Brant,
If I change the Exploded-fasta files, how do I convert all the Exploded - fasta files to Nexus files for downstream analysis.
