### ISSUE TITLE
phyluce_assembly_get_fastas_from_match_counts: AttributeError

### ISSUE THREAD

**Issue by TomSemple** [faircloth-lab/phyluce#115]
Hi Brant and everyone,
I'm getting the error below when I run `phyluce_assembly_get_fastas_from_match_counts`. It seems to be a problem with the Trinity headers (either in the contig files or maybe the lastz files?), but I can't work out how to resolve it. 

It runs fine when I use a few test samples that have very simple headers like `t132`, but not for some of my other files that have awfully long Trinity headers, e.g.:
`TRINITY_DN166311_c0_g1_i1 len=222 path=[1:0-221] [-1, 1, -2]`
I modified the `phyluce.conf` Trinity regex to accommodate both of these headers, checked it on RegExr.com, and it worked fine for:
`phyluce_assembly_get_fasta_lengths`
and
`phyluce_assembly_match_contigs_to_probes`
which successfully generated the match database (exported as csv and checked in Excel).

So, I wonder if `phyluce_assembly_get_fastas_from_match_counts` is using a different regex from the one in `phyluce.conf`, or if it's more sensitive to different sample names?
My sample names are all in the format: "R1200_Phymatothynnus".

Any suggestions would be greatly appreciated!

`2018-07-11 11:06:28,670 - phyluce_assembly_get_fastas_from_match_counts - INFO - Parsing and renaming contigs for R1200_Phymatothynnus
Traceback (most recent call last):
  File "/Users/thomassemple/anaconda2/bin/phyluce_assembly_get_fastas_from_match_counts", line 261, in <module>
    main()
  File "/Users/thomassemple/anaconda2/bin/phyluce_assembly_get_fastas_from_match_counts", line 229, in main
    name = get_contig_name(seq.id).lower()
  File "/Users/thomassemple/anaconda2/bin/phyluce_assembly_get_fastas_from_match_counts", line 155, in get_contig_name
    return match.groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
`

**Comment by brantfaircloth** [comment]
HI Tom,

The fix for this is coming, just not up on bioconda yet.  You could wait until that's up, or you could create/edit `~/.phyluce.conf` to contain:
```
[headers]
trinity:comp\d+_c\d+_seq\d+|c\d+_g\d+_i\d+|TR\d+\|c\d+_g\d+_i\d+|TRINITY_DN\d+_c\d+_g\d+_i\d+
```

**Comment by brantfaircloth** [comment]
Now just waiting for final approval by bioconda folks to get new package up.  You will want `phyluce 1.6.5`, which should fix this problem.

-b

**Comment by brantfaircloth** [comment]
ok - new version avail. from bioconda. closing this but feel free to re-open if new version (or suggestion above) does not fix.

**Comment by TomSemple** [comment]
Thanks for the quick reply Brant! 
I can only see 1.6.2 and 1.6.3 on Bioconda, but I ended up simplifying all of my Trinity headers to `t1`, `t2`, etc. and it worked fine. So all good!
