### ISSUE TITLE
What parameters are used for Trimmomatic in illumiprocessor

### ISSUE THREAD

**Issue by jojoventure** [faircloth-lab/phyluce#116]
Hi Brant,
I have a question about the settings of Trimmomatic in illumiprocessor. What are the default settings, and is it possible to change them, for example, ILLUMINACLIP and SLIDINGWINDOW?
Best,
Chen

**Comment by brantfaircloth** [comment]
you can change them by editing the source code for illumiprocessor, specifically for PE reads [here](https://github.com/faircloth-lab/illumiprocessor/blob/master/illumiprocessor/core.py#L274-L287) and for SE reads [here](https://github.com/faircloth-lab/illumiprocessor/blob/master/illumiprocessor/core.py#L198-L207).
