### ISSUE TITLE
Error: Could not parse --min-ac g -> phyluce_snp_phase_uces

### ISSUE THREAD

**Issue by juancholkovich** [faircloth-lab/phyluce#117]
Dear Dr. Faircloth

I was using the function phyluce_snp_phase_uces, and the result of the process was empty fasta files. When I checked the samtools-bcftools-out.log files I see the next message:

Error: Could not parse --min-ac g

As far as I know, the problem is about the version of samtools used apparently.

But I want to ask you if you know the source of this error and How can I run the function phyluce_snp_phase_uces successfully?

Best regards,

Juan.

**Comment by nnbuainain** [comment]
Dear @juancholkovich,
This might be the same error as issue #113 as my samtools-bcftools-out.log files look the same as yours. I still haven't figured out a solution yet. Please let us know if you do.

**Comment by brantfaircloth** [comment]
I'm working on this now.  Not sure how long it will take to fix.

**Comment by brantfaircloth** [comment]
Should have fixed this in newest version (`v.1.6.6`), which will probably be up on bioconda in the next few days (it's been posted, just needs to be approved).  I ran the updated code against the test data from tutorial 1 and everything works, as expected, again.
