### ISSUE TITLE
Trimming the start of reads

### ISSUE THREAD

**Issue by Cryptamydros** [faircloth-lab/phyluce#120]
Hi,
Is there a way of trimming the first _n_ bases of a file using illumiprocessor? I know that by using Trimmomatic as a stand alone program that you can do this by using HEADCROP: but I can't seem to find if there is a way of doing this with illumiprocessor. I want to trim the first 10 bases off my files as the base content at the start of the files is not great and it would be great if this could also be done in illumiprocessor.

Thanks in advance,
Simon

**Comment by brantfaircloth** [comment]
You would need to directly edit the code that calls illumiprocessor, specifically this file in this spot for PE reads: 

https://github.com/faircloth-lab/illumiprocessor/blob/master/illumiprocessor/core.py#L273-L288

so that it looks something like:

```python
cmd = [
            args.trimmomatic,
            "PE",
            "-{}".format(args.phred),
            input[0],
            input[1],
            output[0],
            output[1],
            output[2],
            output[3],
            "ILLUMINACLIP:{}:2:30:10".format(adapters),
            "HEADCROP:5",
            "LEADING:5",
            "TRAILING:15",
            "SLIDINGWINDOW:4:15",
            "MINLEN:{}".format(args.min_len)
]
```

**Comment by Cryptamydros** [comment]
Excellent, that has done the trick. Thank you very much!! This has made my life much easier than going through and trimming them individually with e.g fastx_trimmer.
