### ISSUE TITLE
Illumiprocessor does not run no output is generated

### ISSUE THREAD

**Issue by lostcode-sam** [faircloth-lab/phyluce#121]
Hi,
I am following the steps mentioned in Tutorial I: UCE Phylogenomics. I have created a .conf file as mentioned in https://phyluce.readthedocs.io/en/latest/tutorial-one.html#clean-the-read-data 
and after that I am running following codes -
illumiprocessor \
    --input raw-fastq/ \
    --output clean-fastq \
    --config illumiprocessor.conf \
    --cores 4

It does not run , no error message is shown and clean-fastq directory remains empty.
is this an issue with how phyluce is installed (phyluce and illumiprocessor are in two different environments in anaconda2)

**Comment by brantfaircloth** [comment]
technically, you should be fine in two different environments.  it sound like something is very off if there are zero error messages.  what happens when you simply run `illumiprocessor`?  similarly, what does the content of `illumiprocessor.conf ` look like?  and, what platform are you using (linux, macos, win)?

**Comment by lostcode-sam** [comment]
This is the .conf file
[adapters]
i7:AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC*ATCTCGTATGCCGTCTTCTGCTTG
i5:AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT

[tag sequences]
BFIDT-166:GGAGCTATGG
BFIDT-016:GGCGAAGGTT
BFIDT-045:TTCTCCTTCA
BFIDT-011:CTACAACGGC

[tag map]
Alligator_mississippiensis_GGAGCTATGG:BFIDT-166
Anolis_carolinensis_GGCGAAGGTT:BFIDT-016
Gallus_gallus_TTCTCCTTCA:BFIDT-045
Mus_musculus_CTACAACGGC:BFIDT-011

[names]
Alligator_mississippiensis_GGAGCTATGG:alligator_mississippiensis
Anolis_carolinensis_GGCGAAGGTT:anolis_carolinensis
Gallus_gallus_TTCTCCTTCA:gallus_gallus
Mus_musculus_CTACAACGGC:mus_musculus

if I simply run illumiprocessor
usage: illumiprocessor [-h] --input INPUT --output OUTPUT --config CONFIG
                       [--trimmomatic TRIMMOMATIC] [--min-len MIN_LEN]
                       [--no-merge] [--cores CORES] [--r1-pattern R1_PATTERN]
                       [--r2-pattern R2_PATTERN] [--se]
                       [--phred {phred33,phred64}] [--log-path LOG_PATH]
                       [--verbosity {INFO,WARN,CRITICAL}]
illumiprocessor: error: argument --input is required

And I am using centos on HPC.

[samriddha@localhost uce-tutorial]$ illumiprocessor \
>     --input raw-fastq/ \
>     --output clean-fastq \
>     --config illumiprocessor.conf \
>     --cores 4
[WARNING] Output directory exists, REMOVE [Y/n]? Y
[samriddha@localhost uce-tutorial]$ ls clean-fastq/
[samriddha@localhost uce-tutorial]$

**Comment by brantfaircloth** [comment]
ok, that looks fine.  and, the contents of the `raw-fastq` directory?

**Comment by lostcode-sam** [comment]
[samriddha@localhost uce-tutorial]$ ls raw-fastq/
Alligator_mississippiensis_GGAGCTATGG_L001_R1_001.fastq.gz
Alligator_mississippiensis_GGAGCTATGG_L001_R2_001.fastq.gz
Anolis_carolinensis_GGCGAAGGTT_L001_R1_001.fastq.gz
Anolis_carolinensis_GGCGAAGGTT_L001_R2_001.fastq.gz
Gallus_gallus_TTCTCCTTCA_L001_R1_001.fastq.gz
Gallus_gallus_TTCTCCTTCA_L001_R2_001.fastq.gz
Mus_musculus_CTACAACGGC_L001_R1_001.fastq.gz
Mus_musculus_CTACAACGGC_L001_R2_001.fastq.gz

**Comment by brantfaircloth** [comment]
Ok, also looks fine.  So on CentOS 7, the following works correctly (I just tested it).  Perhaps there is a problem w/ the conda environment and/or the HPC setup (?).

```bash
$ wget -O fastq.zip https://ndownloader.figshare.com/articles/1284521/versions/1
$ unzip fastq.zip
$ mkdir raw-fastq && mv *.fastq.gz raw-fastq && rm fastq.zip
# create illumiprocessor conf as in tutorial
$ conda create --name illumiprocessor illumiprocessor
$ source activate illumiprocessor
$ illumiprocessor \
>     --input raw-fastq/ \
>     --output clean-fastq \
>     --config illumiprocessor.conf \
>     --cores 4
2018-08-23 10:32:28,252 - illumiprocessor - INFO - ==================== Starting illumiprocessor ===================
2018-08-23 10:32:28,253 - illumiprocessor - INFO - Version: 2.0.9
2018-08-23 10:32:28,253 - illumiprocessor - INFO - Argument --config: illumiprocessor.conf
2018-08-23 10:32:28,253 - illumiprocessor - INFO - Argument --cores: 4
2018-08-23 10:32:28,253 - illumiprocessor - INFO - Argument --input: /home/bcf/tmp/illumitest/raw-fastq
2018-08-23 10:32:28,253 - illumiprocessor - INFO - Argument --log_path: None
2018-08-23 10:32:28,253 - illumiprocessor - INFO - Argument --min_len: 40
2018-08-23 10:32:28,254 - illumiprocessor - INFO - Argument --no_merge: False
2018-08-23 10:32:28,254 - illumiprocessor - INFO - Argument --output: /home/bcf/tmp/illumitest/clean-fastq
2018-08-23 10:32:28,254 - illumiprocessor - INFO - Argument --phred: phred33
2018-08-23 10:32:28,254 - illumiprocessor - INFO - Argument --r1_pattern: None
2018-08-23 10:32:28,254 - illumiprocessor - INFO - Argument --r2_pattern: None
2018-08-23 10:32:28,254 - illumiprocessor - INFO - Argument --se: False
2018-08-23 10:32:28,254 - illumiprocessor - INFO - Argument --trimmomatic: /home/bcf/anaconda/envs/illumiprocessor/bin/trimmomatic
2018-08-23 10:32:28,254 - illumiprocessor - INFO - Argument --verbosity: INFO
2018-08-23 10:32:28,651 - illumiprocessor - INFO - Trimming samples with Trimmomatic
Running....
2018-08-23 10:34:50,571 - illumiprocessor - INFO - =================== Completed illumiprocessor ===================
```

**Comment by lostcode-sam** [comment]
I checked the environment. looks like phyluce commands are missing, if that is the reason for it .

$ ls ../../../opt/anaconda2/envs/phyluce/bin
2to3          infotocap         python2.7         sqlite3_analyzer  tset captoinfo     ncursesw6-config  python2.7-config  tabs              wheel lear         openssl           python2-config    tclsh             wish c_rehash      pip               python-config     tclsh8.6          wish8.6 easy_install  pydoc             reset             tic Idle          python            smtpd.py          toe infocmp       python2           sqlite3           tput

$ ls ../../../opt/anaconda2/envs/illumiprocessor/bin/
2to3             infocmp           python2           sqlite3           tput captoinfo        infotocap         python2.7         sqlite3_analyzer  tset clear            ncursesw6-config  python2.7-config  tabs              wheel
c_rehash         openssl           python2-config    tclsh             wish easy_install     pip               python-config     tclsh8.6          wish8.6 idle             pydoc             reset             tic illumiprocessor  python            smtpd.py          toe

**Comment by brantfaircloth** [comment]
The two packages are independent, so you needn't have one to run the other.

**Comment by lostcode-sam** [comment]
Dear Brant,

The issue was resolved. Thanks a lot!
