### ISSUE TITLE
IO Error There are not appropriate files in dir

### ISSUE THREAD

**Issue by camilocalderon** [faircloth-lab/phyluce#122]
Hello all, 
After processing my data with Illumiprocessor (no errors) I can't run either Velvet or Abyss. I get the following error:

IOError("There are not appropriate files in {}".format(dir))
IOError: There are not appropriate files in /Users/cace/UCE_DATA/uce_anoura/clean-fastq/geoffroyi12/split-adapter-quality-trimmed

I attach a view of my folder structure and the assembly config file. 
macOS Sierra, Java 1.7. 

<img width="947" alt="screen shot 2018-08-28 at 11 57 08" src="https://user-images.githubusercontent.com/8772224/44738344-48fd5100-aaba-11e8-8bc0-55422fbb95e6.png">

<img width="939" alt="screen shot 2018-08-28 at 12 03 14" src="https://user-images.githubusercontent.com/8772224/44738375-603c3e80-aaba-11e8-833c-ac6cd7b4595a.png">

My Abyss command: 

phyluce_assembly_assemblo_abyss \
    --config assembly.conf \
    --output /Users/cace/UCE_DATA/uce_anoura/assembly\
    --kmer 35 \
    --subfolder split-adapter-quality-trimmed \
    --cores 4 \
    --clean \
    --log /Users/cace/UCE_DATA/uce_anoura/log \

Thank you for your time and help. 
-Camilo

**Comment by brantfaircloth** [comment]
Try the `phyluce_assembly_assemblo_abyss` command after removing the `--subfolder split-adapter-quality-trimmed` line.  That should do it.

**Comment by camilocalderon** [comment]
That solved the issue.
Thank you!
