### ISSUE TITLE
can't upgrade python from 3.6 to 3.7

### ISSUE THREAD

**Issue by hhuhhu** [faircloth-lab/phyluce#126]
when i rn conda install python=3.7 in debian, it reports
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - python=3.7
  - qtpy -> python[version='>=3.6,<3.7.0a0'] -> readline==6.2
  - qtpy -> python[version='>=3.6,<3.7.0a0'] -> sqlite=3.13
  - qtpy -> python[version='>=3.6,<3.7.0a0'] -> tk==8.5.18
Use "conda info <package>" to see the dependencies for each package.

**Comment by brantfaircloth** [comment]
phyluce requires python 2.7.  please see https://phyluce.readthedocs.io/en/latest/installation.html.

**Comment by hhuhhu** [comment]
hi guys it's not the specific python package, every package has this error, and in windows, it works well

**Comment by brantfaircloth** [comment]
phyluce is not available for windows.

**Comment by hhuhhu** [comment]
but i use python3.6 not py2.7, i only want to update py3.6 to py3.7 to use asnycio package, and does phyluce has any influence for this?

**Comment by brantfaircloth** [comment]
sounds like the problem you are having is due to conda and not phyluce.  might be good to post the problem on the conda github repository.
