### ISSUE TITLE
Matching contigs to barcodes - No SQLite database generated?

### ISSUE THREAD

**Issue by TomSemple** [faircloth-lab/phyluce#128]
Hi Brant and everyone,

I've been using PHYLUCE_ASSEMBLY_MATCH_CONTIGS_TO_BARCODES to fish out COI from my off-target reads, and it works great, but doesn't generate the database file. I get FASTA and LASTZ files for each sample (with lots of data), but no PROBE.MATCHES.SQLITE file like the output from PHYLUCE_ASSEMBLY_MATCH_CONTIGS_TO_PROBES. 
Is it supposed to be doing this?

I was also wondering what the coverage and identity values are for this program, as they don't seem to be input parameters?

Many thanks,
Tom.

**Comment by brantfaircloth** [comment]
Hi Tom,
This program does not create a database (like the similar program does for UCE searches).  So, the files that are output are the correct outputs for the program.

The barcode searching program does not take values for coverage and identity - it's running a default lastz search without specifying either of these parameters (unlike the standard UCE contig search).

**Comment by milag6** [comment]
Hi
I was wondering, what is the syntax for this program?
I couldnt find any documentation for it
I am trying to do a similar thing 
Do I ran it the same way as I run PHYLUCE_ASSEMBLY_MATCH_CONTIGS_TO_PROBES?
Thanks

**Comment by brantfaircloth** [comment]
There is a tutorial is the documentation: http://phyluce.readthedocs.org/
