### ISSUE TITLE
Memory issue when running phyluce_assembly_assemblo_spades

### ISSUE THREAD

**Issue by jphruska** [faircloth-lab/phyluce#130]
Hi Brant--

I've been running into a memory issue when running the phyluce_assembly_assemblo_spades.

For some reason, when phyluce_assembly_assemblo_spades is calling spades.py, it is telling it to run with a memory flag that is set to 2 GB, as opposed to the default, which is a max of 250 GB.  
Here is the output from the spades log where 2 GM of memory is being requested:

Output dir: /lustre/scratch/johruska/Piranga/spades_assemblies/piranga_hepatica_10257_spades
Mode: read error correction and assembling
Debug mode is turned OFF

Dataset parameters:
  Single-cell mode
  Reads:
    Library number: 1, library type: paired-end
      orientation: fr
      left reads: ['/lustre/scratch/johruska/Piranga/Piranga_clean/piranga_hepatica_10257/split-adapter-quality-trimmed/piranga_hepatica_10257-READ1.fastq.gz']
      right reads: ['/lustre/scratch/johruska/Piranga/Piranga_clean/piranga_hepatica_10257/split-adapter-quality-trimmed/piranga_hepatica_10257-READ2.fastq.gz']
      interlaced reads: not specified
      single reads: ['/lustre/scratch/johruska/Piranga/Piranga_clean/piranga_hepatica_10257/split-adapter-quality-trimmed/piranga_hepatica_10257-READ-singleton.fastq.gz']
      merged reads: not specified
Read error correction parameters:
  Iterations: 1
  PHRED offset will be auto-detected
  Corrected reads will be compressed
Assembly parameters:
  k: [21, 33, 55]
  Repeat resolution is enabled
  Mismatch careful mode is turned ON
  MismatchCorrector will be used
  Coverage cutoff is turned ON and threshold is 5.0
Other parameters:
  Dir for temp files: /lustre/scratch/johruska/Piranga/spades_assemblies/piranga_hepatica_10257_spades/tmp
  Threads: 1
  **Memory limit (in Gb): 2**

Unfortunately, this means that my assemblies using this module have failed, and outputting the following error (from the spades log), due to lack of RAM.

**For example**:  

--  0:06:38.257   196M / 616M  ERROR  K-mer Counting           (kmer_data.cpp             : 353)   The reads contain too many k-mers to fit into available memory. You need approx. 11.7103GB of free RAM to assemble your dataset

I could try and dig through the code to see where this issue might be stemming from, but I figured it would be easier to ask you, and perhaps it would beneficial to the community if it turns out to be a legitimate bug. 

Side note: I've managed to get the assemblies to run by using spades.py directly (not providing a memory flag), but I was hoping to fix this issue in phyluce_assembly_assemblo_spades for ease of use and convenience. 

Best
Jack

**Comment by brantfaircloth** [comment]
Howdy,

It's not a bug.  It's set that way so that most assemblies can complete on a laptop.  You can change the memory requested for spades by creating/editing `~/.phyluce.conf`.  Specifically, you can change the parameters for spades to a value equal to the max memory you have.  So, if you have 256 GB, you can add to that file:

```
[spades]
max_memory:256
cov_cutoff:5
```

**Comment by stachyris** [comment]
Hi Dr Faircloth. 
Even though I have modified the phyluce.conf file, SPAdes is picking up only 8GB RAM allocation. 

Here's the conf file content: 
[binaries]
abyss:$CONDA/bin/ABYSS
abyss-pe:$CONDA/bin/abyss-pe
bcftools:$CONDA/bin/bcftools
bedtools:$CONDA/bin/bedtools
bwa:$CONDA/bin/bwa
gblocks:$CONDA/bin/Gblocks
lastz:$CONDA/bin/lastz
mafft:$CONDA/bin/mafft
muscle:$CONDA/bin/muscle
pilon:$CONDA/bin/pilon
raxml-ng:$CONDA/bin/raxml-ng
samtools:$CONDA/bin/samtools
seqtk:$CONDA/bin/seqtk
spades:$CONDA/bin/spades.py
trimal:$CONDA/bin/trimal
velvetg:$CONDA/bin/velvetg
velveth:$CONDA/bin/velveth
snakemake:$CONDA/bin/Snakemake

[workflows]
mapping:$WORKFLOWS/mapping/Snakefile
correction:$WORKFLOWS/contig-correction/Snakefile
phasing:$WORKFLOWS/phasing/Snakefile

#----------------
#    Advanced
#----------------

[headers]
trinity:comp\d+_c\d+_seq\d+|c\d+_g\d+_i\d+|TR\d+\|c\d+_g\d+_i\d+|TRINITY_DN\d+_c\d+_g\d+_i\d+
velvet:node_\d+
abyss:node_\d+
idba:contig-\d+_\d+
spades:NODE_\d+_length_\d+_cov_\d+.\d+

[spades]
max_memory:128
cov_cutoff:5





And here's partial log from spades: 

Assembly parameters:
  k: [21, 33, 55]
  Repeat resolution is enabled
  Mismatch careful mode is turned ON
  MismatchCorrector will be used
  Coverage cutoff is turned ON and threshold is 5.000000
Other parameters:
  Dir for temp files: /mnt/d/Vinay/Sparrow/Rawdata/spades-assemblies/CHIS155acu_spades/tmp
  Threads: 16
  **Memory limit (in Gb): 8**


======= SPAdes pipeline started. Log can be found here: /mnt/d/Vinay/Sparrow/Rawdata/spades-assemblies/CHIS155acu_spades/spades.log

/mnt/d/Vinay/Sparrow/Rawdata/clean-fastq/CHIS155acu/split-adapter-quality-trimmed/CHIS155acu-READ1.fastq.gz: max reads length: 301
/mnt/d/Vinay/Sparrow/Rawdata/clean-fastq/CHIS155acu/split-adapter-quality-trimmed/CHIS155acu-READ2.fastq.gz: max reads length: 301
/mnt/d/Vinay/Sparrow/Rawdata/clean-fastq/CHIS155acu/split-adapter-quality-trimmed/CHIS155acu-READ-singleton.fastq.gz: max reads length: 301

Reads length: 301


===== Before start started.






Any solution.?

**Comment by stachyris** [comment]
It works when flagged with **--memory 128** in script
But not by default.

**Comment by brantfaircloth** [comment]
Yes - the parameter has been removed from the config file and now exists on the command line.  It’s set to 8 GB by default.
