### ISSUE TITLE
phyluce_assembly_get_trinity_coverage

### ISSUE THREAD

**Issue by GideonPisanty** [faircloth-lab/phyluce#133]
Hello

I would like to filter my assemblies to eliminate low-coverage contigs. I have tried using the "phyluce_assembly_get_trinity_coverage" function, but a few things are unclear to me:
1.  Where are the filtered contigs stored? The script doesn't ask to specify a directory.
2. The "subfolder" line - phyluce assemblies do not generate any subfolder beyond the taxon. Do I omit this line?
3. The "trim" line - here I enter the number of minimum reads?

I ran the script, obviously with some errors, and got the following output:

`(phyluce) [pisantyg@biocomp-0-10 ~]$ phyluce_assembly_get_trinity_coverage \
> --assemblies /isilon/ottawa-rdc/users/pisantyg/abyss/combined \
> --assemblo-config /isilon/ottawa-rdc/users/pisantyg/abyss/combined.conf \
>         --cores 12 \
> --log-path /isilon/ottawa-rdc/users/pisantyg/get_trinity_coverage_1 \
>         --clean \
> --bwa-mem \
>         --assembler abyss \
>         --trim 3
Traceback (most recent call last):
  File "/home/AAFC-AAC/pisantyg/miniconda3/envs/phyluce/bin/phyluce_assembly_get_trinity_coverage", line 20, in <module>
    from phyluce import gatk
  File "/home/AAFC-AAC/pisantyg/miniconda3/envs/phyluce/lib/python2.7/site-packages/phyluce/gatk.py", line 19, in <module>
    import numpy
  File "/opt/bio/lib/NumPy/lib/python2.7/site-packages/numpy-1.11.0-py2.7-linux-x86_64.egg/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/opt/bio/lib/NumPy/lib/python2.7/site-packages/numpy-1.11.0-py2.7-linux-x86_64.egg/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/opt/bio/lib/NumPy/lib/python2.7/site-packages/numpy-1.11.0-py2.7-linux-x86_64.egg/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/opt/bio/lib/NumPy/lib/python2.7/site-packages/numpy-1.11.0-py2.7-linux-x86_64.egg/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/opt/bio/lib/NumPy/lib/python2.7/site-packages/numpy-1.11.0-py2.7-linux-x86_64.egg/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: /opt/bio/lib/NumPy/lib/python2.7/site-packages/numpy-1.11.0-py2.7-linux-x86_64.egg/numpy/core/multiarray.so: undefined symbol: PyUnicodeUCS2_AsUTF8String
`

Thank you

**Comment by brantfaircloth** [comment]
Hi Gideon,

to answer:

1. these will he placed in a directory appended with -filtered.

2. the subfolder argument is used if you need it to direct phyluce to your raw reads

3.  the trimming is automated.  this is a boolean option, so it’s either on or off.  I don’t have the code in front of me, but I think it ensures 5x ends and 15x mean

The errors you are seeing seem to do with the numpy installation on your system that’s being imported (this does not seem to be the one you should have with your phyluce conda install).

**Comment by GideonPisanty** [comment]
Thank you very much!

**Comment by GideonPisanty** [comment]
If you could check and let me know the exact level of trimming in this program, I would really appreciate it.

**Comment by KNx5** [comment]
Hi Gideon, just wondering if you ever ended up working on this--if so I'd be interested in talking! I've been thinking of trying to do some kind of dynamic filtering.
btw from the gatk.py script it looks like this is the filtering level: 
```
100 def get_trimmed_coverage_from_output(log, sample, assembly_pth, coverage, assembler):
101 log.info("Screening and filtering contigs for coverage (3x ends, 5x avg.)")
102 if assembler == "trinity" or assembler == "trinity2":
...

**Comment by brantfaircloth** [comment]
This script is getting removed from phyluce. For computing coverage, see https://github.com/faircloth-lab/phyluce-workflows.
