### ISSUE TITLE
 create a partitioned data file

### ISSUE THREAD

**Issue by GideonPisanty** [faircloth-lab/phyluce#135]
Hello

I would like to create a partitioned data file for use in downstream programs (RAxml, MrBayes, PartitionFinder, etc.).  The format should be something like
DNA, gene1 = 1­-500
DNA, gene2 = 501­-1000
etc.

In the PHYLUCE pipeline, this option is enabled by phyluce_align_format_nexus_files_for_mrbayes, but for this you need first to estimate the models using the program CloudForest, which is obsolete.

Is there another script that can prepare such a file for hundreds of UCE loci?
It seems that PHYLUCE concatenates the individual UCE nexus files in some random order, which makes it impossible to generate such a file even manually.

Thank you

**Comment by brantfaircloth** [comment]
the program to make a phylip file for raxml has options to output nexus and also charsets.  this is what you need to use.

**Comment by GideonPisanty** [comment]
Thank you. In another group someone suggested to me https://github.com/nylander/catfasta2phyml  which is just what I needed.

**Comment by MikeWLloyd** [comment]
> Thank you. In another group someone suggested to me https://github.com/nylander/catfasta2phyml which is just what I needed.

Also see: https://github.com/MikeWLloyd/PartitionedGeneTree 
I worked out a full pipeline to do individual locus trees with partitioning.

**Comment by GideonPisanty** [comment]
Thank you!
