### ISSUE TITLE
"harvesting in silico UCEs" 

### ISSUE THREAD

**Issue by KNx5** [faircloth-lab/phyluce#138]
Hi there, 
I have not been able to recover the same number of loci using the same genome versions published in the 2017 Faircloth paper (Identifying conserved genomic elements and designing universal bait sets to enrich them). I have gone through the methods listed in the Phyluce 2018 documentation, and have tried to understand how the methods listed in the 2017 paper would be employed. You mention aligning the bait set to the genomes, and the stringency, but not the alignment program you used (is it possible that this is not the same as you list in the phyluce pipeline?) Do you mind explaining how your phyluce methods vs these other methods might result in more recovered loci? Thank you very much!

**Comment by brantfaircloth** [comment]
im not totally sure what you mean because it’s not entirely clear to which exact tutorial documents you are referring.  

the exact steps used for each bait set in the manuscript are in the dryad archive for each group:  https://datadryad.org/resource/doi:10.5061/dryad.v0k4h

**Comment by KNx5** [comment]
Thanks! I actually hadn't seen that, and just didn't understand why the Phyluce pipeline 'harvesting' methods would result in fewer loci. I will look closely and try these other methods. Thanks!

**Comment by brantfaircloth** [comment]
most likely because the search parameters were slightly different (e.g. defaults versus changing the min. sequence identity).
