### ISSUE TITLE
phyluce_assembly_get_trinity_coverage issue related to gatk

### ISSUE THREAD

**Issue by michael-branstetter** [faircloth-lab/phyluce#141]
When running phyluce_assembly_get_trinity_coverage using the most recent version of phyluce (v1.6.7), the script failed to run successfully on several samples, failing at the "Computing coverage with GATK..." step. In the [].GATK-coverage-out.log file, I found the error pasted below, suggesting a problem with memory allocation to java. In previous versions of phyluce/gatk, I had not encountered this problem and am not sure how to boost the java memory to fix the issue. Do you know how to increase java memory for gatk within the phyluce environment?

**Comment by brantfaircloth** [comment]
Try setting (either in the terminal in which you are working, which will be temporary, or in your .profile or similar file, which will be "permanent":
```
export _JAVA_OPTIONS="-Xms512m -Xmx8g"
```
where you adjust the values after Xms and Xmx to values that fit your system (you can think of these as min and max memory sizes. In this case Java will start by allocating "-Xms512m" or 512 Mb RAM but can scale up to "-Xmx8g" or 8 GB max RAM. This environment variable changes the RAM allocated to JAVA for all JAVA run on your system.

that may work and should be easy. I would try it first.

If not, another solution is to edit line 32 of bin/gatk within your phyluce environment to look like (you can enter the environment and use which gatk to give you the correct path:
```
default_jvm_mem_opts="-Xms512m -Xmx8g"
```

**Comment by brantfaircloth** [comment]
This script is getting removed from phyluce. For computing coverage, see https://github.com/faircloth-lab/phyluce-workflows.
