### ISSUE TITLE
phyluce_align_seqcap_align

### ISSUE THREAD

**Issue by ClayAssis** [faircloth-lab/phyluce#153]
Hi,

I'm trying to do the alignment, but for some reason it's not working. It dropped all UCEs and returns an empty folder. The problem appears with mafft and also muscle. I'm attaching the phyluce_align_seqcap_align log and also from the previous steps if it helps.

Many thanks!

[phyluce_align_seqcap_align.log](https://github.com/faircloth-lab/phyluce/files/3044402/phyluce_align_seqcap_align.log)
[phyluce_assembly_assemblo_velvet.log](https://github.com/faircloth-lab/phyluce/files/3044403/phyluce_assembly_assemblo_velvet.log)
[phyluce_assembly_get_match_counts.log](https://github.com/faircloth-lab/phyluce/files/3044404/phyluce_assembly_get_match_counts.log)
[phyluce_assembly_match_contigs_to_probes.log](https://github.com/faircloth-lab/phyluce/files/3044405/phyluce_assembly_match_contigs_to_probes.log)

**Comment by brantfaircloth** [comment]
What happens when you pass the `--incomplete-matrix` flag?

**Comment by ClayAssis** [comment]
I'm passing. That's the line I'm using:
phyluce_align_seqcap_align --fasta ~/Documents/RAPIDGENOMICS/Ocoronatus/all-taxa-incomplete.fas --output ~/Documents/RAPIDGENOMICS/Ocoronatus/mafft-nexus --taxa 78 --aligner mafft --cores 30 --incomplete-matrix --log-path ~/Documents/RAPIDGENOMICS/Ocoronatus/log

But I tried to indicate "--incomplete-matrix all-taxa-incomplete.incomplete" and did not work "phyluce_align_seqcap_align: error: unrecognized arguments: all-taxa-incomplete.incomplete"

**Comment by ClayAssis** [comment]
Follows all "all-taxa-incomplete" files

**Comment by brantfaircloth** [comment]
Ok.  I don't see a value for that flag in the log file sent for `seqcap_align`.  It's simply a true/false flag, so it will not work if you give it an argument as in the second part of your comment, above.  Perhaps try running this with `--no-trim`.

**Comment by ClayAssis** [comment]
It worked!
Thank you very much!!!

**Comment by brantfaircloth** [comment]
Cool.

**Comment by eduardoschultz** [comment]
Dear Brant,

I've been finding this same error with several different UCE datasets. phyluce_align_seqcap_align drops all loci, unless the no-trim flag is added. Moreover, I tried it with a dataset I have worked before and the same command that worked previously, with the same input fasta, now drops all loci. So I'm wondering if it could be an issue with the newest version of phyluce. I’m using phyluce 1.6.6 installed with conda on Ubuntu 18.04 but a friend is having the same issue on a Mac.

Also, phyluce_align_get_trimal_trimmed_alignments_from_untrimmed does not seem to do anything with the untrimmed loci.

Everything else seem to be working perfectly.

Best,
Eduardo

**Comment by brantfaircloth** [comment]
Can you send me a few (e.g. 10) alignments where this is happening?

**Comment by eduardoschultz** [comment]
Dear Brant, thanks for the reply! 

The command I'm using is: phyluce_align_seqcap_align --fasta multialign-bams-phased-reads/fastas/joined_allele_sequences_all_samples.fasta --output phased-data-mafft-fasta --output-format fasta --taxa 10 --aligner mafft --cores 16 --incomplete-matrix --log-path ../log --ambiguous. 

I'm running it after phasing the UCEs following the phyluce tutorial. Therefore, I'm using joined_allele_sequences_all_samples.fasta as input, and I emailed you some of these files.

I tried changing the output format, the aligner (mafft/muscle) and some values in proportion, threshold, max-divergence, for example, but had no success, unless using the no-trim option.

**Comment by brantfaircloth** [comment]
ok - I found what the problem is...  basically, biopython changed a feature that's making this process die. I have also committed a fix to the main repository... so you can work from that if you need the fix immediately.  It will take me some time to get the fix in package form and uploaded to bioconda.

**Comment by eduardoschultz** [comment]
It works perfectly now! Many thanks!
