### ISSUE TITLE
Updating phyluce through conda to 1.6

### ISSUE THREAD

**Issue by hintzam33** [faircloth-lab/phyluce#162]
I'm hoping you can help me with updating my version of phlyuce to the latest or at least a newer version that has spades. I've tried to use your update to 1.6.6 script, but couldn't figure out how to get it to work - running it didn't do anything. The version created by conda is 1.5 and therefore doesn't have spades despite your website stating it should be version 1.6.2 (installation guide).

I tried manually updating my version by downloading the tar.gz for version 1.6.7, but I broke conda in the process, so I'm trying to avoid making the same mistake twice. Any advice would be much appreciated! Thank you.

**Comment by brantfaircloth** [comment]
Not sure which operating system you are using but bioconda has 1.6.7 for `macos` and `linux`.  To check this, run:

```conda search phyluce```

Those results should look something like:

```
Loading channels: done
# Name                  Version           Build  Channel
phyluce                   1.6.2          py27_0  bioconda
phyluce                   1.6.3          py27_0  bioconda
phyluce                   1.6.3          py27_2  bioconda
phyluce                   1.6.4          py27_0  bioconda
phyluce                   1.6.5          py27_0  bioconda
phyluce                   1.6.6          py27_0  bioconda
phyluce                   1.6.7          py27_0  bioconda
```

To update, you *should* be able to run:

```conda update phyluce```

And conda should do what you need.  If that's problematic, you should be able to create a specific environment for phyluce v1.6.7 by running something like:

```conda create -n phyluce-updated phyluce=1.6.7```

then using `conda activate phyluce-updated` to switch to the new environment.  If you are not seeing any of the above, you'll need to setup whatever your installation is to use `bioconda` to install phyluce.

**Comment by hintzam33** [comment]
I'm using Ubuntu and was finally able to update phyluce with your suggestions. Thank you very much for the quick response!

**Comment by brantfaircloth** [comment]
Cool.
