### ISSUE TITLE
match_contigs_to_probes.py: improve error message when files named incorrectly

### ISSUE THREAD

**Issue by michael-branstetter** [faircloth-lab/phyluce#17]
I received this error message when trying to run match_contigs_to_probes.py:

2014-07-21 17:41:45,587 - match_contigs_to_probes - CRITICAL - Database already exists
2014-07-21 17:41:45,587 - match_contigs_to_probes - CRITICAL - Cannot create database

The problem was that I had one file in the contigs folder that was incorectly labelled. It would be useful for the error message to be more informative about what the mistake is. There was actually no problem with the program creating the database file and accessing it.

**Comment by brantfaircloth** [comment]
michael - do you have any more information for this one?  perhaps a list of contig names that you were trying (e.g. what the problematic name was)?

**Comment by michael-branstetter** [comment]
From our email exchange: I had two files with the same name and when I moved both into the "contigs" folder one was automatically appended with " copy". Renaming the file so that the name was unique and lacked spaces fixed the problem.

**Comment by brantfaircloth** [comment]
Merging into #36 and closing here.
