### ISSUE TITLE
joined_allele_sequences_all_samples.fasta empty?

### ISSUE THREAD

**Issue by ymilesz** [faircloth-lab/phyluce#172]
Hi Brant, I am trying to follow the phasing tutorial, and I realized my joined_allele_sequences_all_samples.fasta file did not seem to work. I didn't notice any errors in the various log files produced from phyluce_snp_bwa_multiple_align either.

When I opened joined_allele_sequences_all_samples.fasta this is what I see:

>_0 |_phased
>_1 |_phased
>_0 |_phased
>_1 |_phased
>_0 |_phased
>_1 |_phased

I know this not terribly helpful, but if you could point me to which file to examine that'd be fantastic.

Thanks,

Miles

**Comment by renatabiancalana** [comment]
Hi Brant, I'm having the same problem as @ymilesz, also didn't have any issues while running phyluce_snp_bwa_multiple_align or phyluce_snp_phase_uces. I'd be grateful if you could help us on this.  

Thank you,

Renata

**Comment by ymilesz** [comment]
Hi Retana were you able to resolve this problem?

**Comment by renatabiancalana** [comment]
No, I wasn't, and you?

**Comment by ymilesz** [comment]
Not yet.

Sent from my iPhone

On Feb 13, 2020, at 3:51 PM, renatabiancalana <notifications@github.com> wrote:

﻿
[External Email]

No, I wasn't, and you?

**Comment by brantfaircloth** [comment]
Hi folks,

Please include output to stdout/stderr and all log files that were produced, which may help to diagnose the issue.

thx,
b

**Comment by ymilesz** [comment]
Hi Brant.

  The log file for phyluce_snp_phase_uces.log completed without errors, but alligator_mississippiensis.samtools-bcftools-out.log had the following errors: 

/apps/phyluce/20191015/bin/bcftools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

Thanks,

Miles

**Comment by brantfaircloth** [comment]
ok - cool, that helps.  you need to reinstall samtools using conda (you may have to force uninstall samtools then reinstall it).

**Comment by renatabiancalana** [comment]
Hi Brant, in my case the log file for phyluce_snp_phase_uces.log completed without errors, but I didn't try with the samples from the tutorial: 
------------------ Merging alleles from all loci-----------------
2020-01-03 09:29:16,957 - phyluce_snp_phase_uces - INFO - Wrote 1 loci for Tac_squ5039
2020-01-03 09:29:16,958 - phyluce_snp_phase_uces - INFO - Wrote 1 loci for Aer_mon22904
2020-01-03 09:29:16,959 - phyluce_snp_phase_uces - INFO - Wrote 1 loci for Aer_sax621130
2020-01-03 09:29:16,960 - phyluce_snp_phase_uces - INFO - Wrote 1 loci for Tac_squ650459
2020-01-03 09:29:16,961 - phyluce_snp_phase_uces - INFO - Wrote 1 loci for Aer_and3590
2020-01-03 09:29:16,962 - phyluce_snp_phase_uces - INFO - Wrote 1 loci for Tac_squ45879
2020-01-03 09:29:16,963 - phyluce_snp_phase_uces - INFO - Wrote 1 loci for Tac_pho27024
2020-01-03 09:29:17,011 - phyluce_snp_phase_uces - INFO - ================ Completed phyluce_snp_phase_uces ===============

Thanks for your help in this topic.

Renata

**Comment by brantfaircloth** [comment]
if it works with the samples from the tutorial, then the problem is generally with the data you are using (which is hard for me to help with).

**Comment by renatabiancalana** [comment]
ok, I'll try with the tutorial data and see if I have any problems; a colleague from my lab said it could also be the name of the files, but so far I didn't have any issues running Phyluce.

**Comment by ymilesz** [comment]
Thanks Brant mine works now, I will leave this open for Renata.
