### ISSUE TITLE
Trouble with phyluce_align_get_informative_sites 

### ISSUE THREAD

**Issue by TomSemple** [faircloth-lab/phyluce#175]
Hi Brant,
When I try to use `phyluce_align_get_informative_sites` I get this error:
```
phyluce_align_get_informative_sites --alignments mafft-nexus-internal-trimmed-gblocks-clean  --cores 4
Vendor:  continuum
Product: anaconda
Message: trial mode expires in 30 days
Traceback (most recent call last):
  File "/Users/thomassemple/anaconda2/bin/phyluce_align_get_informative_sites", line 160, in <module>
    main()
  File "/Users/thomassemple/anaconda2/bin/phyluce_align_get_informative_sites", line 129, in main
    work = [(args, f) for f in get_files(args.input, args.input_format)]
AttributeError: 'Namespace' object has no attribute 'input'
``` 
It's been about 6 months since I used Phyluce, so I'm wondering if everything I'm using is still up to date?
I ran `conda update python` and `conda update phyluce`, both of which did a few things, but still the same error. 

`python -V` returns `Python 2.7.3 :: Anaconda custom (64-bit)`
I'm not sure how to check that the latest version of Phyluce is installed?

Other things work fine, like `phyluce_align_get_align_summary_data`.

On a side note, in the output above, do you know if the `trial mode expires in 30 days` is referring to Anaconda?

Thanks in advance for any suggestions!

**Comment by brantfaircloth** [comment]
Totally bizarre.  First try both:
```
conda update conda
conda update anaconda
```
and see if that fixes (see [this](https://github.com/ContinuumIO/anaconda-issues/issues/6240)).

If that doesn't fix the error, you may need to nuke your conda install and start over using instructions in documentation and installing miniconda.

**Comment by TomSemple** [comment]
It worked! Thanks! Hopefully this is useful for other people who might not have used the program in a while.

I'm not sure if it changed anything, but I did this, as per the Bioconda instructions:
```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
```

Then I did what you suggested, with another update of Python and Phyluce afterwards.

```
conda update conda
conda update anaconda
conda update python
conda update phyluce
```

Then it just worked!
