### ISSUE TITLE
Error while using phyluce_probe_strip_masked_loci_from_set 

### ISSUE THREAD

**Issue by bastianheimburger** [faircloth-lab/phyluce#183]
Dear Mr Faircloth,

I get an error once I'm using `$ phyluce_probe_strip_masked_loci_from_set --bed bed/Ami.merge.bed --twobit genomes/BlattGenome/BlattGenome.2bit --output bed/Ami.strip.bed --filter-mask 0.25 --min-length 80`

`Traceback (most recent call last):
  File "/usr/users/bheimbu/miniconda2/envs/phyluce/bin/phyluce_probe_strip_masked_loci_from_set", line 122, in <module>
    main()
  File "/usr/users/bheimbu/miniconda2/envs/phyluce/bin/phyluce_probe_strip_masked_loci_from_set", line 97, in main
    sequence = tb[str(chromo)][start:end]
  File "/usr/users/bheimbu/miniconda2/envs/phyluce/lib/python2.7/site-packages/bx/seq/twobit.py", line 82, in __getitem__
    seq = self.index[name]
KeyError: 'JPZV01275749.1'
`

Do you have any idea, what's causing the error?

Cheers Bastian

**Comment by brantfaircloth** [comment]
Two things to check: (1) is that contig name in the fasta file exactly as it's reported above?  (2) is there other information in the fasta header for that (and all) contigs?  if you, you may need to remove that other information, and leave just the contig accession number.

**Comment by bastianheimburger** [comment]
Dear Brant,

I've found my mistake: I've used two different versions of the _Blattella germanica_ genome at the beginning. Stupid me.
That's why the "KeyError: 'JPZV01275749.1'", because this contig/scaffold accession number couldn't be found in the given bed file.

Anyway, thanks for your suggestions,

Bastian
