### ISSUE TITLE
match_contigs_to_probes_error

### ISSUE THREAD

**Issue by fuchs-j** [faircloth-lab/phyluce#190]
Dear users, 

i am facing a problem when running match_contigs_to_probes with contigs extracted from genome data. All steps from the Tutorial III: Harvesting UCE Loci From Genomes have been successfully completed. 

The error i get when running  _match_contigs_to_probes_ is:

File "/~/phyluce_assembly_match_contigs_to_probes", line 19, in <module>
from phyluce.helpers import is_dir, is_file, FullPaths, get_contig_header_string
ImportError: cannot import name get_contig_header_string

I ran the following command: 

phyluce_assembly_match_contigs_to_probes \
    --contigs contigs \
    --probes uce-5k-probes.fasta \
    --output uce-search-results

both with and without using symlinks in the contigs folder where the fasta files are located but the error message is always the same. Adding the full paths to the contigs, probes and output did not change anything either
Could the problem be due because the script does not recognize the fasta format (especially header content) from _probe_slice_sequence_from_genomes , that is looking for a typical abyss, trinity or velvet fasta header ?
i went through all issues content but could not find this problem before.
Thanks a lot for your time and help

**Comment by brantfaircloth** [comment]
This sounds like an error you get when phyluce is not installed correctly or you are running the script without activating the conda environment.

**Comment by fuchs-j** [comment]
Weirdly, it seems that some parts were not installed correctly; i started from scratch, including miniconda2 and everything works now. Thanks a lot for replying so quickly
