### ISSUE TITLE
Conda recipe needs requests python package added

### ISSUE THREAD

**Issue by mkweskin** [faircloth-lab/phyluce#197]
The phyluce conda package is great, but I noticed that the python package `requests` is not installed automatically. This package is used by the script `phyluce_assembly_match_contigs_to_barcodes`.

Thanks!

Edit: I should not that one can manually install this to their phyluce conda environment with `conda install -c conda-forge requests`

**Comment by brantfaircloth** [comment]
Fixed in 7d3ba7b
