### ISSUE TITLE
phyluce_assembly_match_contigs_to_probes 

### ISSUE THREAD

**Issue by quattrinia** [faircloth-lab/phyluce#207]
Hi Brant, 
Is there a way to keep all loci that are thrown out as duplicates in the "finding UCE loci step"? I know you can keep a file of the dupes, but curious if you can actually just keep all loci? Or at least the contigs that match multiple loci. 

Cheers,
Andrea

**Comment by brantfaircloth** [comment]
Yes, there's a way... You can output the list of "duplicates" when matching loci, and then run that through https://gist.github.com/brantfaircloth/e48e7e4eb9748854962863d104f94095.  YMMV and be careful with what you do with those duplicates loci!
