### ISSUE TITLE
Cannot connect to the conda channel

### ISSUE THREAD

**Issue by yksun** [faircloth-lab/phyluce#209]
I try to install phyluce from conda. But I keeping this error:

Collecting package metadata (current_repodata.json): failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: faircloth-lab
  channel url: http://conda.binstar.org/faircloth-lab
  error code: 404

Wondering if the URL is still valid.

Thanks,
Yukun

**Comment by brantfaircloth** [comment]
It is not.  Please see the updated installation instructions in the [documentation](https://phyluce.readthedocs.io/en/latest/installation.html#add-the-necessary-bioconda-repositories-to-conda).

**Comment by yksun** [comment]
Thanks for the instant reply. Problem solved.

**Comment by brantfaircloth** [comment]
Excellent 👍
