### ISSUE TITLE
Some phased fasta with names starting with _R_?

### ISSUE THREAD

**Issue by ymilesz** [faircloth-lab/phyluce#213]
Hi Brant,

  While trying to extract SNPs from my phased UCEs, I noticed that some of the phased fasta have _R_ in front of the usual uce-### (ex. _R_uce-12167_YMZ007_Sycophila_occidentalis_1 |_phased), and it isn't restricted to particular genes or samples. Just wondering why and if I need to be concerned about using these particular sequences downstream.

Thanks,

Miles

**Comment by brantfaircloth** [comment]
These have simply been reversed my MAFFT, so not an issue.

**Comment by ymilesz** [comment]
Perfect thank you for the quick reply!
