### ISSUE TITLE
minor comments on the tutorial

### ISSUE THREAD

**Issue by crsl4** [faircloth-lab/phyluce#215]
Hi Brant,

I am covering `phyluce` in my phylogenetics class and I found a couple of minor typos while following the tutorial step by step.
In particular
1. In the [Install phyluce in its own conda environment](https://phyluce.readthedocs.io/en/latest/installation.html#install-phyluce-in-it-s-own-conda-environment), I had to do `conda activate phyluce` instead of `source activate phyluce` (similarly for deactivate). Not sure if this is Mac specific as I am using a Mac
2. In the [Clean the data](https://phyluce.readthedocs.io/en/latest/tutorial-one.html#clean-the-read-data), you have a `cd my-analysis` that should be `cd uce-tutorial` to be consistent with the rest of the steps
3. Finally, I was unable to run `trinity` as they no longer support Mac. So maybe you can add this somewhere in the documentation.
```
NOTE: assemblo_trinity and Trinity are no longer supported on Mac OS.
Trinity has been consistently hard to build on Mac OS and we will no
longer be supporting it (unless it becomes easier to build).  We
suggest you use Trinity on Linux _OR_ ABYSS, itero, or spades on Mac
OS.
```

As I said, these are all minor things, so feel free to close the issue and ignore completely. Also, let me know if you prefer that I add these comments via a pull request.

Thanks for such a well-documented software!

**Comment by brantfaircloth** [comment]
Excellent - thank you!  Changes made!  Next steps (early summer) - finally finish updating everything for python3 and get all the software tests more reliably in-place...
