### ISSUE TITLE
Problem with phyluce_probe_run_multiple_lastzs_sqlite

### ISSUE THREAD

**Issue by lningyawen** [faircloth-lab/phyluce#219]
Hello Dr Faircloth:
I have encountered some problems when i try to run phyluce_probe_run_multiple_lastzs_sqlite.
The program is run correctly at the beginning. The following output also appears when the program is running.
Running against 001dxc.2bit
Running with the --huge option.  Chunking files into 10000000 bp...
Running the targets against 131 queries...
	/tmp/tmpqSVKWc.fasta
	/tmp/tmptxmRt8.fasta
	/tmp/tmpcUNTK1.fasta
	/tmp/tmpq0MIuQ.fasta
	/tmp/tmpbHD7GU.fasta

Writing the results file...
	/tmp/tmpg2t_RT.lastz
	/tmp/tmp0f8VGv.lastz
	/tmp/tmpOgB0wK.lastz
	/tmp/tmpmyPoQX.lastz
	/tmp/tmp2SsNsM.lastz
Cleaning up the chunked files...
Cleaning /gpfs/home/liunyw/cactus/uce-genome/dragon-genome-lastz/uce-5k-probes.fasta_v_001dxc.lastz
Creating 001dxc table

But after a while the program starts to report errors. The error is reported as follows.
Traceback (most recent call last):
  File "/gpfs/home/liunyw/miniconda3/envs/phyluce/bin/phyluce_probe_run_multiple_lastzs_sqlite", line 257, in <module>
    main()
  File "/gpfs/home/liunyw/miniconda3/envs/phyluce/bin/phyluce_probe_run_multiple_lastzs_sqlite", line 250, in main
    align_against_scaffolds(cur, args, path)
  File "/gpfs/home/liunyw/miniconda3/envs/phyluce/bin/phyluce_probe_run_multiple_lastzs_sqlite", line 203, in align_against_scaffolds
    create_species_lastz_tables(cur, g)
  File "/gpfs/home/liunyw/miniconda3/envs/phyluce/bin/phyluce_probe_run_multiple_lastzs_sqlite", line 140, in create_species_lastz_tables
    pdb.set_trace()
  File "/gpfs/home/liunyw/miniconda3/envs/phyluce/lib/python2.7/bdb.py", line 53, in trace_dispatch
    return self.dispatch_return(frame, arg)
  File "/gpfs/home/liunyw/miniconda3/envs/phyluce/lib/python2.7/bdb.py", line 91, in dispatch_return
    if self.quitting: raise BdbQuit
bdb.BdbQuit

What is the problem causing this? And what should I do?
Thank you very much.

**Comment by brantfaircloth** [comment]
Hi,

I looks like this error is resulting because of the sample/genomes names.  They should not start with a number or special symbol - e.g. `001dxc` created a problem because the name stars with a number.  Numbers following letters should work.

-b

**Comment by lningyawen** [comment]
> Hi,
> 
> I looks like this error is resulting because of the sample/genomes names. They should not start with a number or special symbol - e.g. `001dxc` created a problem because the name stars with a number. Numbers following letters should work.
> 
> -b

Hello Dr Faircloth:

Thank you for your prompt reply.
After I changed the name of the genome, the program works fine. It was such a small mistake that it was hard for me to notice. Thank you again for pointing it out.

However, I encountered a different problem.  After I ran the two commands, phyluce_probe_run_multiple_lastzs_sqlite and phyluce_probe_slice_sequence_from_genomes, I got the UCE without getting an error reported. Only a few of these result files have one or two sequences in them, while the others are empty. I'm wondering if this is related to the probe file I'm using, which was downloaded from the one you provided in your tutorial at this link (https://raw.githubusercontent.com/faircloth-lab/uce-probe-sets/master/uce-5k-) probe-set/uce-5k-probes.fasta). 

If this result is indeed related to the probe file, then how should I go about making the probe file for the class group I am interested in.

I hope to hear from you soon.

yawen

**Comment by brantfaircloth** [comment]
You can look in the files of lastz results and see if there were any matches.  The number and type of matches you get is determined by which bait/probe set you use and the organisms to which you are aligning the baits/probes.  There is a tutorial for designing baits/probes for different groups of organisms in [the documentation](https://phyluce.readthedocs.io/en/latest/tutorial-four.html).

**Comment by lningyawen** [comment]
What a simple mistake that was! Thank you for your patience in answering questions.
