### ISSUE TITLE
having issues installing

### ISSUE THREAD

**Issue by michael-steffen** [faircloth-lab/phyluce#22]
As far as I can tell, I am following the installation of phyluce correctly, but it is not producing the executable file. 

This is the coding line I have been getting. Is there something I am doing incorrectly?

Thanks,
Mike 

Last login: Wed Feb 11 22:42:06 on ttys000
Michaels-MacBook-Pro:~ michael-steffen$ conda install phyluce
Fetching package metadata: ....
Error: No packages found in current osx-64 channels matching: phyluce

You can search for this package on Binstar with

    binstar search -t conda phyluce
Michaels-MacBook-Pro:~ michael-steffen$ conda install -c https://conda.binstar.org/faircloth-lab phyluce
Fetching package metadata: ......
Solving package specifications: .
Package plan for installation in environment /Users/michael-steffen/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    samtools-0.1.19            |                2         279 KB
    velvet-1.2.10              |                2         141 KB
    raxml-8.0.19               |                0         662 KB
    picard-1.106               |                0        41.6 MB
    trimmomatic-0.32           |                1         111 KB
    muscle-3.8.31              |                1         144 KB
    gatk-lite-2.3.0            |                0        11.8 MB
    bwa-0.7.7                  |                0         141 KB
    condaflmake-3.8.2          |                1         213 KB
    lastz-1.02.00              |                2         177 KB
    bedtools-2.18.1            |                2         510 KB
    mafft-7.130                |                2         2.3 MB
    abyss-1.3.7                |                4         2.9 MB
    pysam-0.7.7                |           py27_1         755 KB
    distribute-0.6.45          |           py27_1         517 KB
    pyvcf-0.6.4                |           py27_1          43 KB
    numpy-1.7.1                |           py27_2         2.8 MB
    illumiprocessor-2.0.7      |           py27_1          13 KB
    biopython-1.63             |       np17py27_0         1.9 MB
    bx-python-0.7.1            |       np17py27_1         621 KB
    dendropy-3.12.0            |           py27_0         4.2 MB
    phyluce-1.4                |           py27_0          91 KB
    ------------------------------------------------------------
                                           Total:        72.0 MB

The following NEW packages will be INSTALLED:

    abyss:           1.3.7-4         
    bedtools:        2.18.1-2        
    biopython:       1.63-np17py27_0 
    bwa:             0.7.7-0         
    bx-python:       0.7.1-np17py27_1
    condaflmake:     3.8.2-1         
    dendropy:        3.12.0-py27_0   
    distribute:      0.6.45-py27_1   
    gatk-lite:       2.3.0-0         
    illumiprocessor: 2.0.7-py27_1    
    lastz:           1.02.00-2       
    mafft:           7.130-2         
    muscle:          3.8.31-1        
    phyluce:         1.4-py27_0      
    picard:          1.106-0         
    pysam:           0.7.7-py27_1    
    pyvcf:           0.6.4-py27_1    
    raxml:           8.0.19-0        
    samtools:        0.1.19-2        
    trimmomatic:     0.32-1          
    velvet:          1.2.10-2        

The following packages will be DOWNGRADED:

    numpy:           1.9.0-py27_0 --> 1.7.1-py27_2    

Proceed ([y]/n)? y

Fetching packages ...
samtools-0.1.1 100% |################################| Time: 0:00:00 496.03 kB/s
velvet-1.2.10- 100% |################################| Time: 0:00:00 529.62 kB/s
raxml-8.0.19-0 100% |################################| Time: 0:00:00 818.12 kB/s
picard-1.106-0 100% |################################| Time: 0:00:27   1.58 MB/s
trimmomatic-0. 100% |################################| Time: 0:00:00 468.54 kB/s
muscle-3.8.31- 100% |################################| Time: 0:00:00 558.47 kB/s
gatk-lite-2.3. 100% |################################| Time: 0:00:05   2.42 MB/s
bwa-0.7.7-0.ta 100% |################################| Time: 0:00:00 437.56 kB/s
condaflmake-3. 100% |################################| Time: 0:00:00 360.11 kB/s
lastz-1.02.00- 100% |################################| Time: 0:00:00 429.65 kB/s
bedtools-2.18. 100% |################################| Time: 0:00:00   1.01 MB/s
mafft-7.130-2. 100% |################################| Time: 0:00:01   1.40 MB/s
abyss-1.3.7-4. 100% |################################| Time: 0:00:01   2.44 MB/s
pysam-0.7.7-py 100% |################################| Time: 0:00:01 707.44 kB/s
distribute-0.6 100% |################################| Time: 0:00:00 542.86 kB/s
pyvcf-0.6.4-py 100% |################################| Time: 0:00:00 329.73 kB/s
numpy-1.7.1-py 100% |################################| Time: 0:00:01   1.68 MB/s
illumiprocesso 100% |################################| Time: 0:00:00 191.59 kB/s
biopython-1.63 100% |################################| Time: 0:00:01   1.72 MB/s
bx-python-0.7. 100% |################################| Time: 0:00:00   1.19 MB/s
dendropy-3.12. 100% |################################| Time: 0:00:02   1.89 MB/s
phyluce-1.4-py 100% |################################| Time: 0:00:00 482.96 kB/s
Extracting packages ...
[      COMPLETE      ] |##################################################| 100%
Unlinking packages ...
[      COMPLETE      ] |##################################################| 100%
Linking packages ...
[      COMPLETE      ] |##################################################| 100%
Michaels-MacBook-Pro:~ michael-steffen$ conda install phyluce
Fetching package metadata: ....
Error: No packages found in current osx-64 channels matching: phyluce

You can search for this package on Binstar with

    binstar search -t conda phyluce
Michaels-MacBook-Pro:~ michael-steffen$ which phyluce
Michaels-MacBook-Pro:~ michael-steffen$ $ which phyluce
-bash: $: command not found
Michaels-MacBook-Pro:~ michael-steffen$ phyluce
-bash: phyluce: command not found
Michaels-MacBook-Pro:~ michael-steffen$

**Comment by brantfaircloth** [comment]
Hi Michael, not sure what the issue is here.  One thing is that there is not a specific "executable" - there are instructions that show up in a google search for phyluce install, but those are for a test version that I am (very slowly) working on.  The correct installation instructions are here: 

http://phyluce.readthedocs.org/en/latest/

Have a look in anaconda/bin/ for a script from the phyluce package like "match_contigs_to_probes.py" to see if that program is in the directory.  if it is, you should be good to go.

**Comment by malivezey** [comment]
Hi Brant,
Thanks for your reply and update.  I attended a mycology conference at Duke over the weekend and definitely enjoyed telling some of the diehard taxonomists about your work and my attempt to use it with fungi.  One in particular, Brian Looney of UTenn may download next week.  I will give new instruction and updates a try asap.
Martin
