### ISSUE TITLE
phyluce_align_concatenate_alignments not found

### ISSUE THREAD

**Issue by GillianGibb** [faircloth-lab/phyluce#220]
Hi, when using the programme phyluce_align_concatenate_alignments I get the error 'command not found'. Everything else I've trialled in the UCE tutorial 1 seems to be working fine.

**Comment by brantfaircloth** [comment]
the correct program name for now is phyluce_align_format_nexus_files_for_raxml.  there is an update soon on the horizon where the name changes to phyluce_align_concatenate_alignments.  the name change just made it into the documentation a little bit early.

**Comment by GillianGibb** [comment]
Aha! thanks, knew it would be something like this.

**Comment by brantfaircloth** [comment]
This problem should be fixed - I just released the new version of phyluce (1.7.0) and the documentation should reflect use of that version.

**Comment by rbolem** [comment]
the phyluce_align_format_nexus_files_for_raxml not works for phylip in this code 
phyluce_align_concatenate_alignments \
    --alignments mafft-gblocks-70p \
    --output mafft-gblocks-70p-raxml \
    --log-path log --phylip
