### ISSUE TITLE
Problem installing phyluce 1.7.1

### ISSUE THREAD

**Issue by haxacloruro** [faircloth-lab/phyluce#235]
Hi Brant,
previously I had installed phyluce 1.6, and I decided to work with phyluce 1.7.1. I followed the instructions to install Miniconda3 and then phyluce, but I'm having the next issue:

(base) [habromys@mike1 ~]$ conda env create -n phyluce-1.7.1 --file phyluce-1.7.1-py36-Linux-conda.yml
Collecting package metadata (repodata.json): done
Solving environment: done

==> WARNING: A newer version of conda exists. <==
  current version: 4.9.2
  latest version: 4.10.1

Please update conda by running

    $ conda update -n base -c defaults conda

Preparing transaction: done
Verifying transaction: failed

CondaVerificationError: The package for mafft located at /work/habromys/test-env/pkgs/mafft-7.475-h516909a_0
appears to be corrupted. The path 'bin/einsi'
specified in the package manifest cannot be found.

CondaVerificationError: The package for mafft located at /work/habromys/test-env/pkgs/mafft-7.475-h516909a_0
appears to be corrupted. The path 'bin/fftns'
specified in the package manifest cannot be found.

CondaVerificationError: The package for mafft located at /work/habromys/test-env/pkgs/mafft-7.475-h516909a_0
appears to be corrupted. The path 'bin/fftnsi'
specified in the package manifest cannot be found.

CondaVerificationError: The package for mafft located at /work/habromys/test-env/pkgs/mafft-7.475-h516909a_0
appears to be corrupted. The path 'bin/ginsi'
specified in the package manifest cannot be found.

CondaVerificationError: The package for mafft located at /work/habromys/test-env/pkgs/mafft-7.475-h516909a_0
appears to be corrupted. The path 'bin/linsi'
specified in the package manifest cannot be found.

CondaVerificationError: The package for mafft located at /work/habromys/test-env/pkgs/mafft-7.475-h516909a_0
appears to be corrupted. The path 'bin/mafft-distance'
specified in the package manifest cannot be found.

CondaVerificationError: The package for mafft located at /work/habromys/test-env/pkgs/mafft-7.475-h516909a_0
appears to be corrupted. The path 'bin/mafft-einsi'
specified in the package manifest cannot be found.

CondaVerificationError: The package for mafft located at /work/habromys/test-env/pkgs/mafft-7.475-h516909a_0
appears to be corrupted. The path 'bin/mafft-fftns'
specified in the package manifest cannot be found.

CondaVerificationError: The package for mafft located at /work/habromys/test-env/pkgs/mafft-7.475-h516909a_0
appears to be corrupted. The path 'bin/mafft-fftnsi'
specified in the package manifest cannot be found.

CondaVerificationError: The package for mafft located at /work/habromys/test-env/pkgs/mafft-7.475-h516909a_0
appears to be corrupted. The path 'bin/mafft-ginsi'
specified in the package manifest cannot be found.

CondaVerificationError: The package for mafft located at /work/habromys/test-env/pkgs/mafft-7.475-h516909a_0
appears to be corrupted. The path 'bin/mafft-linsi'
specified in the package manifest cannot be found.

CondaVerificationError: The package for mafft located at /work/habromys/test-env/pkgs/mafft-7.475-h516909a_0
appears to be corrupted. The path 'bin/mafft-nwns'
specified in the package manifest cannot be found.

CondaVerificationError: The package for mafft located at /work/habromys/test-env/pkgs/mafft-7.475-h516909a_0
appears to be corrupted. The path 'bin/mafft-nwnsi'
specified in the package manifest cannot be found.

CondaVerificationError: The package for mafft located at /work/habromys/test-env/pkgs/mafft-7.475-h516909a_0
appears to be corrupted. The path 'bin/mafft-profile'
specified in the package manifest cannot be found.

CondaVerificationError: The package for mafft located at /work/habromys/test-env/pkgs/mafft-7.475-h516909a_0
appears to be corrupted. The path 'bin/mafft-qinsi'
specified in the package manifest cannot be found.

CondaVerificationError: The package for mafft located at /work/habromys/test-env/pkgs/mafft-7.475-h516909a_0
appears to be corrupted. The path 'bin/mafft-xinsi'
specified in the package manifest cannot be found.

CondaVerificationError: The package for mafft located at /work/habromys/test-env/pkgs/mafft-7.475-h516909a_0
appears to be corrupted. The path 'bin/nwns'
specified in the package manifest cannot be found.

CondaVerificationError: The package for mafft located at /work/habromys/test-env/pkgs/mafft-7.475-h516909a_0
appears to be corrupted. The path 'bin/nwnsi'
specified in the package manifest cannot be found.

CondaVerificationError: The package for trimmomatic located at /work/habromys/test-env/pkgs/trimmomatic-0.39-1
appears to be corrupted. The path 'bin/trimmomatic'
specified in the package manifest cannot be found.

It seems that I have a couple of corrupted folders, so I wonder if some files from https://raw.githubusercontent.com/faircloth-lab/phyluce/v1.7.1/distrib/phyluce-1.7.1-py36-Linux-conda.yml are incomplete, or if my problem is something else...

Thank you!

**Comment by brantfaircloth** [comment]
hmm. the packages should be complete because I test the distributions before making them available.  these particular packages are from bioconda, as well, so i’m not sure what happened here. perhaps remove the environment you’ve tried to create, perhaps clean the cache of packages (see conda clean command), and try again.

**Comment by haxacloruro** [comment]
Thanks for the quick answer! As you said, that was a problem related with the packages from bioconda (...some missing files). We fix them and now Phyluce is working.
Best!
