### ISSUE TITLE
Logging error phyluce_align_get_only_loci_with_min_taxa

### ISSUE THREAD

**Issue by jbernst** [faircloth-lab/phyluce#245]
Hello,

I am currently running Phyluce 1.7.1 on a computer cluster, and all has been doing smoothly for the most part. I have 125 taxa in my alignment. One of them I added manually, but kept the fasta headers as the same format so that when I created a new `all-taxa-incomplete.fasta` file, it was the same as all other taxa.

Upon the final steps to create the 75% completeness matrix (`phyluce_align_get_only_loci_with_min_taxa`), I got the following error. It still created the output file, and I got the same error when running `phyluce_align_concatenate_alignments.` When I ran tree reconstruction analyses, my results tree looked normal. So is this error something to worry about? Is this part of the phyluce code or is this something more internal to my cluster? 

```
--- Logging error ---
Traceback (most recent call last):
  File "/home/jmb689/miniconda3/envs/phyluce-1.7.1/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2265' in position 125: ordinal not in range(128)
Call stack:
  File "/home/jmb689/miniconda3/envs/phyluce-1.7.1/bin/phyluce_align_get_only_loci_with_min_taxa", line 128, in <module>
    main()
  File "/home/jmb689/miniconda3/envs/phyluce-1.7.1/bin/phyluce_align_get_only_loci_with_min_taxa", line 119, in main
    sum(results), len(results), args.percent, min_count
Message: 'Copied 4850 alignments of 5226 total containing \u2265 0.75 proportion of taxa (n = 93)'
Arguments: ()
```

Thank you!

Best,
Justin

**Comment by brantfaircloth** [comment]
Shouldn’t be a problem.

**Comment by jbernst** [comment]
Okay! I wasn't sure what caused this, but I think it has to do with the Python version (maybe, I am far from an expert on this and have only read a few posts on it). Thank you!
