### ISSUE TITLE
Is it possible to merge assemblies results from Spades and Trinity to get more contigs? (phyluce_assembly_match_contigs_to_probes issue)

### ISSUE THREAD

**Issue by Danisystematic** [faircloth-lab/phyluce#249]
Hello Dr Faircloth,

 We have used the spades assembler as recommended by the phyluce tutorial but also in the past those of  trinity, so we now have two fasta for each sample which contain the same but also different contigs corresponding to the probes.
For example, during the "find uce phase" we got 324 matchs with spades and 290 with trinity. So we tried to merge the two fasta outputs and use it as a brand new input ,  we got around 100 matching contigs. 
Obviously 100 contigs which are not duplicates if that makes sense. And so a lot of similar wasted contigs.

Is there a way to save this hundred contigs by merging the two fasta files in the "phyluce_assembly_match_contigs_to_probes phase" ? 
Maybe, a way to find out which nodes are duplicated to remove one manually?

Thank you in advance for your answer, best regards

**Comment by brantfaircloth** [comment]
You can see which loci are duplicated using the `--keep-duplicates` option along with an output filename in which to store  the duplicates when you run `phyluce_assembly_match_contigs_to_probes `.

**Comment by Danisystematic** [comment]
Nice that works fine ! Thank you!
