### ISSUE TITLE
format_nexus_files_for_mrbayes.py

### ISSUE THREAD

**Issue by tobiashofmann88** [faircloth-lab/phyluce#25]
this script is erroneous, since one of the arguments (--alignment) carries the wrong name:
it needs to be changed in the script to --aligns (see below), as it is referred to as in the rest of the script. Therefore the flag to use when executing the command should also be --aligns instead of --alignment:
 
def get_args():
    """Get arguments from CLI"""
    parser = argparse.ArgumentParser(description="""Generate a Nexus
        file for MrBayes given an raw_input file of Nexus-formatted
        alignments and a file of models associated with loci.""")
    parser.add_argument(
            **"--aligns",**
            required=True,
            type=is_dir,
            action=FullPaths,
            help="""The path to the alignments directory"""
        )

Another issue is that this script is slightly incompatible with the cloudforest command that creates the input alignment nexus files. Cloudforest names the files *.nexus but this script requires them to end in .nex.

Best,
Tobi

**Comment by brantfaircloth** [comment]
Will update to fix - working on some other general fixes.

**Comment by brantfaircloth** [comment]
This is fixed in the working repository for code that will become phyluce 1.5.1.  In the meantime, you can get and run the new code by checking out the working repository (there is not a conda package yet).
