### ISSUE TITLE
Program does not work for me, support is not evident

### ISSUE THREAD

**Issue by malivezey** [faircloth-lab/phyluce#26]
This issue is not closed. It has not really even been responsibly answered. Thank you Tobias for explaining the path issue. Your comments are an exact duplicate of what is in the online instructions but it does not seem to help the program at all. The program still does not work, the documentation is scant, and the support is zero. Brant - thank you for appearing to respond, but closing this issue seems irresponsible to me.  My final comment that I 'got it' was a acknowledgement to Tobias on the issue of Path.  PLease give me a call so I can get this working.

**Comment by brantfaircloth** [comment]
Martin,

Please see my response to issue #24.
