### ISSUE TITLE
How to know which version of phyluce is installed on a computer?

### ISSUE THREAD

**Issue by Ruben9161** [faircloth-lab/phyluce#267]
I started to work on a computer with Phyluce previosly installed.
But I don't know which version is installed.

1. How do I know which version of phyluce is installed on a computer?
2. Is version 1.7.1 the latest one?

Thanks a lot!

**Comment by brantfaircloth** [comment]
Activate the environment (`conda activate phyluce-1.7.1`, then start `python`, then

```
>>> import phyluce
>>> phyluce.__version__
'1.7.1'
```
