### ISSUE TITLE
conda install phyluce

### ISSUE THREAD

**Issue by malivezey** [faircloth-lab/phyluce#27]
Brant, Tobias,
I have tried I think at least 4 installs now on Ubuntu 14.04 LTS; it just does not work.  Please note below that I am trying Anaconda 1.8.0 this time as you can see in my terminal dialog below

ml@Asus:~$ python -V
Python 2.7.5 :: Anaconda 1.8.0 (64-bit)

The command below works just fine.  I now should have the path 3 times at the bottom of my ~.condarc file
ml@Asus:~$ conda config --add channels http://conda.binstar.org/faircloth-lab

Is there something in the documentation that is missing?  This portion of the install instructions worked just fine with more recent Anaconda 2.?

ml@Asus:~$ conda install phyluce
Error: No packages found matching: conda

Why are there no packages found?

Does the $PATH look correct to you?  I believe the only path needed is the first one: /home/ml/anaconda/bin

ml@Asus:~$ $PATH
bash: /home/ml/anaconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games: No such file or directory
ml@Asus:~$ 

I really appreciate your attempts to help so far; it appears that several times you have not read what I have posted and are responding to other things.

Gratefully,
Martin

**Comment by brantfaircloth** [comment]
If the anaconda distribution is in `/home/ml/anaconda/bin`, then that is what needs to be in your $PATH.  So, in ~/.bash_profile (or whichever you modified), you need:

    export PATH=/home/ml/anaconda/bin:$PATH

Then you need to restart your terminal or run:

    source ~/.bash_profile

to read in the change. The other items in your $PATH are (usually) added by the OS.  You want them there.

**Comment by malivezey** [comment]
The anaconda distribution is indeed as you have stated.  I modified the ~./bashrc file.  I will now check ~./bash_profile

In the dialog above, I believe it shows the $PATH to be as necessary

**Comment by malivezey** [comment]
here are the last two lines in my !./bashrc

# added by Anaconda 1.8.0 installer
export PATH="/home/ml/anaconda/bin:$PATH"
(END)

**Comment by malivezey** [comment]
I greatly appreciate both your and Tobias time and I am willing to make a contribution to your research grant if I can get this running in a couple of days. I very strongly believe in the long term value of your approach. I cannot understand why the idea of using UCEs and associated regions has not gained more traction. To me this is something any new student to the field is praying for everyday: low hanging fruit. You have done all the work. It simply needs to be applied now to an area that needs it very much. I believe it can make a big difference to issues of phylogeny in fungi, and please note, when I am successful, I have every intention of giving you both all of the credit you deserve. I am new, particularly to linux, so if it is coming across as dense, just pitch me another bone. I have been hacking for at least two months on this and I don't think I have raised much of a fuss.

**Comment by brantfaircloth** [comment]
I am not sure why it's not working for you - it's very odd.  same for the java issue.  that said, i am having problems on ubuntu 14.04, now, although I did not in the past... so i'll try and debug those soon.

Also, just to be clear and so you are not surprised at a later date, I want to let you know we've been taking this approach with fungi as part of one of my current grants.  That shouldn't preclude you from using the approach - but it is an active area of my work (along with several collaborators).

-b

**Comment by brantfaircloth** [comment]
See note in #31 re: Java - it's installing fine for me after updating apt-get.

**Comment by malivezey** [comment]
I expected that someone was working on this for fungi, but have not spotted any evidence in the mycological community.  I am very pleased you are working on it.  I am hoping this would help a couple of taxonomists I know and one very well published specialist that works at NIH but will go unmentioned in order to avoid an obvious name drop, but he is aware of some of your work and has seen you speak a couple of times.  I am sure you have seen at least one of his papers.  In case there is any doubt, I would very much like to work with you or contribute in anyway I can to your effort.  (I want to join those who work without pay!)  I include in that offer various admin duties that everyone else is too busy or not inclined to do.  I really appreciated knowing.  

I see no problem with my Java installation.  It just that something pretty basic has been overlooked by me.  That is the only reason I am questioning it.

I have also tried various versions of anaconda. Are you recommending 1.8?  Will 2.7 work as well?

Here is part of the reason I was originally enraptured with fungi, now I want to work more broadly than here:
http://mushroomobserver.org/observer/show_user/2584
http://mushroomobserver.org/observer/observations_by_user/2584

I would be glad to sign any confidentiality papers to be a beta test site, send you a CV, etc.
Thanks!

**Comment by malivezey** [comment]
I could send you the SSD if you want to try that.
Martin

**Comment by malivezey** [comment]
I will see how quickly I can get that in the mail.  I have two, but I want to try everything you have suggested before I do.

**Comment by brantfaircloth** [comment]
Hi Martin,

Unfortunately, I will not have time to take a look at an SSD if you send it my way.  Hopefully, you'll be able to get things working by going back through the steps.  It also might be worth trying to find someone local who can help with linux questions and/or look for a local linux users group for some assistance.

-b

**Comment by malivezey** [comment]
That is okay.  It is going to work.  I think it was an incompatibility
between Java and Chrome.  Thanks, later.

**Comment by brantfaircloth** [comment]
Closing for now - seems you got things working.  Also closing #31, since that overlaps with issues above.
