### ISSUE TITLE
Error in "phyluce_assembly_match_contigs_to_probes"

### ISSUE THREAD

**Issue by kq1986** [faircloth-lab/phyluce#272]
Hello!

I'm trying to match my contigs (~1.9G, assembled using Spades) to my UCE probe set using "phyluce_assembly_match_contigs_to_probes", but I get the following error:

Traceback (most recent call last):
  File "/public/home/kq/miniconda3/envs/phyluce/bin/phyluce_assembly_match_contigs_to_probes", line 421, in <module>
    main()
  File "/public/home/kq/miniconda3/envs/phyluce/bin/phyluce_assembly_match_contigs_to_probes", line 345, in main
    raise EnvironmentError("lastz: {}".format(lztstderr))
OSError: lastz: b'FAILURE: in new_position_table(), prev[] array size (7,512,212,992) exceeds allocation limit of 4,294,967,279; consider using lastz_32, or setting max_malloc_index for a special build, or breaking your target sequence into smaller pieces\n'

I guess this is due to the contigs file is too big.   Is there any good suggestion to troubleshoot this? 

Thanks very much!

**Comment by kq1986** [comment]
Hi Brant,

I followed the Tutorial 3 and that have fixed my problem.  Thank you very much for the quick response!!

**Comment by brantfaircloth** [comment]
Cool - glad to hear it!
