### ISSUE TITLE
phyluce_assembly_assemblo_spades no contig.fasta file 

### ISSUE THREAD

**Issue by karlyhiggins** [faircloth-lab/phyluce#273]
Hello,

I am running this command and not getting any contig.fasta files. There is also a warning on each individual when running: WARNING - Did not clean all fastq/fasta files from /Users/dlab/Desktop/Karly/phylucepractice/spades-assemblies/M0D000065M_spades

```
phyluce_assembly_assemblo_spades \
    --conf assembly.conf \
    --output spades-assemblies \
    --cores 12
```

I attached the .log files. Thank you
[phyluce_assembly_assemblo_spades.log](https://github.com/faircloth-lab/phyluce/files/8533379/phyluce_assembly_assemblo_spades.log)
[spades.phyluce.log](https://github.com/faircloth-lab/phyluce/files/8533382/spades.phyluce.log)
!

**Comment by brantfaircloth** [comment]
It may be that spades is running out of RAM - you adjust this using the `--memory` flag to increase beyond 8 GB.  You could also test to ensure spades is working correctly by following the tutorial and using the data linked there (that will at least let you know if your copy of spades is working as expected).

**Comment by karlyhiggins** [comment]
When I try the --memory flag I get an unrecognized argument for phyluce_assembly_assemblo_spades. 

`phyluce_assembly_assemblo_spades \--conf assembly.conf \--output spades-assemblies \--memory 40 \--cores 12
`

**Comment by brantfaircloth** [comment]
are you using the latest version of phyluce (1.7.1) - it includes this flag.  In older versions, you can edit `phyluce.conf` to change the RAM used for spades or you could make your own at `~/.phyluce.conf` that looks like:

```
[spades]
max_memory:<put integer value here for GB Ram available>
cov_cutoff:5
```

**Comment by karlyhiggins** [comment]
The update and memory allocation appears to have fixed the problem. Thank you!

**Comment by brantfaircloth** [comment]
Excellent 👍
