### ISSUE TITLE
Phyluce on Apple M-series Processors

### ISSUE THREAD

**Issue by coliverbrown** [faircloth-lab/phyluce#281]
Hi Brant,
I'm installing phyluce onto a Mac but when I'm trying to create the conda environment, it fails. The error message reads "ResolvePackageNotFound:" and then lists what looks like dependences. I'll post it below. The .yml file downloaded just fine and I can open it up and read it. Any help would be appreciated. Thanks!

Here's the code and terminal output:

`--2022-09-23 16:04:56--  https://raw.githubusercontent.com/faircloth-lab/phyluce/v1.7.1/distrib/phyluce-1.7.1-py36-macOS-conda.yml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3988 (3.9K) [text/plain]
Saving to: 'phyluce-1.7.1-py36-macOS-conda.yml'

phyluce-1.7.1-py36-macOS-conda.yml 100%[===============================================================>]   3.89K  --.-KB/s    in 0s      

2022-09-23 16:04:57 (10.9 MB/s) - 'phyluce-1.7.1-py36-macOS-conda.yml' saved [3988/3988]

(base) fbk-02uq6x9:~ corvus$ conda env create -n phyluce-1.7.1 --file phyluce-1.7.1-py36-macOS-conda.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - gettext==0.19.8.1=h7937167_1005
  - gmp==6.2.1=h2e338ed_0
  - libgcc==4.8.5=1
  - pandas==1.1.5=py36h2be6da3_0
  - libnghttp2==1.43.0=h07e645a_0
  - bzip2==1.0.8=hc929b4f_4
  - openssl==1.1.1j=hbcf498f_0
  - readline==8.0=h0678c8f_2
  - jupyter_core==4.7.1=py36h79c6626_0
  - psutil==5.8.0=py36h20b66c6_1
  - openmpi==4.0.5=h5807002_4
  - raxml-ng==1.0.1=ha44586f_0
  - tk==8.6.10=h0419947_1
  - wget==1.20.1=h33e2efd_0
  - zlib==1.2.11=h7795811_1010
  - bcftools==1.11=he8d9d6d_0
  - brotlipy==0.7.0=py36h20b66c6_1001
  - cryptography==3.4.6=py36h3d45be8_0
  - xz==5.2.5=haf1e3a3_1
  - libffi==3.3=h046ec9c_2
  - coincbc==2.10.5=he509fd4_1
  - trimal==1.4.1=ha1b3eb9_4
  - ca-certificates==2020.12.5=h033912b_0
  - python-lzo==1.12=py36hab4c556_1003
  - lastz==1.0.4=h0b31af3_4
  - make==4.3=h22f3db7_1
  - importlib-metadata==3.7.2=py36h79c6626_0
  - samtools==1.11=h725deca_0
  - pytest==6.2.2=py36h79c6626_0
  - pulp==2.4=py36h79c6626_0
  - numpy==1.19.5=py36h08dc641_1
  - yaml==0.2.5=haf1e3a3_0
  - libopenblas==0.3.12=openmp_h54245bb_1
  - bedtools==2.30.0=h6eb76b4_0
  - chardet==4.0.0=py36h79c6626_1
  - libcxx==11.1.0=habf9029_0
  - perl==5.32.0=hbcb3906_0
  - certifi==2020.12.5=py36h79c6626_1
  - pysocks==1.7.1=py36h79c6626_3
  - gsl==2.6=h71c5fe9_2
  - htslib==1.11=h422799e_2
  - libdeflate==1.7=h35c211d_5
  - seqtk==1.3=h2573ce8_2
  - openjdk==11.0.8=hb0a8c7a_0
  - c-ares==1.17.1=h0d85af4_1
  - libunistring==0.9.10=h1de35cc_0
  - muscle==3.8.1551=h770b8ee_5
  - ncurses==6.2=h2e338ed_4
  - datrie==0.8.2=py36h9de38fb_1
  - lzo==2.10=haf1e3a3_1000
  - sqlite==3.34.0=h17101e1_0
  - traitlets==4.3.3=py36h9f0ad1d_1
  - gblocks==0.91b=1
  - libidn2==2.3.0=h0b31af3_0
  - pyyaml==5.4.1=py36h20b66c6_0
  - rich==9.2.0=py36h79c6626_0
  - llvm-openmp==11.0.1=h7c73e74_0
  - mafft==7.475=h0b31af3_0
  - libedit==3.1.20191231=h0678c8f_2
  - bwa==0.7.17=h2573ce8_7
  - krb5==1.17.2=h60d9502_0
  - libssh2==1.9.0=h52ee1ee_6
  - pluggy==0.13.1=py36h79c6626_4
  - libcurl==7.75.0=h8ef9fac_0
  - wrapt==1.12.1=py36h20b66c6_3
  - libiconv==1.16=haf1e3a3_0
  - abyss==1.5.2=boost1.61_5
  - libev==4.33=haf1e3a3_1
  - python==3.6.13=h7728216_0_cpython
  - pyrsistent==0.17.3=py36h20b66c6_2
  - velvet==1.2.10=1
  - libgfortran5==9.3.0=h6c81a4c_19
  - spades==3.14.1=he641558_1
  - future==0.18.2=py36h79c6626_3
  - docutils==0.16=py36h79c6626_3
  - biopython==1.78=py36hfa26744_2
  - cffi==1.14.5=py36hfaecaff_0
  - bx-python==0.8.9=py36h4fb836f_2
  - phyluce=1.7.1
  - setuptools==49.6.0=py36h79c6626_3
  - libgfortran==5.0.0=9_3_0_h6c81a4c_19
`

**Comment by brantfaircloth** [comment]
Do you happen to be on a M1 or M2 CPU on whatever machine you are using?  My experience with this (I have an M1 laptop and a new M1 desktop) is that the underlying packages needed for installation (from bioconda) have not all been ported appropriately to the M1 CPU (so some/many of them do not exist).

This means I will need to create a new configuration file for M-series CPU macs... but I have not had time to do that yet.  I'm also not sure that all the bioconda packages needed are available for M1 macs yet - which could also an additional delay.

**Comment by brantfaircloth** [comment]
One somewhat non-intuitive way to work around the error is to install the [*intel-64* version of miniconda](https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh) (versus the m1 version), which *should* run the required dependencies under emulation...

**Comment by coliverbrown** [comment]
Hi Brant,
Thanks for the update. Yes, I'm using a new M1 desktop so that explains the issue. I'll try that intel-64 version first but I understand that an update might take a bit.

**Comment by tauanajc** [comment]
Hello there,
I am having the same issue trying to install the latest version of phyluce with Anaconda (instead of miniconda) on my institution's cluster.
Will try a previous version, but wanted to mention it here in case it adds any information.

**Comment by jsalt** [comment]
> One somewhat non-intuitive way to work around the error is to install the [_intel-64_ version of miniconda](https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh) (versus the m1 version), which _should_ run the required dependencies under emulation...

Hi Brant! I'm currently helping the PhD student in our lab install phyluce on her M1 chip mac and we ran into this exact issue, but your workaround solved the problem! We re-installed miniconda3 using the x84-64 version and successfully installed phyluce using the `conda env create -n phyluce-1.7.1 --file phyluce-1.7.1-py36-macOS-conda.yml` command.

Just wanted to share for anyone else having this issue.

**Comment by brantfaircloth** [comment]
Here’s some more info about setting up conda to allow and x86-64 environment alongside the ARM (m1) native environment.

https://towardsdatascience.com/how-to-manage-conda-environments-on-an-apple-silicon-m1-mac-1e29cb3bad12

**Comment by brantfaircloth** [comment]
Ok, I've adjust some things so that I can install an x86 environment on my M1 machine.  The procedure is as follows:

1. Install miniconda for the M-series Apple CPUs
2. Run the following:
```
# the next line must be run at the same time (e.g. do not split it up)
CONDA_SUBDIR=osx-64 conda create -n phyluce-1.7.1-x86 python=3.6
conda activate phyluce-1.7.1-x86
conda config --env --set subdir osx-64
conda env update --name phyluce-1.7.1-x86 --file phyluce-1.7.1-py36-macOS-conda.yml --prune
```
3. You should be good to go

What this does is basically install conda for the M-series CPUs on your machine (so it's "native" by default), but then sets up an x86 environment for phyluce that will run in emulation.  ONLY the `phyluce-1.7.1-x86` conda environment is set to x86 in this example (although you could adjust for other environments, if needed).

Thanks to [Danny Cunningham's post](https://towardsdatascience.com/how-to-manage-conda-environments-on-an-apple-silicon-m1-mac-1e29cb3bad12) for the pointers.

**Comment by coliverbrown** [comment]
Thanks all! I've got phyluce working now

**Comment by henicorhina** [comment]
Hey Brant, This installation worked perfectly for me on an M1 mac, except for one package: 

ResolvePackageNotFound: 
  - nbformat==5.1.2=pyhd8ed1ab_1

**Comment by brantfaircloth** [comment]
Yes, the instructions have you grabbing an older version of the yml file - I need to update them.  Try to pull a new one:
```
wget https://raw.githubusercontent.com/faircloth-lab/phyluce/main/distrib/phyluce-1.7.1-py36-macOS-conda.yml
```
and you should be good to go.

**Comment by henicorhina** [comment]
Thanks! That new .yml worked perfectly

**Comment by brantfaircloth** [comment]
This has now been updated in the [1.7.2 release](https://github.com/faircloth-lab/phyluce/releases/tag/v1.7.2).
