### ISSUE TITLE
Problem installing phyluce using miniconda

### ISSUE THREAD

**Issue by SilAdSe** [faircloth-lab/phyluce#290]
Hello, my name is Silvia. I am attempting to install the phyluce package for linux in my user in a cluster using miniconda and following the instructions given in the phyluce github release page but I am getting the following error:

Solving environment: failed

ResolvePackageNotFound: 
  - nbformat==5.1.2=pyhd8ed1ab_1

It had already installed it a few months ago and successfully used it until today. The last process I run was pphyluce_assembly_assemblo_spades, but I had been getting some errors indicating that I needed to allocate more RAM. I had been doing different trials increasing the --memory flag each time and when I saw it wasn't generating the contigs output I killed it and deleted the outputs to make a new trial allocating more memory. The last I tried was --memory 100, it failed, I killed it and it took it a lot of time to delate the outputs in the spades_assembly folder. After that, the next trial didn't work and it gave me the following error:

Traceback (most recent call last):
  File "/users-d3/sadrian/miniconda3/envs/phyluce-1.7.1/bin/phyluce_assembly_assemblo_spades", line 19, in <module>
    from phyluce.helpers import FullPaths, is_dir, is_file
  File "/users-d3/sadrian/miniconda3/envs/phyluce-1.7.1/lib/python3.6/site-packages/phyluce/__init__.py", line 21, in <module>
    cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT
  File "/users-d3/sadrian/miniconda3/envs/phyluce-1.7.1/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/users-d3/sadrian/miniconda3/envs/phyluce-1.7.1/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 116] Stale file handle: 'git'

I tried a couple of times but it was always the same. I thought maybe some file in the phyluce environment had been corrupted so I decided to try to delete and install it again. But now I am not being able to install the package, have no clue of what is happening and need some support with that. Thank you very much in advance.

**Comment by brantfaircloth** [comment]
Hello,

I am working on an update to fix that issue you are having with reinstalling, but I'm not quite ready to post the update.  In the meantime, you can:
```
wget https://raw.githubusercontent.com/faircloth-lab/phyluce/main/distrib/phyluce-1.7.2-py36-Linux-conda.yml
```
and then install phyluce using that `yml` file versus the one for 1.7.1.  This should fix the first issue.  I am not sure of the cause of the second issue - see if re-installing fixes it, first.

**Comment by brantfaircloth** [comment]
This has now been updated in the [1.7.2 release.](https://github.com/faircloth-lab/phyluce/releases/tag/v1.7.2).

**Comment by SilAdSe** [comment]
Thank you, I successfully installed the new version of phyluce. I managed to run phyluce_assembly_assemblo_spades in another node in the cluster, so it seems to be a cluster problem. Thank you again, have a nice weekend.
