### ISSUE TITLE
phyluce_snp_bwa_multiple_align 

### ISSUE THREAD

**Issue by TiagoBelintani** [faircloth-lab/phyluce#292]
Hello, everything ok?

I'm using version 1.7.1 and 1.7.2 and when I play "phyluce_snp_bwa_multiple_align" I get no response. Some reason?

print page error:

(phyluce-1.7.2) tiagob@uv2000:/guest/triatominae/tiagob/programs/phyluce> phyluce_snp_bwa_multiple_align
If 'phyluce_snp_bwa_multiple_align' is not a typo you can use command-not-found to lookup the package that contains it, like this:

on the contrary:

(phyluce-1.7.2) tiagob@uv2000:/guest/triatominae/tiagob/programs/phyluce> phyluce_probe_get_locus_bed_from_lastz_files
usage: phyluce_probe_get_locus_bed_from_lastz_files [-h] --alignments
                                                    ALIGNMENTS --output OUTPUT
                                                    [--regex REGEX]
                                                    [--verbosity {INFO,WARN,CRITICAL}]
                                                    [--log-path LOG_PATH]

Can you help me?

**Comment by brantfaircloth** [comment]
This has been replaced by a [workflow](https://phyluce.readthedocs.io/en/latest/daily-use/daily-use-4-workflows.html).  You can either use the workflow or use an earlier version of phyluce.
