### ISSUE TITLE
exploding the monolithic fasta by locus?

### ISSUE THREAD

**Issue by lcgraber** [faircloth-lab/phyluce#294]
Hi,

Can I explode the monolithic fasta (phyluce_assembly_explode_get_fastas_file) by locus? It is possible according to the tutorial but it doesn't appear that "--by-locus" is an option for the function. I did try using "--split-char locus" but that gave me a fasta file for every locus for every sample (ex. uce-10_ant_species.unaligned.fasta) instead of a fasta of all samples for one locus. 

Let me know if there is a way to do this. Thanks!

**Comment by brantfaircloth** [comment]
The default behavior is to explode by locus (with the alternate being `--by-taxon`.

**Comment by lcgraber** [comment]
That did it! Thanks so much!

**Comment by brantfaircloth** [comment]
You bet 👍
