### ISSUE TITLE
phyluce failed to find reads during phasing workflow

### ISSUE THREAD

**Issue by andreluizherpeto** [faircloth-lab/phyluce#296]
Dear Dr. Faircloth,

     I'm attempting to phase UCE data using the phyluce [workflow](https://phyluce.readthedocs.io/en/latest/daily-use/daily-use-4-workflows.html#mapping). I performed the mapping step and got the expected output files in my output folder "mapping-results", but during the phasing step I'm getting an error that indicates that phyluce cannot find the reads. I'm running phyluce 1.7.1 on ubuntu using:

     Config file:

     I'm listing below a single sample as an example. Under bam I'm listing the bam file generated by mapping step and under contigs I'm listing the contigs file previously generated by spades (the same one used in the mapping step). I also tried the contigs file generated by the mapping step and stored in the references folder as an alternative.

bams:
   Eurolophosaurus_amathites_MTR11349: /media/digitalstorm/Storage2/andre/andre_uce_jan_2023/phase-tropiduridae/mapping-results/mapped_reads/Eurolophosaurus_amathites_MTR11349.fxm.sorted.md.bam

contigs:
   Eurolophosaurus_amathites_MTR11349: /media/digitalstorm/Storage2/andre/andre_uce_jan_2023/phase-tropiduridae/spades-assemblies/contigs/Eurolophosaurus_amathites_MTR11349.contigs.fasta

     Phyluce code:

(phyluce-1.7.1) digitalstorm@Velox-XXXXX:/media/digitalstorm/Storage2/andre/andre_uce_jan_2023/phase-tropiduridae/mapping-results/mapped_reads$     phyluce_workflow --config /media/digitalstorm/Storage2/andre/andre_uce_jan_2023/phase-tropiduridae/phasing.conf \
>     --output /media/digitalstorm/Storage2/andre/andre_uce_jan_2023/phase-tropiduridae/phasing-results \
>     --workflow mapping \
>     --cores 4

     And this is the error message I'm getting:

Building DAG of jobs...
InputFunctionException in line 48 of /home/digitalstorm/miniconda3/envs/phyluce-1.7.1/phyluce/workflows/mapping/Snakefile:
Error:
  KeyError: 'reads'
Wildcards:
  sample=Eurolophosaurus_amathites_MTR11349
Traceback:
  File "/home/digitalstorm/miniconda3/envs/phyluce-1.7.1/phyluce/workflows/mapping/Snakefile", line 25, in get_fq1

     I'm not sure about what could be the issue here, given that all paths in my config file are ok. The only potentially odd thing that I was able to identify is that the bam file created inside the mapped_reads folder during the mapping step has a lock sign on top of the icon. I checked that bam file using samtools and noticed that it is not corrupted. I was able to convert it to sam and back to bam, read it in multiple programs, and even eliminate the lock sign using the command chmod, but the error message persists.

     Maybe I'm missing something very silly here. So, any advice would be greatly appreciated.
     I thank you in advance. Andre Carvalho.

**Comment by brantfaircloth** [comment]
Hi Andre,

Change the `—workflow` to `phasing` - it looks like there is a typo in the documentation.

-b

**Comment by brantfaircloth** [comment]
this one’s on me!  i’ll get that typo fixed shortly 👍

**Comment by kylewilliamgray** [comment]
> this one’s on me! i’ll get that typo fixed shortly 👍

I just wanted to let you know that the the workflow mapping typo is still present in the tutorials. When using workflow phasing it works. 

Thanks!
Kyle

**Comment by brantfaircloth** [comment]
Had to make some other changes to get read-the-docs working again.  Should be fixed and updated (in online version of docs) in 6aa5533.
