### ISSUE TITLE
phyluce not installing on macOS aarch64

### ISSUE THREAD

**Issue by macrinl** [faircloth-lab/phyluce#297]
Hello,

I am trying to run phyluce using UTM virtual machine on a MacBook Pro with M1 chip. Given the M1 chip of my machine, I need to run linux-aarch64 version, hence Miniconda3-latest-Linux-aarch64.sh . Everything is working fine until the installation of phyluce. When I prompt the code in the terminal everything runs, but at the end of the installation it gives me an error saying "solving environment: fails ResolvePackageNotFound: " and mentions a series of packages including phyluce 1.7.2
Is this because phyluce is not available for machines running aarch64 yet, or do you think there is any way to overcome this issue?

Many thanks

**Comment by brantfaircloth** [comment]
Have you tried the [instructions for installing on an M-series CPU](https://github.com/faircloth-lab/phyluce/releases)?

**Comment by macrinl** [comment]
Hello. yes, I have, trying to install phyluce from the terminal on Mac M1 now, but I am getting the same error. I run the suggested piece of code: conda env update --name phyluce-1.7.2-x86 --file phyluce-1.7.2-py36-macOS-conda.yml --prune
and I get the following response:
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - seqtk=1.3
  - phyluce=1.7.2
  - python=3.6.15
  - bwa=0.7.17
  - spades=3.14.1
  - bedtools=2.30.0
  - abyss=1.5.2
  - lastz=1.0.4
  - openjdk=11.0.8
  - bx-python=0.8.9
  - raxml-ng=1.0.1
  - libgcc=4.8.5
  - samtools=1.11
  - gblocks=0.91b
  - bcftools=1.11
  - muscle=3.8.1551
  - htslib=1.11
  - trimal=1.4.1
  - rich=9.2.0
  - velvet=1.2.10
  - mafft=7.475
  - python-lzo=1.12

**Comment by macrinl** [comment]
Fixed, it was not running a piece of code. 
Thank you very much for your help!

**Comment by brantfaircloth** [comment]
Cool - thanks for letting me know 👍

**Comment by Anoplogaster** [comment]
Would you be able to explain what code was not running Macrinl? I am trying to install phyluce on my M2 Mac and I'm running into the same error when running the conda env update --name phyluce-1.7.3-x86 --file phyluce-1.7.3-py36-macOS-conda.yml --prune , I get the same error of Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - bedtools=2.30.0
  - htslib=1.11
  - bcftools=1.11
  - mafft=7.475
  - samtools=1.11
  - python-lzo=1.12
  - python=3.6.15
  - openjdk=11.0.8
  - gblocks=0.91b
  - lastz=1.0.4
  - spades=3.14.1
  - libgcc=4.8.5
  - abyss=1.5.2
  - raxml-ng=1.0.1
  - muscle=3.8.1551
  - velvet=1.2.10
  - bwa=0.7.17
  - phyluce=1.7.3
  - seqtk=1.3
  - bx-python=0.8.9
  - rich=9.2.0
  - trimal=1.4.1

Cheers
