### ISSUE TITLE
Java

### ISSUE THREAD

**Issue by malivezey** [faircloth-lab/phyluce#31]
I installed Java per instructions;  your reservations with certain platforms are noted.  Is it possible that Java did not install correctly on a ASUS laptop about 4 years old? 
Intel® Core™ i7-2630QM CPU @ 2.00GHz × 8 
Intel® Sandybridge Mobile 
64-bit
239.8 GB

**Comment by brantfaircloth** [comment]
on Ubuntu 14.04 LTS, running:

    sudo apt-get update
    sudo apt-get install openjdk-7-jre

solved the problem with installing java for me.  it's also listed as a required dependency, but only used for a subset of programs in the package, so not essential to getting most things running.

**Comment by brantfaircloth** [comment]
Closing based on discussion in #27.
