### ISSUE TITLE
Phyluce spaces assembly error?

### ISSUE THREAD

**Issue by louisfnastasi** [faircloth-lab/phyluce#314]
I have a feeling this will be an easy solve but I'm having an issue with parsing the config file for assembly with spades. The error I receive (see bottom of post) implies that the samples section can't be located, yet it is certainly there and I've verified that there are no hidden characters, etc. that could impact parsing. Any advice on solving this?

My script for assembly:
source activate phyluce-1.7.2
cd /storage/group/hmh19/default/UCEs_working/
phyluce_assembly_assemblo_spades \
    --conf assembly-conf1.conf \
    --output spades-assemblies \
    --cores 32

My config file titled assembly-conf1.conf (in the proper directory):
[samples]
Aylax_minor_CYNHG0061:/storage/group/hmh19/default/UCEs_working/PSUC-team-clean-fastq/Aylax_minor_CYNHG0061/split-adapter-quality-trimmed
Synophromorpha_rubi_CKDPSUC65:/storage/group/hmh19/default/UCEs_working/PSUC-team-clean-fastq/Synophromorpha_rubi_CKDPSUC65/split-adapter-quality-trimmed

Error output from our cluster:
[38;21m2023-09-09 14:24:41,849 - phyluce_assembly_assemblo_spades - INFO - =========== Starting phyluce_assembly_assemblo_spades ===========[0m
[38;21m2023-09-09 14:24:41,849 - phyluce_assembly_assemblo_spades - INFO - Version: 1.7.2[0m
[38;21m2023-09-09 14:24:41,849 - phyluce_assembly_assemblo_spades - INFO - Commit: None[0m
[38;21m2023-09-09 14:24:41,849 - phyluce_assembly_assemblo_spades - INFO - Argument --config: /storage/group/hmh19/default/UCEs_working/assembly-conf1[0m
[38;21m2023-09-09 14:24:41,849 - phyluce_assembly_assemblo_spades - INFO - Argument --cores: 32[0m
[38;21m2023-09-09 14:24:41,850 - phyluce_assembly_assemblo_spades - INFO - Argument --dir: None[0m
[38;21m2023-09-09 14:24:41,850 - phyluce_assembly_assemblo_spades - INFO - Argument --log_path: None[0m
[38;21m2023-09-09 14:24:41,850 - phyluce_assembly_assemblo_spades - INFO - Argument --memory: 8[0m
[38;21m2023-09-09 14:24:41,850 - phyluce_assembly_assemblo_spades - INFO - Argument --no_clean: False[0m
[38;21m2023-09-09 14:24:41,850 - phyluce_assembly_assemblo_spades - INFO - Argument --output: /storage/group/hmh19/default/UCEs_working/spades-assemblies[0m
[38;21m2023-09-09 14:24:41,850 - phyluce_assembly_assemblo_spades - INFO - Argument --subfolder: [0m
[38;21m2023-09-09 14:24:41,850 - phyluce_assembly_assemblo_spades - INFO - Argument --verbosity: INFO[0m
[38;21m2023-09-09 14:24:41,850 - phyluce_assembly_assemblo_spades - INFO - Getting input filenames and creating output directories[0m
Traceback (most recent call last):
  File "/storage/home/lfn5093/.conda/envs/phyluce-1.7.2/lib/python3.6/configparser.py", line 846, in items
    d.update(self._sections[section])
KeyError: 'samples'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/storage/home/lfn5093/.conda/envs/phyluce-1.7.2/bin/phyluce_assembly_assemblo_spades", line 231, in <module>
    main()
  File "/storage/home/lfn5093/.conda/envs/phyluce-1.7.2/bin/phyluce_assembly_assemblo_spades", line 184, in main
    input_data = get_input_data(args.config, args.dir)
  File "/storage/home/lfn5093/.conda/envs/phyluce-1.7.2/lib/python3.6/site-packages/phyluce/raw_reads.py", line 165, in get_input_data
    groups = conf.items("samples")
  File "/storage/home/lfn5093/.conda/envs/phyluce-1.7.2/lib/python3.6/configparser.py", line 849, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'samples'

Thanks in advance for any help!

**Comment by brantfaircloth** [comment]
This still looks like some sort of issue with paths.  Can you run this interactively (e.g. rather than using a script) so you can make sure things are operating as you expect?  It could also be some weirdness in the structure of the config file - potentially a line ending problem, although it's very hard to say.

**Comment by louisfnastasi** [comment]
Interesting - I ran the exact same commands manually in the terminal and it worked and provided a typical output (although a couple failed but nothing unusual otherwise). Any ideas as to why?

**Comment by brantfaircloth** [comment]
Honestly not sure - maybe the script is not doing something correctly?
