### ISSUE TITLE
Issues Installing Phyluce on M2 MacOS

### ISSUE THREAD

**Issue by Anoplogaster** [faircloth-lab/phyluce#317]
Hello,

I am running into the same error when installing phyluce at different locations (both at /user and various /applications /documents) using the installing with MacOS - M-Series CPU instructions. 

At the command conda env update --name phyluce-1.7.3-x86 --file phyluce-1.7.3-py36-macOS-conda.yml --prune, I always run into the error below:

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - bedtools=2.30.0
  - htslib=1.11
  - bcftools=1.11
  - mafft=7.475
  - samtools=1.11
  - python-lzo=1.12
  - python=3.6.15
  - openjdk=11.0.8
  - gblocks=0.91b
  - lastz=1.0.4
  - spades=3.14.1
  - libgcc=4.8.5
  - abyss=1.5.2
  - raxml-ng=1.0.1
  - muscle=3.8.1551
  - velvet=1.2.10
  - bwa=0.7.17
  - phyluce=1.7.3
  - seqtk=1.3
  - bx-python=0.8.9
  - rich=9.2.0
  - trimal=1.4.1

I have installed and reinstalled python 3.6 and messed with some other things but still manage to get this same error. Not sure if this is a M2 issue or something else. Any help is greatly appreciated!

Thanks

**Comment by Anoplogaster** [comment]
A simple yet frustrating error that caused this was due to this line: 

# the next line must be run at the same time (e.g. do not split it up) - this sets up an x86 environment
CONDA_SUBDIR=osx-64 conda create -n phyluce-1.7.2-x86 python=3.6
conda activate phyluce-1.7.2-x86
conda config --env --set subdir osx-64

I was trying to run all three lines in one go, which led to the errors I've been seeing on some other MacOS with M chips, but if you run each line individually:

CONDA_SUBDIR=osx-64 conda create -n phyluce-1.7.2-x86 python=3.6

conda activate phyluce-1.7.2-x86

conda config --env --set subdir osx-64

It runs and installs all dependencies without any issues.

**Comment by brantfaircloth** [comment]
This is meant to imply you should run the first line all at once versus splitting it into separate components (e.g. do not run `CONDA_SUBDIR=osx-64` followed by `conda create -n phyluce-1.7.2-x86 python=3.6`)
