### ISSUE TITLE
concatenate with character sets in Phyluce 1.7.1 

### ISSUE THREAD

**Issue by JennaMcCullough** [faircloth-lab/phyluce#319]
I'm running v. 1.7.1 and trying to get a concatenated phylip alignment with character sets. The script to concatenate alignments in the newer version, Phyluce_align_concatenate_alignments, does not have a character sets flag. I used to be able to use phyluce_align_format_nexus_files_for_raxml which did have a flag to produce a character sets flag (--charsets). Is there a reason why it was removed in the newer version, or am I just not seeing the script that would produce this output in addition to a concatenated alignment? 

Thanks in advance

Jenna

**Comment by JennaMcCullough** [comment]
Well, I realize now that the character sets are just default. Whoops.

**Comment by brantfaircloth** [comment]
🤣 no worries

**Comment by JennaMcCullough** [comment]
🤦‍♀️
