### ISSUE TITLE
conda install phyluce

### ISSUE THREAD

**Issue by malivezey** [faircloth-lab/phyluce#32]
ml@Asus:~$ conda install phyluce
Fetching package metadata: ....
Error: No packages found in current linux-64 channels matching: phyluce

You can search for this package on Binstar with

    binstar search -t conda phyluce

Why won't this command work?

**Comment by brantfaircloth** [comment]
did you run:

conda config --add channels https://conda.binstar.org/faircloth-lab

**Comment by malivezey** [comment]
Yes I did, thank you!  I have created a full bash script so you can see my setup.  I understood you to say that I could use the latest version of conda, but it returned this error:
ml@Asus:~$ conda install phyluce
Fetching package metadata: ......
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint: 
[1/3                 ]|#############                           |  33%

Hint: the following packages conflict with each other:
  - phyluce
  - python 3.4*

**Comment by brantfaircloth** [comment]
you need to use the latest version of conda **for Python 2.7**, not Python 3.4.

**Comment by malivezey** [comment]
Will setup for that now with modified script
Thanks
