### ISSUE TITLE
pyluce-master.zip

### ISSUE THREAD

**Issue by malivezey** [faircloth-lab/phyluce#33]
I don't find any instructions on how to install phyluce-master.zip.  Once extracted, It appears that all of the supplied .py files should be placed in the /home/anaconda/bin/ directory, but there is nothing to support this.  I don't find instructions to put the default folder on the path.  As a result, the programs are not found.

Also - the phyluce config file uses and environmental variable $CONDA which I don't see defined anywhere.  Should I add this line to the .bashrc file?

**Comment by brantfaircloth** [comment]
On 8 May 2015, at 13:01, Martin Livezey wrote:

> I don't find any instructions on how to install phyluce-master.zip.  
> Once extracted, It appears that all of the supplied .py files should 
> be placed in the /home/anaconda/bin/ directory, but there is nothing 
> to support this.  I don't find instructions to put the default folder 
> on the path.  As a result, the programs are not found.
>
> Also - the phyluce config file uses and environmental variable $CONDA 
> which I don't see defined anywhere.  Should I add this line to the 
> .bashrc file?

please install using conda.

**Comment by malivezey** [comment]
I have installed using conda.  It must be very frustrating on that end.  Something is not connecting
Here is the startup script I have run; everything here seems to work fine.

#Startup script for install of phyluce on Ubuntu 14.04 LTS and Python 2.7
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install openjdk-7-jre
bash /Downloads/Anaconda-2.2.0-Linux-x86_64.sh
conda config --add channels https://conda.binstar.org/faircloth-lab
conda install phyluce
pwd
python -V
$PATH

**Comment by malivezey** [comment]
Since the default $PATH has not appeared to work, I modified it as follows in .bashrc

fi


# added by Anaconda 2.2.0 installer
export PATH="/home/ml/anaconda/bin:$PATH"
export PATH="/home/ml/anaconda/jar:/home/ml/anaconda/bin:/home/ml/phyluce-maste$
export CONDA_DEFAULT_ENV="/home/ml/anaconda:$CONDA_DEFAULT_ENV"
export PYTHONPATH="/home/ml/phyluce-master/bin/assembly:$PYTHONPATH"
export CONDA="/home/ml/phyluce-master/bin/assembly:/home/ml/anaconda/bin:$CONDA"

(END)

I am getting a 'permission denied' when trying to run:

match_contigs_to_probes.py --contigs contigs/ --probes uce-2.5k-probes.fasta --output mapped_uce/ --log-path log

**Comment by malivezey** [comment]
.condarc checks out just fine:

Channels:
  - http://conda.binstar.org/faircloth-lab


channels:
  - https://conda.binstar.org/faircloth-lab
  - defaults

**Comment by malivezey** [comment]
Python version is as requested:
ml@Asus:/home/ml# python -V
Python 2.7.9 :: Anaconda 2.2.0 (64-bit)

**Comment by brantfaircloth** [comment]
remove all of your entries for PATH from .bashrc or .bash_profile or 
whichever you are using.  put just this one:

export PATH="/home/ml/anaconda/bin:$PATH"

remove the entries for PYTHONPATH and CONDA.  then log out.  then log 
back in.  then run

echo $PATH

you should see "/home/ml/anaconda/bin" as the first entry, followed by 
many others.  then run

conda install phyluce

**Comment by malivezey** [comment]
ml@Asus:~$ echo $PATH
/home/ml/anaconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
ml@Asus:~$ conda install phyluce
Fetching package metadata: ......
Solving package specifications: .................
# All requested packages already installed.
# packages in environment at /home/ml/anaconda:
#
phyluce                   1.5.0                    py27_0  
ml@Asus:~$ match_contigs_to_probes.py --contigs contigs/ --probes uce-2.5k-probes.fasta --output mapped_uce/ --log-path log
bash: /home/ml/anaconda/bin/match_contigs_to_probes.py: Permission denied
ml@Asus:~$

**Comment by malivezey** [comment]
This is the same as I have been seeing since the install of correct version of Anaconda 2.x, EXCEPT that I copied all files in all folders from the extracted master-phyluce.zip to /home/ml/anaconda/bin.

Prior to doing that copy, the command 'match_contigs_to_probes.py' could not be found.  If you are at a loss, I do have an opportunity to meet with a user group run by David Kristensen who is published and presenting a new scheme for deriving phylogeny of Bacteriophages based on categorizing genes.  He was interested in your project.  

What about 'conda create', is something missing in the documentation on that?

**Comment by malivezey** [comment]
I think we have probably done enough for the day, certainly understand if you are.  I present Thursday.  I will be trying to pull something together before then.  I would really like to set the class back, but I understand your schedule.  It would be great to get this rolling.

**Comment by brantfaircloth** [comment]
run without the .py at the end.  this is in the current documentation.

**Comment by malivezey** [comment]
ml@Asus:~$ match_contigs_to_probes.py --contigs contigs/ --probes uce-2.5k-probes.fasta --output mapped_uce/ --log-path log
bash: /home/ml/anaconda/bin/match_contigs_to_probes.py: Permission denied

ml@Asus:~$ ml@Asus:~$ ml@Asus:~$ match_contigs_to_probes --contigs contigs/ --probes uce-2.5k-probes.fasta --output mapped_uce/ --log-path log
ml@Asus:~$: command not found

With or without the .py I am striking out.  Tobias indicated .py in his documentation.

**Comment by brantfaircloth** [comment]
Tobias' documentation is old.  the documentation on the website is current.  you may have overwritten the correct files in the anaconda/bin directory when you copied the contents of the phyluce-master.zip.  this would possibly give you the wrong permissions.  you can navigate to anaconda/bin and run:

chmod -R 0755 *

that should fix permissions.  you should be able to run things without the .py.

-b

**Comment by malivezey** [comment]
ml@Asus:~$ chmod -R 0755 *
ml@Asus:~$ match_contigs_to_probes --contigs contigs/ --probes uce-2.5k-probes.fasta --output mapped_uce/ --log-path log/
match_contigs_to_probes: command not found

chmod seemed to take; I ran it in my home directory and in /anaconda/bin.  I rebooted.  Ran everything again.  Not using .py  Still no dice.

We had earlier had the /home/ml/anaconda/jar in the $PATH; is it no longer needed?

I have not done the tutorials.  Should I look into putting this on a mac?

**Comment by malivezey** [comment]
match_contigs_to_probes will not even run in /anaconda/bin where I it plainly resides.  I am turning the computer off.

**Comment by brantfaircloth** [comment]
Closing this out.

**Comment by malivezey** [comment]
Okay.  I am still interested in helping you with the site, your research,
or just plain feeding my own curiousity.  I completed my course with a
simple bioinformatics exercise using the Plasmodium falciparum genome.  How
about this: I will *send you a blank SSD* if you or an assistant can use
phyluce to create a working copy - you send the SSD in a *pre-paid envelop
back to me*.  I am pretty sure you want to be sure we are not back in
dependency or permissions hell, right?

Thanks again for your help and this opportunity.
Martin Livezey
