### ISSUE TITLE
phyluce_snp_phase_uces yielding empty output files

### ISSUE THREAD

**Issue by cLweinrich** [faircloth-lab/phyluce#330]
Hello,

I have been trying to work through Phasing UCE Data from Tutorial II using my own dataset. I am using phyluce 1.7.3.

When I try to run the actual phasing step ("phyluce_snp_phase_uces"), the command runs and produces a number of output files and logs without error. However, the final output file ("joined_allele_sequences_all_samples.fasta") is empty.

Based on what I can gather from the various output files/logs, it appears that "phyluce_snp_phase_uces" performs a number of steps. After calling "samtools sort", it looks like the sorted .bam files should then be converted to FASTQ files for the remaining steps. However, the FASTQ files are essentially empty (they contain a single empty record consisting of just "@" and "+" on subsequent lines). The "samtools-phase-out.log" seems to indicate that phasing worked, and the sorted .bam's seem to be a reasonable size which leads me to believe it's specifically the .bam > .fq conversion which is not working, but I may be wrong.

I'm wondering if I'm missing something, or if there's a possible solution/workaround to my problem. I'm happy to provide any files that may be useful.

Best,
Christian

**Comment by brantfaircloth** [comment]
Hi Christian,

The older phasing workflow has been phased out, so to speak.  Phasing is now accomplished (hopefully more robustly) using the `phyluce_workflow` command, which is not well documented.  The first step is mapping, which takes a configuration file that looks like the one here:

https://github.com/faircloth-lab/phyluce/blob/main/phyluce/tests/test-conf/mapping.config.yaml

And is run like:
```
phyluce_workflow --config <config file> --output <folder name> --workflow mapping --cores <# cores>
```

And the second stage is the "phasing" command, which takes a config file that looks like:

https://github.com/faircloth-lab/phyluce/blob/main/phyluce/tests/test-conf/phasing.config.yaml

And is run like:
```
phyluce_workflow --config <config file> --output <folder name> --workflow phasing --cores <# cores>
```

**Comment by cLweinrich** [comment]
Thanks for the quick response. I will give that a go.
