### ISSUE TITLE
phyluce_assembly_match_contigs_to_probes - AttributeError: 'NoneType' object has no attribute 'groups'-NEW Issues

### ISSUE THREAD

**Issue by jjinzhou** [faircloth-lab/phyluce#337]
Dear Professor Faircloth,

I'm having a problem running this command"phyluce_assembly_match_contigs_to_probes", which seems to be the same problem as #233 and #321. I modified the `~/.phyluce.conf` in conda environment according to your answers to these two questions, i.e

> [headers]
trinity:comp\d+_c\d+_seq\d+|c\d+_g\d+_i\d+|TR\d+\|c\d+_g\d+_i\d+|TRINITY_DN\d+_c\d+_g\d+_i\d+
velvet:node_\d+
abyss:node_\d+
idba:contig-\d+_\d+
spades:NODE_\d+_length_\d+_cov_\d+.\d+
minia3:scaffold_\d+_uid_\d+

 I made this change because the assembly software was selected Minia3 and the file starts with `scaffold_41_uid_1710815508`.But the results still show the same error.
 I then tried the `--regex scaffold_\d+_uid_\d+` parameter, but the results were still wrong.

I don't know what went wrong and I was hoping for your guidance.
Here is the code I used, and the specific error

> phyluce_assembly_match_contigs_to_probes \
    --contigs assemblies_endding \
    --probes hymenoptera-v2-PRINCIPAL-bait-set.fasta \
    --output uce_extraction \
    --min-coverage 67 \
    --min-identity 80

`File "~/miniconda3/envs/phyluce-1.7.3/bin/phyluce_assembly_match_contigs_to_probes", line 421, in <module>
    main() \n File "~/miniconda3/envs/phyluce-1.7.3/bin/phyluce_assembly_match_contigs_to_probes", line 354, in main 
    contig_name = get_contig_name(lz.name1)
  File "~/miniconda3/envs/phyluce-1.7.3/bin/phyluce_assembly_match_contigs_to_probes", line 279, in get_contig_name
    return match.groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'`

**Comment by brantfaircloth** [comment]
The header string you are using looks incorrect.  It should be something like:
```
minia3:scaffold_\d+_uid_\d+
```
to match a header name like:
```
scaffold_41_uid_1710815508
```
The `--regex` command won't work - that's meant for something else.

**Comment by jjinzhou** [comment]
Thank you so much for your quick reply! 
But sorry, I think it was a formatting error caused by pasting. That's exactly the format I'm using. But the mistake still occurs
<img width="683" alt="截屏2024-04-23 10 50 38" src="https://github.com/faircloth-lab/phyluce/assets/155713830/a71dba68-94c3-4bc6-9c94-566c786ee7fe">

Lzhensectabl:phyLuce_assembLy_match_contigs_to_probes
-contigs assemblies_endding\
-probes hymenoptera-v2-PRINCIPAL-bait-set. fasta\
--output uce_extraction \
-min-coverage 67 \
--min-identity80
2024-04-23 10:33:46,824 - phyluce_assembly_match_contigs_to_probes - INFO
======= Starting phyluce_assembly_match_contigs_to_probes
2024-04-23 10:33:46,824 - phyluce_assembly_match_contigs_to_probes - INFO
- Version: 1.7.3
2024-04-23 10:33:46,824 - phyluce_assembly_match_contigs_to_probes - INFO
- Commit: None
2024-04-23 10:33:46,824 - phyluce_assembly_match_contigs_to_probes
- INFO
- Argument --contigs:~/assemblies_endding
2024-04-23 10:33:46,824 - phyluce_assembly_match_contigs_to_probes - INFO - Argument --cv: None
2024-04-23 10:33:46. 824
- phyluce_assembly_match_contigs_to_probes
- INFO
- Argument
--dupefile: None
2024-04-23 10:33:46.824
- phyluce_assembly_match_contigs_to_probes
- INFO
- Argument
--keep_duplicates: None
2024-04-23 10:33:46,824
- phyluce_assembly_match_contigs_to_probes
- TNEO
- Argument
--log_path: None
2024-04-23 10:33:46.824
- phyluce_assembly_match_contigs_to_probes
- INFO
- Argument
--min_coverage: 67
2024-04-23 10:33:46.824
- phyluce_assembly_match_contigs_to_probes
- INFO
Argument --min_identity: 80
2024-04-23 10:33:46. 824
- phyluce_assembly_match_contigs_to_probes
- INFO
- Argument -output: ~/phylogenomic_latest/uce_plw/uce_extraction
2024-04-23 10:33:46. 825
- phyluce_assembly_match_contigs_to_probes
- INFO
Argument -probes: ~/phylogenomic_latest/uce_plw/hymenoptera-v2-PRINCI
PAL-bait-set. fasta
2024-04-23 10:33:46.825 - phvluce_assembly match_contigs to probes - INFO
- Argument --regex: A(uce-\d+) (?: p\d+.*)
2024-04-23 10:33:46,825 - phyluce_assembly_match_contigs_to_probes - INFO
- Argument --verbositv: INFO
2024-04-23 10:33:47,421 - phyluce_assembly_match_contigs_to_probes - INFO
- Creating the UCE-match database
2024-04-23 10:33:47,461 - phyluce_assembly_match_contigs_to_probes - INFO
- Processina contia data
2024-04-23 10:33:47,462 - phyluce_assembly_match_contigs_to_probes
- INFO
Traceback (most recent call last):
File "~/miniconda3/envs/phyluce-1.7.3/bin/phyluce_assembly_match_contigs_to_probes", line 421, in «modules
main
File "~/miniconda3/envs/phyluce-1.7.3/bin/phyluce_assembly_match_contigs_to_probes", line 354, in main
contig_name = get_contig_name(lz.namel)
File "~/miniconda3/envs/phyluce-1.7.3/bin/phyluce_assembly_match_contigs_to_probes", line 279, in get_contig_name
return match.groups0[0]
AttributeError:
'NoneType'
object has no attribute
'groups'

**Comment by brantfaircloth** [comment]
I'm not sure - Minia is not a supported assembler, so what you are trying to do is non-standard.  If I had to guess, it would be that some scaffolds/contigs in the output have a different header format than the one you think they have. But I don't use Minia, so I'm not sure what the header format looks like for all scaffolds/contigs.

**Comment by jjinzhou** [comment]
Thank you very much for your help. I have re-checked the header format of each sample, and it is indeed the same format. But I didn't have a lot of samples so I decided to reassemble them with spades to avoid this problem.
Wish you have a good day!
