### ISSUE TITLE
illumiprocessor - unequal split-adapter-quality-trimmed read1 and read2

### ISSUE THREAD

**Issue by jackson-roberts** [faircloth-lab/phyluce#339]
Hey Brant,

I finally updated from phyluce 1.6 -> 1.7 and (in my memory) have never experienced this issue. illumiprocessor+trimmomatic appear to be running correctly, but the final READ1.fastq.gz and READ2.fastq.gz have unequal reads, thus Spades is throwing the OS value 255 error. 

Am I just missing something simple? Shouldn't the READ1 + READ2 files from illumiprocessor in the split-adapter-quality-trimmed directory always be equal, with all orphaned reads in the singleton file?

Thanks, and hope you are well.

Jackson

**Comment by brantfaircloth** [comment]
Hi Jackson,

Yes, these should always be equal.  I'm not sure how that could have happened.  Are the input files equal in terms of read pairs?

-b

**Comment by jackson-roberts** [comment]
Hey Brant!

thanks for the response and apologies for the delay. I pulled an my old system running phyluce 1.6, ran the identical spades call with the same data, and all ran well until it (as expected) ran out of RAM. I feel really really silly. Spades currently is not compatible with Mac M2 ARM OS’, which I was running when this error persisted. So everything is running as it should, it is just time to update to a large Linux based system. 

Thanks again for your time. 

Jackson
