### ISSUE TITLE
phyluce_align_remove_locus_name_from_files does not clean names if output is fasta

### ISSUE THREAD

**Issue by tauanajc** [faircloth-lab/phyluce#341]
Hi there!

I aligned my UCEs without any trimming and saved as fasta. When using the command to clean the names, it only worked with the default nexus. When I used `--output-format fasta`, the name was duplicated with one version clean followed by the original separated by a space, like so: `Diodora_cayenensis_FMNH281526_gLIB_0098 uce-2172_Diodora_cayenensis_FMNH281526_gLIB_0098 | uce-2172`.

**Comment by brantfaircloth** [comment]
That's weird.  But, I've fixed the bug in the code that was causing the problem.  That fix won't make it into a release for a while, but it's pretty simple if you want to implement on your own.  I'm about to reference the issue in a commit and the fix should pop up below.
