### ISSUE TITLE
phyluce_align_get_gblocks_trimmed_alignments_from_untrimmed not functioning

### ISSUE THREAD

**Issue by sbabbbie** [faircloth-lab/phyluce#352]
I'm having an issue that I cannot resolve. It's the same issue someone had back in 2018, but the suggested fixes aren't working for me:

https://github.com/faircloth-lab/phyluce/issues/129

Basically, phyluce_align_get_gblocks_trimmed_alignments_from_untrimmed doesn't work and I can't figure out why. The loading bar for trimming seems to be working fine, then suddenly I get the error:

"FileNotFoundError: [Errno 2] No such file or directory: '/Users/sbabbbie/Documents/UCE/backbone_tree_test/seed+mysequences_aligned_fragmentscollapsed_endstrimmed_stage2/uce-2175.fasta-gb'". 

It doesn't seem to be making any fasta.gb files for any alignments as far as I can see, and I'm left with an empty output directory. Editing the phyluce.conf file as someone suggested on the linked thread didn't make a difference. I'm on an Apple M2 chip if that matters, but I installed following the instructions for the M series chips. Gblocks and Phyluce are both updated. Any advice?

**Comment by brantfaircloth** [comment]
Hi Spenser,

Gblocks does not work on *any* M-series chips, as far as I know.  The source code is also not open, so we cannot recompile for an M-series.  Your best best is trimal in place of Gblocks.  Or run the Gblocks step on Linux (eg on the cluster).

-b

**Comment by sbabbbie** [comment]
That was so fast!! Thanks, Brant!
