### ISSUE TITLE
Phyluce_probe_run_multiple_lastzs_sqlite creating empty lastz files, but no discernable errors.

### ISSUE THREAD

**Issue by teaganme** [faircloth-lab/phyluce#353]
Hello! I'm trying to get a monolithic file for a probe set I'm developing, which is merged between two other probe files. The odd thing is this step worked perfectly for both "parent" probesets, but my "child" probeset is having this issue. I've added my output, which I ran with set -x to help with debugging. Any ideas welcome! 

[phyluce_probe_run_multiple_lastzs_sqlite_log.log](https://github.com/user-attachments/files/17601839/phyluce_probe_run_multiple_lastzs_sqlite_log.log)

And a screenshot of the directory structure, with empty lastz files, just in case it's helpful. 

<img width="575" alt="Screenshot 2024-11-01 093055" src="https://github.com/user-attachments/assets/755eba1a-3e47-47ae-9cf9-dcc4a3ebc606">

**Comment by brantfaircloth** [comment]
can you explain a little more about what you're trying to do and exactly what you did that did not work correctly?  my guess is problem lies in the naming of probes/baits in the probe/bait file you created.

**Comment by teaganme** [comment]
I'm following tutorial IV, starting at the In-silico test of the bait design. Would my probe file having different headers affect it? My merged probe/bait file has your style of headers (>uce-3883_p1 |design:diptera-v1,designer:faircloth,probes-locus:uce-3883,probes-probe:1,probes-source:lutlon1,probes-global-chromo:JH689388.1,probes-global-start:68886,probes-global-end:69006,probes-local-start:0,probes-local-end:120) and my style (>uce-1194_p4 |uce-1194_ruf). I wasn't considering the headers, since they both worked independently, but would the fact both are in the same file be an issue?

**Comment by brantfaircloth** [comment]
Merging the two could cause problems if the is overlap in the bait/locus names (e.g. you have uce-1000 in both sets of files).  I'm not entirely sure that is your issue though - it sort of looks like lastz is not running correctly.... really hard to tell from afar.  I might try a smaller set of alignments, first (e.g. against just 1 genome, maybe with a reduced probe set) to ensure that all is working, and then scale up to more genomes/more baits.

**Comment by teaganme** [comment]
Hello! I have good news! It ended up being the nucleotides in the probe file were all lowercase! I believe the utility I used for merging probe sets made them lowercase for some reason. Thank you for your quick response, and for the thoroughness of the tutorials you have available!

**Comment by brantfaircloth** [comment]
Gotcha - glad it worked out 👍
