### ISSUE TITLE
phyluce_assembly_match_contigs_to_probes probes do not match

### ISSUE THREAD

**Issue by JETitus** [faircloth-lab/phyluce#50]
Hi Dr. Faircloth,

I am having an issue with phyluce_assembly_match_contigs_to_probes script. As a run down. I did a test run on a few samples of my data and phyluce performed magnificently. Gave me the 3000ish exons I was targeting and phylogenetic analysis proved that the exons were exactly what they were supposed to be. Excellent!

However, that was with 8 samples. I am not using my whole dataset 52 samples (those 8 samples came from this dataset). No errors occur. Everything runs brilliantly, but when I use phyluce_assembly_get_match_counts not a single probe is matched. The log is below. 

[phyluce_assembly_match_contigs_to_probes_slim.txt](https://github.com/faircloth-lab/phyluce/files/146981/phyluce_assembly_match_contigs_to_probes_slim.txt)

I edited the regex command to '([A-Z])\w+_exon\d+' to grab my probe naming scheme. Fasta below.
[targetsFilt.fasta.txt](https://github.com/faircloth-lab/phyluce/files/146984/targetsFilt.fasta.txt)

Here is the log from my test dataset.
[Het_Phyluce_probe_extraction_results.txt](https://github.com/faircloth-lab/phyluce/files/146987/Het_Phyluce_probe_extraction_results.txt)

That worked perfectly. Nothing has changed between these runs except I added the rest of my dataset for a total of 52 samples instead of 8 (again those 8 sample are in this dataset) and cleaned data in split-adapter-quality-trimmed directory is not gunzipped like the test data, which shouldn't matter for Trinity.

Here is the Trinity log for the test set that worked.
[phyluce_assembly_assemblo_trinity.log.txt](https://github.com/faircloth-lab/phyluce/files/146994/phyluce_assembly_assemblo_trinity.log.txt)

Here is the Trinity log for the whole dataset that is not able to match the probes.
[phyluce_assembly_assemblo_trinity.log.txt](https://github.com/faircloth-lab/phyluce/files/146996/phyluce_assembly_assemblo_trinity.log.txt)

I am hoping I made a typo somewhere or my regex is off. I really have not answers why the same data worked in one run, but not in the other.

Thank you for you time. I really appreciate it.

Cheers,
James

**Comment by brantfaircloth** [comment]
Seems a lot like the regular expression is off.  The `CCM0121` sample that worked in the set of 8 returns no data for the larger set of all samples.  That doesn't make sense (the total number of contigs assembled for `CCM0121` is also different from the `CCM0121_SM6_NE` sample which is also suspect).

I cannot see the regex you used for the initial test of 8 samples (it's trimmed out), but my guess is that the one you are using for the second test is incorrect.  The regular expression `([A-Z])\w+_exon\d+` only grabs `E` from `ENSACAP`, when what I think you want to be doing is something more like `(\w+)_exon\d+`, which would grab the entire `ENSACAP0000000bzw1` as the locus name.

There are also a lot of duplicates being identified in your test run of 8 samples which workes, and this may also be problematic... so once you fix the first problem, you'll need to take a look at the second possible problem.

-b

**Comment by mateusf** [comment]
Hi James,

you can check if your regex is working properly here: https://regex101.com/

hope this help you somehow.

Best

2016-02-25 13:21 GMT-04:00 JETitus <notifications@github.com>:

> Hi Dr. Faircloth,
>
> I am having an issue with phyluce_assembly_match_contigs_to_probes script.
> As a run down. I did a test run on a few samples of my data and phyluce
> performed magnificently. Gave me the 3000ish exons I was targeting and
> phylogdentic analysis proved that the exons were exactly what they were
> supposed to be. Excellent!
>
> However, that was with 8 samples. I am not using my whole dataset 52
> samples (those 8 samples came from this dataset). No errors occur.
> Everything runs brilliantly, but when I use
> phyluce_assembly_get_match_counts not a single probe is matched. The log is
> below.
>
> phyluce_assembly_match_contigs_to_probes_slim.txt
> <https://github.com/faircloth-lab/phyluce/files/146981/phyluce_assembly_match_contigs_to_probes_slim.txt>
>
> I edited the regex command to '([A-Z])\w+_exon\d+' to grab my probe naming
> scheme. Fasta below.
> targetsFilt.fasta.txt
> <https://github.com/faircloth-lab/phyluce/files/146984/targetsFilt.fasta.txt>
>
> Here is the log from my test dataset.
> Het_Phyluce_probe_extraction_results.txt
> <https://github.com/faircloth-lab/phyluce/files/146987/Het_Phyluce_probe_extraction_results.txt>
>
> That worked perfectly. Nothing has changed between these runs except I
> added the rest of my dataset for a total of 52 samples instead of 8 (again
> those 8 sample are in this dataset) and cleaned data in
> split-adapter-quality-trimmed directory is not gunzipped like the test
> data, which shouldn't matter for Trinity.
>
> Here is the Trinity log for the test set that worked.
> phyluce_assembly_assemblo_trinity.log.txt
> <https://github.com/faircloth-lab/phyluce/files/146994/phyluce_assembly_assemblo_trinity.log.txt>
>
> Here is the Trinity log for the whole dataset that is not able to match
> the probes.
> phyluce_assembly_assemblo_trinity.log.txt
> <https://github.com/faircloth-lab/phyluce/files/146996/phyluce_assembly_assemblo_trinity.log.txt>
>
> I am hoping I made a typo somewhere or my regex is off. I really have not
> answers why the same data worked in one run, but not in the other.
>
> Thank you for you time. I really appreciate it.
>
> Cheers,
> James
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/faircloth-lab/phyluce/issues/50>.
>



-- 
Mateus Ferreira
Biólogo (CRBIO 73940/06-D)
Doutorando em Genética - GCBEV/INPA
Cel: (92)98147-1505

**Comment by JETitus** [comment]
Hi All,

Thank you for very quick replies. I am quite appreciative of it.

Thanks for the update with the regex. I was using regexr.com to check my regular expressions, and it was saying everything was matching just fine, which it was, but need to grab the proper group (which I was not).

Consider this issue closed.

Thank you again.

Cheers,
James

**Comment by nadjenajar** [comment]
Hello,

I have a similar issue but I don't understand why my regular expression isn't working (from inexperience). I've got a custom probe set:
[Exonbaits.txt](https://github.com/faircloth-lab/phyluce/files/1799874/Exonbaits.txt)
with names like:
1:16956259-16956388:+_0
Un:56207074-56207348:+_104
5-random:1014495-1014634:-_20
Z:54117359-54117488:-_0

I used this expression (\w+|5-random):(\d+-\d+):(._\d+), and the program ran but almost nothing matched any contigs.
[rowr_align_output_log.txt](https://github.com/faircloth-lab/phyluce/files/1799878/rowr_align_output_log.txt)

I'm trying a different expression now on just two individuals (\w+|5-random):(\d{6,9}-\d{6,9}):[+-]_(\d{1,3})

I get this error afterwards:
 File "/home/mmcglaughlin/miniconda2/envs/phyluceenv/bin/phyluce_assembly_match_contigs_to_probes", line 237, in new_get_probe_name return match.groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'

I'm pretty sure my issue is a basic one but I can't seem to get this to work on my own.

Thanks for reading - Nadje
