### ISSUE TITLE
New link to download tutorial data from figshare

### ISSUE THREAD

**Issue by mkweskin** [faircloth-lab/phyluce#52]
This is about your readthedocs tutorial. It looks like figshare has changed their URLs for downloads. The working new link to download the sample data via wget is: https://ndownloader.figshare.com/articles/1284521/versions/1

**Comment by mkweskin** [comment]
Actually the new wget command should be: `wget -O fastq.zip https://ndownloader.figshare.com/articles/1284521/versions/1` otherwise it downloads the file as "1".

**Comment by brantfaircloth** [comment]
Fixed in 05cd3d0.  Thank you!
