### ISSUE TITLE
How to update phyluce?

### ISSUE THREAD

**Issue by TiagoSousaNeves** [faircloth-lab/phyluce#54]
Hi, what is the best way to update phyluce 1.5 to 2.0?

**Comment by brantfaircloth** [comment]
1.5 is the "official" version of phyluce you should be using.  2.0 is a test version, and should not be used at this point.

**Comment by TiagoSousaNeves** [comment]
Ok!
Thank you Brant!

**Comment by brantfaircloth** [comment]
The best way to update, now, is to use bioconda as described in http://phyluce.readthedocs.io/en/latest/installation.html.
