### ISSUE TITLE
OSerror

### ISSUE THREAD

**Issue by bettycatherine** [faircloth-lab/phyluce#59]
Hi,
I followed exactly every step in the intall manual and tried to install phyluce on three computers, but I always get this message:

wuhong@WH-Ubuntu:~$ phyluce_probe_run_multiple_lastzs_sqlite
Traceback (most recent call last):
  File "/home/wuhong/BioSoftWare/anaconda2/bin/phyluce_probe_run_multiple_lastzs_sqlite", line 23, in <module>
    from phyluce.helpers import is_dir, is_file, FullPaths
  File "/home/wuhong/BioSoftWare/anaconda2/lib/python2.7/site-packages/phyluce/**init**.py", line 16, in <module>
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/home/wuhong/BioSoftWare/anaconda2/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/home/wuhong/BioSoftWare/anaconda2/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

The phyluce was installed sucessfully:

wuhong@WH-Ubuntu:~$ conda update phyluce
Fetching package metadata .........
Solving package specifications: ..........
# All requested packages already installed.
# packages in environment at /home/wuhong/BioSoftWare/anaconda2:
# 

phyluce                   1.5.0                    py27_0    https://conda.binstar.org/faircloth-lab

So can any one tell me what is wrong?

I installed both miniconda and anaconda, neither worked, and now the conda version is conda 4.2.7.

**Comment by brantfaircloth** [comment]
On 25 Sep 2016, at 22:16, bettycatherine wrote:

> Hi,
> I followed exactly every step in the intall manual and tried to 
> install phyluce on three computers, but I always get this message:

you need to install git.  that should fix the error.

-b

**Comment by bettycatherine** [comment]
Thank you, it works for me.
However, I have encountered another problem:
phyluce_probe_slice_sequence_from_genomes --lastz try-lastz --conf genome-config --flank 200 --name-pattern "mccormacketal-2560-probes.fasta_v_{}.lastz.clean" --output py
No matter what name I give to the output directory, it keeps telling me that output directory already exist (of course it does't).
If I choose to overwrite it, the program proceeded wierd:
Output directory exists.  Overwrite [Y/n]? Y
2016-09-27 13:57:31,612 - Phyluce - INFO - =================== Starting Phyluce: Slice Sequence ===================
And it just stopped, and nothing came out.
I tried on two machines and came out the same results.
I cannot figure out which part is wrong.

**Comment by brantfaircloth** [comment]
I am not sure.  Are you able to make the tutorial (http://phyluce.readthedocs.io/en/latest/tutorial-three.html) work?  If I had to guess, I would say it's a problem with the files in either `try-lastz` or the name pattern you are using.

**Comment by bettycatherine** [comment]
I tried the steps in the tutorial and it doesn't work either.
The messges were the same with my own data:
(my_root)[yul@login2 uce-genome]$phyluce_probe_slice_sequence_from_genomes --lastz tutorial3-genome-lastz --conf genomes.conf --flank 500 --name-pattern "uce-5k-probes.fasta_v_{}.lastz.clean" --output tutorial-genome-fasta
[WARNING] Output directory exists, REMOVE [Y/n]? Y
Output directory exists.  Overwrite [Y/n]? Y
2016-09-28 10:24:27,361 - Phyluce - INFO - =================== Starting Phyluce: Slice Sequence ===================

And this is the content of the directory:
allMis2
  allMis2.2bit
galGal4
  galGal4.2bit
genomes.conf
tutorial3-genome-lastz
  uce-5k-probes.fasta_v_allMis2.lastz.clean
  uce-5k-probes.fasta_v_galGal4.lastz.clean
tutorial3.sqlite
tutorial-genome-fasta
uce-5k-probes.fasta

**Comment by brantfaircloth** [comment]
Can you send the contents of `genomes.conf`?

**Comment by bettycatherine** [comment]
No problem.
This is the one I used for tutorial data:
[scaffolds] galGal4:/home/yul/workdir/huyiwen/zz/UCE/uce-genome/galGal4/galGal4.2bit allMis2:/home/yul/workdir/huyiwen/zz/UCE/uce-genome/allMis2/allMis2.2bit
And this is the one I used for my own data:
[scaffolds] aciJub:/home/yul/workdir/huyiwen/zz/UCE/2bit/aciJub.2bit

**Comment by brantfaircloth** [comment]
are you working on a cluster, by any chance or on a local machine?  also,
do these paths to each 2bit file exist?  finally, what operating system and
os version are you using?

thanks,
b

**Comment by bettycatherine** [comment]
I tried both on a cluster and a local machine, I validate that these files exist.
The operating system of the local machine is Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-95-generic x86_64).

**Comment by davidcerny** [comment]
I can confirm that the same problem also occurs on CentOS Linux 7.3.1611 and macOS Sierra 10.12.3, even when I follow all the steps in the tutorial.

**Comment by brantfaircloth** [comment]
Hi david,

I'm assuming the problem you are referring to is the notice that `Output directory exists.  Overwrite [Y/n]? Y`?  On CentOS 6.5, and OS X 10.10.5, I receive this notice, but the program runs after typing `Y`, as requested.

The improper notice appears to be fixed in later versions of the code (not currently available on anaconda).  If you would like to use those later versions, you should be able to check the code out from github: 

```
git clone https://github.com/faircloth-lab/phyluce.git`
```
then run each script using:
```
python /path/where/you/put/github/repo/phyluce/bin/probes/phyluce_probe_run_multiple_lastzs_sqlite \
    --db tutorial3.sqlite \
    --output tutorial3-genome-lastz \
    --scaffoldlist galGal4 allMis2 \
    --genome-base-path ./ \
    --probefile uce-5k-probes.fasta \
    --cores 12
```
I also updated the formatting in the documentation a little bit to clear up some issues: http://phyluce.readthedocs.io/en/latest/tutorial-three.html#finding-uce-loci

**Comment by davidcerny** [comment]
Hi Dr. Faircloth,

Many thanks for your quick reply! I'm sorry I wasn't clearer; the issue I meant was indeed the output directory notice, followed by the wrapper getting stuck at `=================== Starting Phyluce: Slice Sequence ===================`. The source of the problem turned out to be the fact that the paths in `genomes.conf` were not separated by line breaks. I think the past version of the tutorial might have had a formatting problem in this part, which led both me and Betty Catherine to think that the paths were to be separated by spaces rather than line breaks. Many thanks for updating it!

**Comment by brantfaircloth** [comment]
Excellent!  Thanks for letting me know.  Closing this.
