### ISSUE TITLE
Locus name removal 

### ISSUE THREAD

**Issue by davecarlon** [faircloth-lab/phyluce#60]
I get the following error message when using:
bid25406:ngs dcarlon$ phyluce_align_remove_locus_name_from_nexus_lines --alignments /Users/dcarlon/Desktop/NGS/taxon-set1/mafft-nexus/  --output /Users/dcarlon/Desktop/NGS/taxon-set1/mafft-nexus-clean/ --taxa 3

**Error message**
RunningTraceback (most recent call last):
  File "/Users/dcarlon/anaconda/bin/phyluce_align_remove_locus_name_from_nexus_lines", line 138, in <module>
    main()
  File "/Users/dcarlon/anaconda/bin/phyluce_align_remove_locus_name_from_nexus_lines", line 126, in main
    results = map(worker, work)
  File "/Users/dcarlon/anaconda/bin/phyluce_align_remove_locus_name_from_nexus_lines", line 102, in worker
    assert len(all_taxa) == args.taxa, "Taxon names are not identical"
AssertionError: Taxon names are not identical
bid25406:ngs dcarlon$ phyluce_align_remove_locus_name_from_nexus_lines --ali

The taxon names should be all the same in all alignments. They have this general format in the nexus file:

#NEXUS
begin data;
	dimensions ntax=7 nchar=119;
	format datatype=dna missing=? gap=-;
matrix
'uce-668_pfish_490_Sc_Baja'   CCAGCCAGATGACGAGCATCACGCAGAGCGACATCATCAGCACGCTGCAGTCGCTCAACATGGTGAAGTACTGGAAGGGTCAGCACGTCATCTGTGTCACCCCCAAACTGGTGGAGGAG
'uce-668_pfish_496_Sc_Baja'   

Its also not clear to me what the --taxa flag is for? Min or max taxa in the set of alignments?

**Comment by brantfaircloth** [comment]
Try dropping the taxa argument.

**Comment by davecarlon** [comment]
That worked. Thank you.
