### ISSUE TITLE
trimmomatic issue

### ISSUE THREAD

**Issue by confrench33** [faircloth-lab/phyluce#61]
Hello Brian, I'm working through your phyluce tutorial and when I try to run illumiprocessor to clean the reads I get this error:

Traceback (most recent call last):
  File "/home/jason/anaconda2/bin/illumiprocessor", line 17, in <module>
    sys.exit(main())
  File "/home/jason/anaconda2/lib/python2.7/site-packages/illumiprocessor/cli/main.py", line 131, in main
    main(args)
  File "/home/jason/anaconda2/lib/python2.7/site-packages/illumiprocessor/main.py", line 22, in main
    core.check_dependencies(args)
  File "/home/jason/anaconda2/lib/python2.7/site-packages/illumiprocessor/core.py", line 259, in check_dependencies
    java.test_trimmomatic(args.trimmomatic)
  File "/home/jason/anaconda2/lib/python2.7/site-packages/illumiprocessor/core.py", line 252, in test_trimmomatic
    "Trimmomatic does not appear to be installed"
AssertionError: Trimmomatic does not appear to be installed

However, 
`conda search trimmomatic` returns 

> Fetching package metadata .........
trimmomatic               *  0.32                          1  http://conda.binstar.org/faircloth-lab 

I know trimmomatic is installed, but for some reason it's not being recognized. I'm running java 1.7 on Ubuntu 16.04, so I don't think java is the problem (I mention this because the core.py program tests for java just before testing for trimmomatic). Do you have any ideas what might be going on? Thanks.

**Comment by brantfaircloth** [comment]
if you run ```java -jar ~/anaconda2/jar/trimmomatic.jar``` what output do you get?

**Comment by brantfaircloth** [comment]
also, can you send output of ```java -version```?  thx!

**Comment by confrench33** [comment]
Hi Brant,
I appreciate the quick response. 
`java -jar ~/anaconda2/jar/trimmomatic.jar` returns:
Usage: 
       PE [-threads <threads>] [-phred33|-phred64] [-trimlog <trimLogFile>] [-basein <inputBase> | <inputFile1> <inputFile2>] [-baseout <outputBase> | <outputFile1P> <outputFile1U> <outputFile2P> <outputFile2U>] <trimmer1>...
   or: 
       SE [-threads <threads>] [-phred33|-phred64] [-trimlog <trimLogFile>] <inputFile> <outputFile> <trimmer1>...

and `java -version` returns:
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

**Comment by brantfaircloth** [comment]
huh, weird.  can you try passing this path to trimmomatic to illumiprocessor?  (can't remember which flag that is and on my phone for the weekend - run illumiprocessor --help to see choices)

**Comment by confrench33** [comment]
I just took a look at the default path for the --trimmomatic argument, and it wants to direct to /anaconda/jar/trimmomatic.jar instead of /anaconda2/jar/trimmomatic.jar. When I manually input the path for the --trimmomatic argument, the process runs correctly. Thank you very much!
