### ISSUE TITLE
Temporary directory. 

### ISSUE THREAD

**Issue by skgumma** [faircloth-lab/phyluce#62]
From the documents, there's no way to set the temporary directory, which causing my job to fail. I'm using phyluce_probe_run_multiple_lastzs_sqlite and it's writing to /tmp directory, however the diskspace in /tmp is too less for my job to finish, is there a way to set different directory as temporary file location.

**Comment by brantfaircloth** [comment]
The location `/tmp` is selected by default depending on your particular python installation and/or operating system. You should be able to manually change the default `tmpdir` by setting the `TMPDIR`, `TEMP` or `TMP` environment variables in your particular OS.

**Comment by skgumma** [comment]
Thanks for the response @brantfaircloth . I have another trouble. I'm running with 24 cores, however, when I see the top output, I can only see one process running just with 100% process utilization. Please can you suggest what is the issue.

**Comment by brantfaircloth** [comment]
first, please file a new issue.  it's not clear to me what program you are running when having this problem and what your input files are.  also need to know OS and version of OS.  this has not been reported before.

-b

**Comment by skgumma** [comment]
Thanks for your response @brantfaircloth I will raise a new issue with all required details. I'm marking this ticket as closed.
