### ISSUE TITLE
--core has no effect

### ISSUE THREAD

**Issue by skgumma** [faircloth-lab/phyluce#63]
The command what I'm executing is **phyluce_probe_run_multiple_lastzs_sqlite  --probefile stemim1+3.temp-DUPE-SCREENED.probes    --scaffoldlist Lipmaca Songxia acaGeni stemim1      --genome-base-path ../uce-liphistiidae/genomes      --identity 50      --cores 24   --db stemim1+3+acaGeni.sqlite      --output liphistiidae-genome-lastz**

I'm running this program in Cent OS 6.8, and  anaconda2  installed in my home directory. 

The expectation is i should use 24 cores with 24 processes or 2400% utilization, however when I see the top output, I only see 100% utilization, hence the rest of 23 cores are being not utilized, which eventually slowdown the output I guess. 

Thanks in advance for suggestions.

**Comment by brantfaircloth** [comment]
I've not observed this behavior before, also running on CentOS 6.8 and with anaconda2 in $HOME.  I'm not sure what the issue could be, other than that the "genomes" you are inputting are < 10 Mbp.  In that case, they don't get chunked into smaller pieces, and those smaller pieces don't then get sent to multiple processes, which results in the utilization being 100% versus 2400%.

**Comment by brantfaircloth** [comment]
No response.
