### ISSUE TITLE
IOError in assembly step

### ISSUE THREAD

**Issue by juancholkovich** [faircloth-lab/phyluce#64]
@brantfaircloth 

Dear Dr.Faircloth

My name is Juan Henao from Colombia, I writing to you because I have a problem following the first tutorial. The problem is when I try to carry out the assembly process, I received this error message:

IOError: Neither Trinity.fasta nor trinity.log were found in output.

I am tried to fix this error but definitely, I can't. What is the cause of this error and how I can fix it?

Best regards.

Juan D. Henao

**Comment by brantfaircloth** [comment]
Hi Juan, it sounds like the assembly is failing for some reason.  You may be able to look into the `trinity.log` file to see what the error is/was.  If you are assembling on a laptop or small desktop, it could be that you are running out of RAM.

**Comment by brantfaircloth** [comment]
No response.
