### ISSUE TITLE
IOError: There is a problem with the read names

### ISSUE THREAD

**Issue by leonvarhan** [faircloth-lab/phyluce#65]
Hello Brant, 
I'm working through the phyluce tutorial, and I keep getting the error message:

line 105, in _get_read_data
    "errors in your conf file.".format(self.start_name))
IOError: There is a problem with the read names for Alligator_mississippiensis_GGAGCTATGG. Ensure you do not have spelling/capitalization errors in your conf file.

I copied the text from http://phyluce.readthedocs.io/en/latest/tutorial-one.html  to create the .conf file and converted it to plain text. 

This is the command: 
illumiprocessor --trimmomatic --input raw-fastq  --output clean-fastq --config illumiprocessor.conf --r1-pattern '{}_(R1|READ1|Read1|read1)_\d+.fastq(?:.gz)*' --r2-pattern '{}_(R2|READ2|Read2|read2)_\d+.fastq(?:.gz)*' --cores 1

Any suggestions would be greatly appreciated, 
Thank you

**Comment by JennaMcCullough** [comment]
How was this resolved? I am having a similar issue with my own data:

>illumiprocessor --input raw_data --output cleaned_reads --config illumiprocessor.conf --trimmomatic /home/vosea/anaconda2/jar/trimmomatic.jar --log-path logs --cores 12
