### ISSUE TITLE
phyluce_probe_get_tiled_probes error

### ISSUE THREAD

**Issue by solenopsis1840** [faircloth-lab/phyluce#66]
Hi,
I'm trying to design UCE probes but get the following error trying to design the temporary bait set from my base taxon:

phyluce_probe_get_tiled_probes  --input ferVir1+5.fasta  --probe-prefix "uce-"  --design mealybug-v1 --designer gotzek --tiling-density 3  --two-probes  --overlap middle   --masking 0.25  --remove-gc  --output ferVir1+5.temp.probes
Probes removed for masking (.) / low GC % (G) / ambiguous bases (N):
Traceback (most recent call last):
  File "/Users/dgotzek/anaconda/envs/phyluce/bin/phyluce_probe_get_tiled_probes", line 375, in <module>
    main()
  File "/Users/dgotzek/anaconda/envs/phyluce/bin/phyluce_probe_get_tiled_probes", line 262, in main
    global_chromo, global_chromo_positions = global_coords.split(':')
ValueError: need more than 1 value to unpack

This happens using phyluce 1.5.0 on both my laptop (MacOSX 10.12.4 with conda 4.3.16 build 2.1.10 and python 2.7.13.final.0) and our LINUX cluster (linux-64 with miniconda2 4.3.11 and python 2.7.13.final.0). 

Any help is greatly appreciated!
Thanks,
Dietrich

**Comment by brantfaircloth** [comment]
hi Dietrich, can you send me your ferVir1+5.fasta file (or a portion of 
it)?

-b

**Comment by solenopsis1840** [comment]
Hi Brant,
Thanks for the quick reply! I just sent you a dropbox invite. The file is in the bed folder. 
Cheers,
Dietrich

**Comment by ClearloveMiao** [comment]
@solenopsis1840 
Hi!
How to fix this problem? `ValueError: need more than 1 value to unpack`
Thanks a lot!

**Comment by ymilesz** [comment]
Hi Brant,

  I've also encountered this problem after trying a new base genome, it was working fine before. 

Thanks,

Miles
