### ISSUE TITLE
phyluce_probe_run_multiple_lastzs_sqlite error

### ISSUE THREAD

**Issue by RandolphQuek** [faircloth-lab/phyluce#67]
Hi Dr Faircloth and members of the community,

I have encountered an error with the above file and hope I could get some help! I seem to keep getting this error: ConfigParser.NoSectionError: No section: 'lastz' when I try running the code according to the tutorial!

I understand from twitter that I have been advised that I am missing the config file, which was what I have been suspecting and trying to get it to read the config file. However, it still doesn't seem to work!

According to the twitter response, I seem to be missing the config file. the following file needs to be at ~/.phyluce.conf:

How should I go about it? Do I need to change the path directory in the config file or place it in a particular folder?

Apologies for bothering you again and hope you could help me with this! I have been struggling with this for several days now and I am still trying various permutations and trying to get it to work!

Thanks for any help!

Regards,

Randolph Quek.

**Comment by brantfaircloth** [comment]
randolph,

have you installed phyluce using conda?  it should have installed the config file, as well.

-b

**Comment by RandolphQuek** [comment]
Hi Dr Faircloth,

Yes I did install it using conda as per the instructions in the tutorial! Would you advise that I uninstall and reinstall the program?

Thanks for your help so far!

Regards,

Randolph Quek.

**Comment by brantfaircloth** [comment]
You can paste the contents of https://github.com/faircloth-lab/phyluce/blob/master/config/phyluce.conf into a file located at `~/.phyluce.conf`.  Also make sure you install `git`.
