### ISSUE TITLE
phyluce_probe_easy_lastz error

### ISSUE THREAD

**Issue by solenopsis1840** [faircloth-lab/phyluce#68]
Hi Brant,

Yet another issue cropped up designing probes: phyluce_probe_easy_lastz chokes on both my Mac and the cluster with different error messages (see below). I started the probe design from scratch because the wonky headers got the best of me (and phyluce) and I made sure the input files were cleaned up. This new error is odd, because it ran for me before.

Any help is greatly appreciated!
Thanks,
Dietrich

Mac 10.12.5:
(phyluce) Dietrichs-MBP:bed dgotzek$ phyluce_probe_easy_lastz --target ferVir1+5.temp.probes --query ferVir1+5.temp.probes --identity 50 --coverage 50 --output ferVir1+5.temp.probes-TO-SELF-PROBES.lastz
Started:  Wed May 24, 2017  06:58:52
Traceback (most recent call last):
  File "/Users/dgotzek/anaconda/envs/phyluce/bin/phyluce_probe_easy_lastz", line 80, in <module>
    main()
  File "/Users/dgotzek/anaconda/envs/phyluce/bin/phyluce_probe_easy_lastz", line 74, in main
    raise IOError(lztstderr)
IOError: /bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `/Users/dgotzek/anaconda/envs/phyluce/bin/lastz /Users/dgotzek/Dropbox (Smithsonian)/MealyBug_UCEs/bed/ferVir1+5.temp.probes[multiple,nameparse=full] /Users/dgotzek/Dropbox (Smithsonian)/MealyBug_UCEs/bed/ferVir1+5.temp.probes[nameparse=full]                --strand=both                 --seed=12of19                 --transition                 --nogfextend                 --nochain                 --gap=400,30                 --xdrop=910                 --ydrop=8370                 --hspthresh=3000                 --gappedthresh=3000                 --noentropy                 --coverage=50.0                 --identity=50.0                 --output=/Users/dgotzek/Dropbox (Smithsonian)/MealyBug_UCEs/bed/ferVir1+5.temp.probes-TO-SELF-PROBES.lastz                 --format=general-:score,name1,strand1,zstart1,end1,length1,name2,strand2,zstart2,end2,length2,diff,cigar,identity,continuity'

Linux (64-bit CentOS 6.5) cluster:
[dgotzek@n15 bed]$ phyluce_probe_easy_lastz --target ferVir1+5.temp.probes --query ferVir1+5.temp.probes --identity 50 --coverage 50 --output ferVir1+5.temp.probes-TO-SELF-PROBES.lastz
Started:  Wed May 24, 2017  06:59:18
Traceback (most recent call last):
  File "/usr/local/apps/phyluce/1.5.0/bin/phyluce_probe_easy_lastz", line 80, in <module>
    main()
  File "/usr/local/apps/phyluce/1.5.0/bin/phyluce_probe_easy_lastz", line 71, in main
    alignment = lastz.Align(args.target, args.query, args.coverage, args.identity, args.output, args.min_match)
  File "/usr/local/apps/phyluce/1.5.0/lib/python2.7/site-packages/phyluce/lastz.py", line 78, in __init__
    --format=general-:score,name1,strand1,zstart1,end1,length1,name2,strand2,zstart2,end2,length2,diff,cigar,identity,continuity'.format(target, query, coverage, identity, self.output, get_user_path("lastz", "lastz"))
  File "/usr/local/apps/phyluce/1.5.0/lib/python2.7/site-packages/phyluce/pth.py", line 27, in get_user_path
    pth = config.get(program, binary)
  File "/usr/local/apps/anaconda/2.2.0/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'lastz'

**Comment by brantfaircloth** [comment]
Hi Dietrich,

In the first, the parentheses, “(“ and “)”, in the path to the 
Dropbox directory appear to be causing the problem.

In the second, it looks like you are missing the config file for 
phyluce.  That file should be in `~/anaconda/config/phyluce.conf` 
(assuming your anaconda is in `~/anaconda`.  Alternatively, you can 
place the contents of that file 
(https://github.com/faircloth-lab/phyluce/blob/master/config/phyluce.conf) 
in `~/.phyluce.conf`.

cheers,
b

**Comment by solenopsis1840** [comment]
Weird, the path to dropbox never caused an issue for other programs. But it did the trick this time, thanks. 

As for the missing config file for the server installation, I've let the gacrc folks know. 
Cheers,
Dietrich

**Comment by brantfaircloth** [comment]
cool.  closing the issue for now.
