### ISSUE TITLE
regular expression for Trinity contig name 

### ISSUE THREAD

**Issue by lijingbu** [faircloth-lab/phyluce#71]
When using phyluce_assembly_match_contigs_to_probes, I found out the regex in config/phyluce.conf not working in the trinity 2.4.0 results.
Made changes below and works. Not familiar with python, but is this because of different python version? I use 2.7, not 3. 

 49 [headers]
 50 #trinity:comp\d+_c\d+_seq\d+|c\d+_g\d+_i\d+|TR\d+\|c\d+_g\d+_i\d+
 51 trinity:comp\d+_c\d+_seq\d+|c\d+_g\d+_i\d+|TR\w+\d+\_c\d+_g\d+_i\d+

**Comment by brantfaircloth** [comment]
No, everything should be setup for Python 2.7.  It's more likely a trinity issue - they tend to change headers a lot, which is why i made the regex easier to set/change in the config file.

**Comment by lijingbu** [comment]
Cool. Thanks.

**Comment by brantfaircloth** [comment]
No problem!
