### ISSUE TITLE
phyluce_align_filter_alignments input argument 

### ISSUE THREAD

**Issue by lijingbu** [faircloth-lab/phyluce#72]
Little issue: 

Line 136 of file phyluce_align_filter_alignments 
`136     files = get_files(args.input, args.input_format)`
need to be
`136     files = get_files(args.alignments, args.input_format)`

because the input was not set up as one of the arguments. 
Thanks.

**Comment by brantfaircloth** [comment]
this should be fixed in the working branch of the code.

-b

**Comment by lijingbu** [comment]
Great. Thanks.
