### ISSUE TITLE
ignoring bad/non-existent assemblies 

### ISSUE THREAD

**Issue by mike2vandy** [faircloth-lab/phyluce#77]
I have a fairly large UCE data set of (~170 samples) and I've started phyluce_assembly_assemblo_trinity. I know the sequencing was so poor for some samples that they wont assemble. However, instead of dying
when a Trinity.fas can't be found, I want to make the script skip that sample and move on to the next.

That being said I have a few questions:

1) By chance do you already know/have a hack for that?

2) I've noticed if an output directory already exists, phyluce quits. Is that always true whether a sample has already been fully processed or not?

**Comment by brantfaircloth** [comment]
ok, with regards to question 1: first suggestion is to filter the input data to remove those samples from the config file that have << 100k reads.  usually, these are non-starters.

second suggestion is to change lines 279-280 in [phyluce_assembly_assemblo_trinity](https://github.com/faircloth-lab/phyluce/blob/master/bin/assembly/phyluce_assembly_assemblo_trinity#L279-L280) from:
```
except:
    raise IOError("Neither Trinity.fasta nor trinity.log were found in output.")
```
to:
```
except:
    log.critical("Neither Trinity.fasta nor trinity.log were found in output.")
```
which should stop the error (and log which files failed).  that said, i haven't tried this.

with regards to question 2, the program tries to create a directory for the sample it's currently processing and will fail if a directory already exists.  two ways around this problem are to (1) comment out that sample(s) in the config file and restart or (2) edit line 320 of [phyluce_assembly_assemblo_trinity](https://github.com/faircloth-lab/phyluce/blob/master/bin/assembly/phyluce_assembly_assemblo_trinity#L320) from:
 
```
os.makedirs(sample_dir)
```
to:
```
if not os.path.isdir(sample_dir):
    os.makedirs(sample_dir)
else:
    pass
```
Again, haven't tried this, so YMMV.

**Comment by mike2vandy** [comment]
I had to make a few modifications to your suggestions, but I was able to change the code to do what I want (skip finished assemblies and ignore bad assemblies without quitting). It probably is easier to just change the config file, but it is nice just letting phyluce finish all samples it's presented with. 

Thanks for the help.
