### ISSUE TITLE
error due to Trinity parameter --JM

### ISSUE THREAD

**Issue by bryansmclean** [faircloth-lab/phyluce#79]
Brant (et al.)

Im having an issue with Trinity assembly of paired-end Illumina reads. The error message from trinity.log is:

ERROR, don't recognize parameter: --JM
Please review usage info for accepted parameters.

assemblo_trinity.py works up through copying raw read data and combining singleton reads, but fails with this message:

2017-08-25 09:13:39,936 - assemblo_trinity - INFO - Running Trinity.pl for PE data
2017-08-25 09:13:40,083 - assemblo_trinity - WARNING - Did not clean all fastq/fasta files from /ufrc/guralnick/bryanmclean/trin_1a/Uarmatus_NK216605
2017-08-25 09:13:40,083 - assemblo_trinity - INFO - Symlinking assembled contigs into /ufrc/guralnick/bryanmclean/trin_1a/contigs
2017-08-25 09:13:40,084 - assemblo_trinity - INFO - =================== Completed assemblo_trinity ==================

A little internet trolling suggests the issue could be due to memory, but it occurs even if I allocate many more resources (the amount of which is also correctly specified in my .conf file). Wondering if this stems from using an incompatible version of Trinity (our hpc runs Trinity 2.2.0).

Thanks
Bryan

**Comment by brantfaircloth** [comment]
Hmm.  possible that it may be that it's the version of trinity on your cluster.  Basically, what happens is this - the code tries to run the following:

https://github.com/faircloth-lab/phyluce/blob/master/bin/assembly/phyluce_assembly_assemblo_trinity#L132-L149

If that does not work, the code defaults to running:

https://github.com/faircloth-lab/phyluce/blob/master/bin/assembly/phyluce_assembly_assemblo_trinity#L151-L167

Which includes the `--JM` parameter (and is meant for Trinity v1).  So, my guess is that whichever version of Trinity is on your HPC machines dies when the first bit of code runs, but then the code tries to run the 2nd bit, which is really meant for versions of Trinity that are pre-V2.  That also fails.

The way to fix this is to try and see what parameter/option is causing trinity to die in that first bit of code (you can just try to directly run trinity with these parameters on the HPC, see which ones fails, then edit the code).  It could be a version issue (e.g. different flags) or it could be that trinity is having some other problem (if trinity actually ran, you can also look in the output logs generated by trinity for additional clues).

-b

**Comment by bryansmclean** [comment]
Update on this: assemblo_trinity.py seems to be working for me if I rely on Trinity v1.x (2014) and devote enough computing power (48GB RAM).
