### ISSUE TITLE
Viewing "matches table" and "match_map table"

### ISSUE THREAD

**Issue by jpicathartes** [faircloth-lab/phyluce#80]
Hi Brant--

I recognize this is probably of minor concern, but I've been having issues properly viewing the "matches" and "match_map table" created by sqlite. I've followed the tutorial commands verbatim, and they work, but instead of producing neat and orderly tables, I am instead seeing a messy and ineligible jumble. 

I've been successful at creating a data matrix (using phyluce_assembly_get_match_counts), so I don't think there are issues with matching the probes to contigs -- it appears to be mostly cosmetic. However, it's still frustrating. Any recommendations? Perhaps there is a setting in my terminal that would fix this issue? I'm operating Linux (Ubuntu). 

Thanks in advance
Jack

**Comment by brantfaircloth** [comment]
Hi Jack,

This might help - you can create an `~./sqliterc` file with some formatting commands that will start sqlite in a prettier/more useful mode.  On the computer you are using to view the database, create this file (aka `$HOME/.sqliterc`) with the following contents:

```
.mode columns
.headers on
.nullvalue .
```

Then, just run sqlite like norma. That should help pretty things up a bit.

-b

**Comment by jpicathartes** [comment]
Hi Brant--

Many thanks for the quick reply. My apologies, I am bit a new to SQLite, so it has taken me a while to learn and navigate SQL. I apologize in advance for my ignorance on all of this. I clearly have a lot to learn. 

Will  I need to transfer all of the information (matches and match_map tables) from the probe.matches.sqlite file to the new sqliterc file? I understand the commands at the bottom will modify the format of the file, but I am having a hard time figuring out how this differs (apart from the matches and match_map tables now appearing in a different file), from what is stated in phyluce documentation, where it asks for those commands to be run with probe.matches.sqlite. 

.mode columns
.headers on
.nullvalue . 

Thanks in advance
Jack

**Comment by brantfaircloth** [comment]
What I wrote is not different from what's in the tutorial - it just makes those changes "stick" every time you open sqlite.

I guess maybe I'm not understanding the problem you are running into - it may simply be that you are trying to query too many columns of information at once, and that is wrapping in your terminal window, making things look ugly.

So, a few solutions here:

1) Query fewer columns of information at a time
2) Make your terminal window larger (hard to do on a laptop)
3) Output the query results to CSV and open in the CSV Excel (which will give you prettier output)

The 3rd option is relatively easy, you would run (in sqlite3):
```
sqlite>.mode csv
sqlite>.output name_of_file_you_want_to_create.csv
sqlite>SELECT * FROM match_map;
sqlite>.quit
```
Then, in the same directory where the sqlite database lives (i.e., where `probe.matches.sqlite` is), there should be a new file, entitled `name_of_file_you_want_to_create.csv`.  You can open that in excel.

**Comment by jpicathartes** [comment]
Hi Brant--

Exporting the results to a CSV definitely helped organize the tables. 

Many thanks for all the help. 

Jack
