### ISSUE TITLE
Run Phyluce with java 1.8

### ISSUE THREAD

**Issue by patrick-douglas** [faircloth-lab/phyluce#83]
The JDK 1.7 is no longer Available, so there is any way to run phyluce using JDK 1.8?

**Comment by brantfaircloth** [comment]
yes.  is there a particular script that is giving you problems?

-b

**Comment by patrick-douglas** [comment]
I'm getting the following error:
```
Error, Trinity requires access to Java version 1.7.  Currently installed version is: openjdk version "1.8.0_92"
OpenJDK Runtime Environment (Zulu 8.15.0.1-linux64) (build 1.8.0_92-b15)
OpenJDK 64-Bit Server VM (Zulu 8.15.0.1-linux64) (build 25.92-b15, mixed mode)
```

**Comment by brantfaircloth** [comment]
This is likely going to require a recompile of trinity to work with whichever version of java is now commonplace.  The best way to do this sooner rather than later is to locally compile Trinity, then change the `~/.phyluce.conf` file to point at that version of Trinity.  I am unlikely to get to updating the conda code for phyluce for at least a month because of other time-constraints.

**Comment by patrick-douglas** [comment]
Were is located the `~/.phyluce.conf`?
Or I just need create it?

**Comment by brantfaircloth** [comment]
You should be able to create it.  You can also use full paths (e.g. no variable expansion).  Mine looks like:

```
[abyss]
abyss:$CONDA/bin/ABYSS
abyss-pe:$CONDA/bin/abyss-pe

[bowtie]
bowtie:$CONDA/bin/bowtie

[bwa]
bwa:$CONDA/bin/bwa

[gblocks]
gblocks:$CONDA/bin/gblocks

[trimal]
trimal:$HOME/git/trimal/source/trimal

[java]
executable:java
mem:-Xmx46g
jar:$CONDA/jar
gatk:GenomeAnalysisTKLite.jar

[lastz]
lastz:$CONDA/bin/lastz

[mafft]
mafft:$CONDA/bin/mafft

[muscle]
muscle:$CONDA/bin/muscle

[raxml]
raxmlHPC-SSE3:$CONDA/bin/raxmlHPC-SSE3
raxmlHPC-PTHREADS-SSE3:$CONDA/bin/raxmlHPC-PTHREADS-SSE3

[samtools]
samtools:$CONDA/bin/samtools
bcftools:$CONDA/bin/bcftools
vcfutils:$CONDA/bin/vcfutils.pl

[seqtk]
seqtk:$HOME/bin/seqtk

[trinity]
#trinity:$HOME/bin/trinity
trinity:$HOME/src/trinityrnaseq_r2013-02-25/Trinity.pl
#max_memory:46G
kmer_coverage:2
jellyfish_memory:36G

[velvet]
velvetg:$CONDA/bin/velvetg
velveth:$CONDA/bin/velveth

#----------------
#    Advanced
#----------------

[headers]
trinity:comp\d+_c\d+_seq\d+|c\d+_g\d+_i\d+|TR\d+\|c\d+_g\d+_i\d+
velvet:node_\d+
```

**Comment by patrick-douglas** [comment]
I jus replaced all files inside the folder `/home/me/anaconda2/bin/trinity-2.0.6` by binaries of Trinity 2.4 version.
Apparently this solved my problem
thank you

**Comment by brantfaircloth** [comment]
cool.  obviously, that's another way to do it!

**Comment by patrick-douglas** [comment]
I good thing to do is update the Trinity version in Phyluce repo, is possible?

**Comment by brantfaircloth** [comment]
it's possible - it will just take me some time to get around to doing it (many other things going on).

**Comment by patrick-douglas** [comment]
Ok, thank you!
I suggest the following:
When a user issue the command `conda install phyluce` the installation process download trinity directly from Trinity Git Hub repo instead download Trinity from Phyluce repo.
This way is better because is possible get the latest version of Trinity

**Comment by brantfaircloth** [comment]
It's not quite that simple - there has to be a conda package built for trinity and that has to be available.  So, I either have to build that and upload it or I have to get it from somewhere else (like the bioconda package repository).

**Comment by patrick-douglas** [comment]
I think the best way is update the bioconda repo
