### ISSUE TITLE
Trinity Java 1.7 requirements

### ISSUE THREAD

**Issue by KNx5** [faircloth-lab/phyluce#85]
Greetings, I’m no longer able to download the 1.7 versión of Java.
Sudo apt-get install openjdk-7-jre 
returns a package deleted error

What workaround are people using?

**Comment by brantfaircloth** [comment]
Yeah, this is an exciting new wrinkle that I need to fix (but that will take time).  So, you have several options...

(1) you could download trinity, build it on your own, and then change the path to trinity in ~/.phyluce.conf using a section like:

```
[trinity]
trinity:$CONDA/bin/Trinity
max_memory:8G
kmer_coverage:2
```

(2) you could try to install java 1.7 using the PPA (e.g. https://askubuntu.com/questions/761127/how-do-i-install-openjdk-7-on-ubuntu-16-04-or-higher)

On CentOS, it appears that Java 1.7 is still available.  On OSX, options seem more limited...

**Comment by drwhitehouse** [comment]
Is trinity the only thing that needs java here?  
Java 1.7 presents real problems in HPC / Container environments so it would be good to avoid it in those circumstances.

**Comment by MikeWLloyd** [comment]
@brantfaircloth I've also had success with bowtie2. I've written some scripts wrapped around it, which play fairly well with your existing pipeline. I've been wanting to take a stab at integrating them fully with phyluce, but haven't had the chance. The scripts I have also provide the ability to get coverages of only those contigs that contain loci, in addition to all coverages of all contigs. If you are interested they are in a repo here [coverage scripts](https://github.com/MikeWLloyd/Sequencing-Coverage-Scripts)

**Comment by brantfaircloth** [comment]
@MikeWLloyd _Thanks_ for passing those along - I'll have a look.  Right now, I'm about to move phyluce to bioconda (see #110) which will help with some issues while creating some new ones (see also #110).  Overall, however, it will make my life easier.  Same thing with moving to itero - because it's based on BAM-formatted alignments + assembly, everything is easier to deal with than it was with Trinity, which is quite honestly, not that much fun to deal with...

**Comment by brantfaircloth** [comment]
Closing - not sure what else there is to resolve.  Hopefully, v.1.6.2 phyluce package on bioconda will fix remaining issues - that should be available soon and can be installed following http://phyluce.readthedocs.io/en/latest/installation.html
