### ISSUE TITLE
duplicate taxon name

### ISSUE THREAD

**Issue by wbsimey** [faircloth-lab/phyluce#86]
Hello Brant,
We are analyzing 350 taxa via the Phyluce Phylogenomics pipeline. Unfortunately, we named two of the taxa with the same name. It looks like the phyluce_assembly_assemblo_abyss script only processed the second duplicate name (according to the assemblo log file and the abyss-k35.err.log). It seems that I should be able to rerun the missing duplicate taxon with a new name by itself up to the trimming steps. Or is it best to start over with all 360 taxa from the assembly step?

**Comment by brantfaircloth** [comment]
Hi Brian,

You should be totally ok to go ahead and just re-assemble that single taxon.  the way to do that is just to change the left-hand side (left of colon) to the new name.  so, if your config file previously looked like:

```
[samples]
duplicate-name:/path/to/sample/data1
duplicate-name:/path/to/sample/data2
[...384 other samples...]
```

you could simply make a new config file with one line where you alter the name of the duplicate sample (the one that did not assemble):

```
[samples]
duplicate-name-updated:/path/to/sample/data1
```
then re-assemble.  this will run the re-assembly for only that single sample.  I would probably also change the output directory to something new, then copy back over the relevant data after assembly, just to make sure nothing gets borked.

-b

**Comment by wbsimey** [comment]
Thanks Brant,
UPDATE - I ran the assembly step against the renamed sample. But realized that the phyluce_assembly_match_contigs_to_probe script writes to a sqlite database file, which is then read by the phyluce_assembly_get_match_counts script. So, I moved the dirs and contig files generated by the assembly script to the appropriate dirs. Then reran phyluce_assembly_match_contigs_to_probe script against all of the data including the renamed sample.  I will then continue the pipeline with all taxa from there. This should work, right?

**Comment by brantfaircloth** [comment]
Yes, one way to do this is to rerun `phyluce_assembly_match_contigs_to_probe` followed by re-running `phyluce_assembly_get_match_counts`.  Another way to do it is to re-run `phyluce_assembly_match_contigs_to_probe` only against the sample or samples that are "new", and then run `phyluce_assembly_get_match_counts` with the `--extend-locus-db` option, where you pass the 2nd sqlite database created for the additional samples to the script.  After that, you'll need to run `phyluce_assembly_get_fastas_from_match_counts` with both the `--extend-locus-db` and `--extend-locus-contigs` options.

This latter option **seems** like more work but can save you substantial time (versus re-running all 300+ samples).
