### ISSUE TITLE
OSError: [Errno 17] File exists-- Illumiprocessor

### ISSUE THREAD

**Issue by jpicathartes** [faircloth-lab/phyluce#90]
Hello--

I've been having an issue carrying out adapter trimming with Illumiprocessor on de-multiplexed data of mine. 

**My raw files are named in the following manner, for example**

Pelecanus_occidentalis_B36816_R1_001.fastq.gz
Pelecanus_occidentalis_B36816_R2_001.fastq.gz

**When using the following code:**

llumiprocessor --input ./raw --output ./cleaned_reads --config Heron_preprocess_modified.conf --trimmomatic /home/hruska/anaconda2/jar/trimmomatic.jar --log-path logs --cores 4 --r1-pattern _R1_001 --r2-pattern _R2_001

**I've been receiving the following error message:**

ile "/home/hruska/anaconda2/bin/illumiprocessor", line 17, in <module>
    sys.exit(main())
  File "/home/hruska/anaconda2/lib/python2.7/site-packages/illumiprocessor/cli/main.py", line 131, in main
    main(args)
  File "/home/hruska/anaconda2/lib/python2.7/site-packages/illumiprocessor/main.py", line 36, in main
    core.create_new_dirs(reads)
  File "/home/hruska/anaconda2/lib/python2.7/site-packages/illumiprocessor/core.py", line 365, in create_new_dirs
    os.symlink(reads, new_file)
OSError: [Errno 17] File exists

Any information on what may be causing this issue would be greatly appreciated. 

Best
Jack

**Comment by brantfaircloth** [comment]
hi jack,

looks like you need to adjust the `--r1-pattern` and `--r2-pattern` inputs.  those need to be valid regular expressions.  the default `--r1-pattern` in the code looks like (`--r2-pattern` is basically the same):

```
self.r1_pattern = "{}_(?:.*)_(R1|READ1|Read1|read1)_\d+.fastq(?:.gz)*"
```

so, to work with your samples, you are going to need something like (haven't tested):

```
--r1-pattern {}_R1_\d+.fastq(?:.gz)*
--r2-pattern {}_R2_\d+.fastq(?:.gz)*
```

Where your config file contains `Pelecanus_occidentalis_B36816` for that sample.

**Comment by jpicathartes** [comment]
Hi Brant--

Many thanks for the quick reply. I really appreciate the help.

**I've attempted to input your recommended r1 and r2 regular expressions**:

llumiprocessor --input ./raw --output ./cleaned_reads --config Heron_preprocess_modified.conf --trimmomatic /home/hruska/anaconda2/jar/trimmomatic.jar --log-path logs --cores 4 --r1-pattern {}_R1_\d+.fastq(?:.gz)* --r2-pattern {}_R2_\d+.fastq(?:.gz)*

**with the following error message as a result**:
-bash: syntax error near unexpected token `('

Many thanks. 

Jack

**Comment by brantfaircloth** [comment]
put each inside quotes, like `”{}R1\d+.fastq(?:.gz)*”`.

**Comment by jpicathartes** [comment]
Ok, that got rid of that issue. 

**I've included the read patterns in quotations and now I'm back to my original error**:

 File "/home/hruska/anaconda2/bin/illumiprocessor", line 17, in <module>
    sys.exit(main())
  File "/home/hruska/anaconda2/lib/python2.7/site-packages/illumiprocessor/cli/main.py", line 131, in main
    main(args)
  File "/home/hruska/anaconda2/lib/python2.7/site-packages/illumiprocessor/main.py", line 36, in main
    core.create_new_dirs(reads)
  File "/home/hruska/anaconda2/lib/python2.7/site-packages/illumiprocessor/core.py", line 365, in create_new_dirs
    os.symlink(reads, new_file)
OSError: [Errno 17] File exists

**For more context**:

The first sample of my config file, Agamia_agami_B12815, appears to be processed, at least partially. 

**The following output is seen**:

In my working directory:

cleaned_reads
     agamia_agami_B12815
             raw-reads
                 agamia_agami_B12815-READ1.fastq.gz

After that, it seems to hit the snag and quits. 

Jack

**Comment by brantfaircloth** [comment]
you may also need to tweak your config file - make sure no entries are duplicated.  best way to do this is to smart small (with only a few samples in the file) and work up to larger numbers of samples.  the software creates aliases for everything, first, which is where the problem is cropping up.

also note in the patterns you used, you’re missing an underscore after the braces and before R1 and R2.

**Comment by jpicathartes** [comment]
Hi Brant--

Figured out the issue was related to inclusion of additional fastq.gz.md5 files in the raw_reads directory. Once those were removed, illumiprocessor worked. 

Many thanks for all of your help.

Jack
