### ISSUE TITLE
Issue creating SQlite tables

### ISSUE THREAD

**Issue by ragp89** [faircloth-lab/phyluce#95]
Hi there,

I am trying to find UCEs in some microalgae genomes I generated. To do this I have been following the Tutorial III. When I do it with the test datasets mentioned there everything works perfectly; however, when I try it with my data there are some issues at the `phyluce_probe_run_multiple_lastzs_sqlite step`. I think it might be related to few matches of UCEs in my genomes(?). This is what I get:  

```
$ phyluce_probe_run_multiple_lastzs_sqlite --db database.sqlite --output genomes-lastz --scaffoldlist gen1 gen2 gen3 gen4 gen4 --genome-base-path ./ --probefile uce-5k-probes.fasta --cores 12 --identity 70

Running against gen1.2bit
Running with the --huge option.  Chunking files into 10000000 bp...
Running the targets against 79 queries...
	/scratch/tmp/pbs.1544784.delta/tmpvsjHVh.fasta

< .. snip .. >

Writing the results file...
	/scratch/tmp/pbs.1544784.delta/tmpcIqyRl.lastz

< .. snip .. >

Cleaning up the chunked files...
Cleaning /path/to/genome-lastz/uce-5k-probes.fasta_v_gen1.lastz
Creating gen1 table
--Return--
> /path/to/miniconda2/bin/phyluce_probe_run_multiple_lastzs_sqlite(141)create_species_lastz_tables()->None
-> pdb.set_trace()
(Pdb) c    # here I told the debugger to continue
Inserting data to gen1 table
Traceback (most recent call last):
  File "/path/to/miniconda2/bin/phyluce_probe_run_multiple_lastzs_sqlite", line 258, in <module>
    main()
  File "/path/to/miniconda2/bin/phyluce_probe_run_multiple_lastzs_sqlite", line 251, in main
    align_against_scaffolds(cur, args, path)
  File "/path/to/miniconda2/bin/phyluce_probe_run_multiple_lastzs_sqlite", line 205, in align_against_scaffolds
    insert_species_to_lastz_tables(cur, g, clean)
  File "/path/to/miniconda2/bin/phyluce_probe_run_multiple_lastzs_sqlite", line 153, in insert_species_to_lastz_tables
    cur.executemany(query, rows)
sqlite3.OperationalError: disk I/O error
```

I don't understand what is happening and hope you can help me fix this issue.

Thanks in advance!

**Comment by brantfaircloth** [comment]
howdy.  what type of machine are you running on?  some HPC setups can have this IO error problem (e.g. lustre file systems) - see this thread for a similar issue:  https://github.com/CGATOxford/CGATPipelines/issues/39.

your genomes seem pretty small based on being placed into a single chunk during the search - have you tried to run this on a workstation (and possibly even a laptop)?

**Comment by brantfaircloth** [comment]
also, another option is to run on an actual disk on the node your are using to run the job - usually individual nodes have some scratch drives for this.

**Comment by ragp89** [comment]
Yes, I was running it on a HPC with lustre. Run with no issues on my computer. Thanks!!

**Comment by brantfaircloth** [comment]
👊
