### ISSUE TITLE
Ensure you do not have spelling/capitalization errors in your conf file

### ISSUE THREAD

**Issue by camilocalderon** [faircloth-lab/phyluce#96]
Hello, I keep receiving this message even when I have tried several naming schemes. 

-IOError: There is a problem with the read names for Geoffroyi_12. Ensure you do not have spelling/capitalization errors in your conf file.-

I have tried independently for 10 samples and keep receiving the same error. I have tried with no caps at the beginning of the name but doesn't work either. Looking at other "Issues" I have tried the format that other people say has worked for them. Any help is much appreciated. 

Running on macOS Sierra, Java version 1.7,  I attach too an image of how my data is named
![screen shot 2018-03-11 at 23 56 04](https://user-images.githubusercontent.com/8772224/37266424-f51c0480-2587-11e8-85a6-19c2e11dd431.png)

This is what my config file looks like:

[adapters]
i7:GATCGGAAGAGCACACGTCTGAACTCCAGTCAC*ATCTCGTATGCCGTCTTCTGCTTG
i5:AATGATACGGCGACCACCGAGATCTACACTATGCAGTACACTCTTTCCCTACACGACGCTCTTCCGATCT

[tag sequences]
59:GTGTTCTA
27:AGTCACTA

[tag map]
Geoffroyi_12:59
Geoffroyi_28:27

[names]
Geoffroyi_12:Geoffroyi12
Geoffroyi_28:Geoffroyi28

**Comment by brantfaircloth** [comment]
You may need to change the default regular expression used to find your reads using something like:

```
--r1-pattern = "{}_R1_\d+.fastq(?:.gz)*"
--r2-pattern = "{}_R2_\d+.fastq(?:.gz)*"
```
when you invoke the program.

**Comment by camilocalderon** [comment]
Thank you Dr. Faircloth, I will try this and post the results.

**Comment by camilocalderon** [comment]
Hello Dr. Faircloth, I changed the names I was using for my samples to include a larger part of the name of the sequence(i.e. GEOFFROYI12_S385_L003_R1_001.fastq.gz) and everything worked perfectly.
