### ISSUE TITLE
Parallelizing assemblo step

### ISSUE THREAD

**Issue by wbsimey** [faircloth-lab/phyluce#98]
Hi Brant,
I am comparing velvet, trinity and abyss assemblers in phyluce on a 36 core AWS instance.
I split the assembly.config file into 12 files and simultaneously ran twelve abyss assembly scripts such as this one:
#!/bin/bash
/home/ubuntu/anaconda2/bin/phyluce_assembly_assemblo_velvet \
    --config /home/ubuntu/ABySS/assembly_032118_12.conf \
    --output /home/ubuntu/ABySS/abyss-assemblies_032118 \
    --kmer 35 \
    --subfolder split-adapter-quality-trimmed \
    --cores 3 \
    --clean \
 --log-path /home/ubuntu/ABySS/log_032118/12

This worked like a charm; it finished assembling 140 data sets (taxa) in a couple hours rather than a couple days. However, it did not work for velvet. I got the ‘Output directory exists’ error and only one of the scripts ran. 

Any ideas why it works for abyss and not velvet? 

File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/phyluce/helpers.py", line 36, in __call__
    answer = raw_input("[WARNING] Output directory exists, REMOVE [Y/n]? ")

**Comment by wbsimey** [comment]
I think I found the answer in your python code:

for **phyluce_assembly_assemblo_abyss**:
inside your definition of get_args,  you have:
`    parser.add_argument(
        "--output",
        required=True,
        action=CreateDir,
        default=None,
        help="""The directory in which to store the assembly data"""`
for **phyluce_assembly_assemblo_velvet** is is:
`    parser.add_argument(
        "--output",
        required=True,
        action=FullPaths,
        default=None,
        help="""The directory in which to store the assembly data"""`
I will try to edit the **phyluce_assembly_assemblo_velvet** code and see what happens. 
Will report back.

**Comment by wbsimey** [comment]
Changing the 'action' argument from 'CreateDir' to 'FullPaths' worked. 
I can now run multiple instances of velveth across multiple .conf files.

**Comment by liugang9988** [comment]
> I think I found the answer in your python code:
> 
> for **phyluce_assembly_assemblo_abyss**:
> inside your definition of get_args, you have:
> ` parser.add_argument( "--output", required=True, action=FullPaths, default=None, help="""The directory in which to store the assembly data"""`
> for **phyluce_assembly_assemblo_velvet** is is:
> ` parser.add_argument( "--output", required=True, action=CreateDir, default=None, help="""The directory in which to store the assembly data"""`
> I will try to edit the **phyluce_assembly_assemblo_velvet** code and see what happens.
> Will report back.


-----------------------

Hi, I had the same problem. answer = raw_input("[WARNING] Output directory exists, REMOVE [Y/n]? "). Here is the  **phyluce_assembly_assemblo_velvet** code below:
phyluce_assembly_assemblo_velvet \
--config ./assembl1.config \
--output ./velvet_uce_assembly1 \
--subfolder split-adapter-quality-trimmed \
--kmer 35 \
--clean \
--cores 48 \
--log-path velvet_assembly1_log

Could you please help to look what my code is wrong? Thank you very much.
